/**
 * Owned concern: stable route-level semantic reason tokens used by the HTTP
 * runtime error translation boundary.
 */
export const HTTP_ERROR_REASON = Object.freeze({
  adapterNotConfigured: 'adapter_not_configured',
  cancelReasonNotSupported: 'cancel_reason_not_supported',
  clientRunIdNotAllowed: 'client_run_id_not_allowed',
  conflictingRunIds: 'conflicting_run_ids',
  conflictingPlanInputs: 'conflicting_plan_inputs',
  internalError: 'internal_error',
  invalidAfterSeq: 'invalid_after_seq',
  invalidBody: 'invalid_body',
  invalidCredentialReference: 'invalid_credential_reference',
  invalidDbtProjectGraphRequest: 'invalid_dbt_project_graph_request',
  invalidDbtDependencyEditRequest: 'invalid_dbt_dependency_edit_request',
  invalidSelectedDbtModelAnalysisRequest: 'invalid_selected_dbt_model_analysis_request',
  invalidDbtProjectImportRequest: 'invalid_dbt_project_import_request',
  invalidDbtYamlDescriptionEditRequest: 'invalid_dbt_yaml_description_edit_request',
  invalidEnrichedFlag: 'invalid_enriched_flag',
  invalidGraphDbtWorkspaceArtifactPublicationRequest:
    'invalid_graph_dbt_workspace_artifact_publication_request',
  invalidGraphDbtModelCompilationRequest: 'invalid_graph_dbt_model_compilation_request',
  invalidEnvironmentId: 'invalid_environment_id',
  invalidLimit: 'invalid_limit',
  invalidPreviewProfile: 'invalid_preview_profile',
  invalidPlanRef: 'invalid_plan_ref',
  invalidPlanSource: 'invalid_plan_source',
  invalidProjectId: 'invalid_project_id',
  invalidWorkspaceSourceYaml: 'invalid_workspace_source_yaml',
  invalidWorkspaceDiffChanges: 'invalid_workspace_diff_changes',
  invalidWorkspaceFileRevision: 'invalid_workspace_file_revision',
  invalidWorkspacePath: 'invalid_workspace_path',
  invalidRunExecutionContextRef: 'invalid_run_execution_context_ref',
  invalidRunId: 'invalid_run_id',
  invalidSelection: 'invalid_selection',
  invalidSignalType: 'invalid_signal_type',
  invalidTargetAdapter: 'invalid_target_adapter',
  invalidTenantId: 'invalid_tenant_id',
  limitOutOfRange: 'limit_out_of_range',
  missingEnvironmentId: 'missing_environment_id',
  missingIdempotencyKey: 'missing_idempotency_key',
  missingProjectId: 'missing_project_id',
  missingTenantId: 'missing_tenant_id',
  missingTenantScope: 'missing_tenant_scope',
  planRejected: 'plan_rejected',
  postgresTransformSqlNotReady: 'postgres_transform_sql_not_ready',
  runAlreadyExists: 'run_already_exists',
  runControlUnavailable: 'run_control_unavailable',
  runMaterializationSampleUnavailable: 'run_materialization_sample_unavailable',
  runRecoveryUnavailable: 'run_recovery_unavailable',
  runNotFound: 'run_not_found',
  sourceRunNotTerminal: 'source_run_not_terminal',
  tenantAccessDenied: 'tenant_access_denied',
  unsupportedWarehouseAdapter: 'unsupported_warehouse_adapter',
  unsupportedPlanVersion: 'unsupported_plan_version',
  workspaceFileNotFound: 'workspace_file_not_found',
  workspaceFileRevisionConflict: 'workspace_file_revision_conflict',
  workspaceSourceImportCanvasNotFound: 'workspace_source_import_canvas_not_found',
  workspaceSourceImportProjectionFailed: 'workspace_source_import_projection_failed',
  warehouseSourceDataSampleFailed: 'warehouse_source_data_sample_failed',
  workspaceSourceImportIdempotencyMismatch: 'workspace_source_import_idempotency_mismatch',
  dbtProjectImportRejected: 'dbt_project_import_rejected',
  dbtProjectImportStaleReceipt: 'dbt_project_import_stale_receipt',
  dbtProjectImportCanvasOccupied: 'dbt_project_import_canvas_occupied',
  dbtProjectImportAuthorityConflict: 'dbt_project_import_authority_conflict',
  dbtProjectImportIdempotencyMismatch: 'dbt_project_import_idempotency_mismatch',
  dbtProjectImportInProgress: 'dbt_project_import_in_progress',
  dbtProjectImportProjectionFailed: 'dbt_project_import_projection_failed',
  dbtProjectFileAuthorityRequired: 'dbt_project_file_authority_required',
  dbtDependencyEditIdempotencyConflict: 'dbt_dependency_edit_idempotency_conflict',
  dbtDependencyEditReceiptInvalid: 'dbt_dependency_edit_receipt_invalid',
  graphDbtWorkspaceArtifactPublicationIdempotencyConflict:
    'graph_dbt_workspace_artifact_publication_idempotency_conflict',
  dbtYamlDescriptionDocumentInvalid: 'dbt_yaml_description_document_invalid',
  dbtYamlDescriptionIdempotencyConflict: 'dbt_yaml_description_idempotency_conflict',
  dbtYamlDescriptionProposalMismatch: 'dbt_yaml_description_proposal_mismatch',
  dbtYamlDescriptionReceiptInvalid: 'dbt_yaml_description_receipt_invalid',
  dbtYamlDescriptionResourceAmbiguous: 'dbt_yaml_description_resource_ambiguous',
  dbtYamlDescriptionResourceNotFound: 'dbt_yaml_description_resource_not_found',
  dbtYamlDescriptionResourceUnsupported: 'dbt_yaml_description_resource_unsupported',
  dbtYamlDescriptionRevisionConflict: 'dbt_yaml_description_revision_conflict',
} as const);

export type HttpErrorReason = (typeof HTTP_ERROR_REASON)[keyof typeof HTTP_ERROR_REASON];
