/**
 * Owned concern: stable route-level semantic reason tokens used by the HTTP
 * runtime error translation boundary.
 */
export const HTTP_ERROR_REASON = Object.freeze({
  adapterNotConfigured: 'adapter_not_configured',
  cancelReasonNotSupported: 'cancel_reason_not_supported',
  clientRunIdNotAllowed: 'client_run_id_not_allowed',
  conflictingRunIds: 'conflicting_run_ids',
  conflictingPlanInputs: 'conflicting_plan_inputs',
  internalError: 'internal_error',
  invalidAfterSeq: 'invalid_after_seq',
  invalidBody: 'invalid_body',
  invalidEnrichedFlag: 'invalid_enriched_flag',
  invalidEnvironmentId: 'invalid_environment_id',
  invalidLimit: 'invalid_limit',
  invalidPreviewProfile: 'invalid_preview_profile',
  invalidPlanRef: 'invalid_plan_ref',
  invalidPlanSource: 'invalid_plan_source',
  invalidProjectId: 'invalid_project_id',
  invalidWorkspaceDiffChanges: 'invalid_workspace_diff_changes',
  invalidWorkspacePath: 'invalid_workspace_path',
  invalidRunExecutionContextRef: 'invalid_run_execution_context_ref',
  invalidRunId: 'invalid_run_id',
  invalidSelection: 'invalid_selection',
  invalidSignalType: 'invalid_signal_type',
  invalidTargetAdapter: 'invalid_target_adapter',
  invalidTenantId: 'invalid_tenant_id',
  limitOutOfRange: 'limit_out_of_range',
  missingEnvironmentId: 'missing_environment_id',
  missingProjectId: 'missing_project_id',
  missingTenantId: 'missing_tenant_id',
  missingTenantScope: 'missing_tenant_scope',
  planRejected: 'plan_rejected',
  runAlreadyExists: 'run_already_exists',
  runNotFound: 'run_not_found',
  sourceRunNotTerminal: 'source_run_not_terminal',
  tenantAccessDenied: 'tenant_access_denied',
  unsupportedCursor: 'unsupported_cursor',
  unsupportedPlanVersion: 'unsupported_plan_version',
  workspaceGraphDraftIdempotencyKeyReused: 'workspace_graph_draft_idempotency_key_reused',
  workspaceGraphDraftNotFound: 'workspace_graph_draft_not_found',
  workspaceGraphDraftUnsupportedSchemaVersion: 'workspace_graph_draft_unsupported_schema_version',
  workspaceFileNotFound: 'workspace_file_not_found',
} as const);

export type HttpErrorReason = (typeof HTTP_ERROR_REASON)[keyof typeof HTTP_ERROR_REASON];
