export const LIST_RUNS_LIMIT = {
  DEFAULT: 50,
  MAX: 100,
} as const;

export const LIST_RUNS_PARSE_ERROR_CODE = {
  MISSING_TENANT_SCOPE: 'MISSING_TENANT_SCOPE',
  INVALID_TENANT_ID: 'INVALID_TENANT_ID',
  INVALID_PROJECT_ID: 'INVALID_PROJECT_ID',
  INVALID_ENVIRONMENT_ID: 'INVALID_ENVIRONMENT_ID',
  UNSUPPORTED_CURSOR: 'UNSUPPORTED_CURSOR',
  INVALID_LIMIT: 'INVALID_LIMIT',
  LIMIT_OUT_OF_RANGE: 'LIMIT_OUT_OF_RANGE',
} as const;

export type ListRunsParseErrorCode =
  (typeof LIST_RUNS_PARSE_ERROR_CODE)[keyof typeof LIST_RUNS_PARSE_ERROR_CODE];

export const LIST_RUNS_PARSE_ERROR_RESPONSE = {
  BAD_REQUEST: 'BAD_REQUEST',
  FORBIDDEN: 'FORBIDDEN',
} as const;

export const LIST_RUNS_ACTION = {
  kind: 'query',
  name: 'run:list',
} as const;
