export const RUNTIME_ROUTE_PATH = {
  session: '/session',
  start: '/runs/start',
  plansCompile: '/plans/compile',
  plansPreview: '/plans/preview',
  plansImport: '/plans/import',
  projects: '/projects',
  workspaceContext: '/workspace/context',
  workspacePlugins: '/workspace/plugins',
  workspaceGraphDraft: '/workspace/graph/draft',
  dbtProjectGraph: '/workspace/dbt/graph',
  dbtSelectedModelAnalysis: '/workspace/dbt/analysis/selected-model',
  dbtDependencyEditApplications: '/workspace/dbt/dependency-edits/applications',
  graphDbtWorkspaceArtifactPublications: '/workspace/dbt/graph-artifacts/publications',
  graphDbtModelCompilation: '/workspace/dbt/graph-artifacts/compiled-models',
  dbtYamlDescriptionEditProposals: '/workspace/dbt/description-edits/proposals',
  dbtYamlDescriptionEditApplications: '/workspace/dbt/description-edits/applications',
  dbtYamlDescriptionEditReverts: '/workspace/dbt/description-edits/reverts',
  dbtProjectImportValidate: '/workspace/dbt/import/validate',
  dbtProjectImport: '/workspace/dbt/import',
  workspaceDiffChanges: '/workspace/diff/changes',
  warehouseConnections: '/workspace/warehouse/connections',
  warehouseConnection: '/workspace/warehouse/connections/:connectionId',
  warehouseConnectionSourceObjects: '/workspace/warehouse/connections/:connectionId/objects',
  warehouseConnectionSourceDataSample:
    '/workspace/warehouse/connections/:connectionId/source-data-sample',
  warehouseConnectionTest: '/workspace/warehouse/connections/:connectionId/test',
  warehousePostgresSqlValidation: '/workspace/warehouse/sql-validation',
  warehouseSourcesImport: '/workspace/sources/import',
  warehouseSourceRebind: '/workspace/sources/:nodeId/binding',
  workspaceFiles: '/workspace/files',
  workspaceFileHistory: '/workspace/file-history/:path',
  workspaceFileContent: '/workspace/files/:path',
  costAttributionSummary: '/cost/attribution-summary',
  list: '/runs',
  get: '/runs/:runId',
  events: '/runs/:runId/events',
  signal: '/runs/:runId/signal',
  cancel: '/runs/:runId/cancel',
  recover: '/runs/:runId/recover',
} as const;
