export const ENGINE_ERROR_CODE = {
  RUN_NOT_FOUND: 'RUN_NOT_FOUND',
  RUN_ALREADY_EXISTS: 'RUN_ALREADY_EXISTS',
  ADAPTER_NOT_REGISTERED: 'ADAPTER_NOT_REGISTERED',
  TENANT_ACCESS_DENIED: 'TENANT_ACCESS_DENIED',
  CAPABILITIES_NOT_SUPPORTED: 'CAPABILITIES_NOT_SUPPORTED',
  TARGET_ADAPTER_MISMATCH: 'TARGET_ADAPTER_MISMATCH',
  INVALID_RUN_ID: 'INVALID_RUN_ID',
  PLAN_SCHEMA_VERSION_UNKNOWN: 'PLAN_SCHEMA_VERSION_UNKNOWN',
  RUN_METADATA_NOT_FOUND: 'RUN_METADATA_NOT_FOUND',
  SIGNAL_NOT_IMPLEMENTED: 'SIGNAL_NOT_IMPLEMENTED',
  OUTBOX_RATE_LIMIT_EXCEEDED: 'OUTBOX_RATE_LIMIT_EXCEEDED',
  PLAN_URI_NOT_ALLOWED: 'PLAN_URI_NOT_ALLOWED',
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  UNSUPPORTED_PLAN_VERSION: 'UNSUPPORTED_PLAN_VERSION',
  INVALID_RUN_EVENT_INPUT: 'INVALID_RUN_EVENT_INPUT',
  RUN_SEQUENCE_OVERFLOW: 'RUN_SEQUENCE_OVERFLOW',
  RUN_EXECUTION_CONTEXT_REJECTED: 'RUN_EXECUTION_CONTEXT_REJECTED',
} as const;

export type EngineErrorCode = (typeof ENGINE_ERROR_CODE)[keyof typeof ENGINE_ERROR_CODE];
