/**
 * Owned concern: name protected runtime rail vocabulary once so rail catalogs
 * compose semantic constants instead of ad hoc string literals.
 */

export const PROTECTED_RUNTIME_RAIL_KIND = {
  command: 'command',
  query: 'query',
} as const;

export const PROTECTED_RUNTIME_NEGATIVE_CASE = {
  authenticationFailed: 'authentication failed',
  clientRunId: 'client runId',
  compatibilityDisabled: 'compatibility disabled',
  disabledRoute: 'disabled route',
  invalidGraphSource: 'invalid graph source',
  invalidDbtProjectRoot: 'invalid dbt project root',
  invalidPath: 'invalid path',
  invalidPlanSource: 'invalid plan source',
  invalidPlanRef: 'invalid plan ref',
  invalidRecoverySource: 'invalid recovery source',
  invalidSelection: 'invalid selection',
  idempotencyConflict: 'idempotency conflict',
  missingRunExecutionContextBinding: 'missing run execution context binding',
  missingAction: 'missing action',
  missingFile: 'missing file',
  missingWorkspaceFileReadAuthority: 'missing workspace-file read authority',
  missingIdempotencyKey: 'missing idempotency key',
  missingScope: 'missing scope',
  missingToken: 'missing token',
  nonEmptyReason: 'non-empty reason',
  workspaceProfileWithoutServerOwnedReference:
    'workspace profiles.yml without server-owned profile reference',
  staleAuthority: 'stale authority',
  tenantMismatch: 'tenant mismatch',
  tenantWorkspaceMismatch: 'tenant/workspace mismatch',
  unknownRun: 'unknown run',
  untrustedDbtRunExecutionContextRef: 'untrusted DBT run execution context ref',
  unsupportedAdapter: 'unsupported adapter',
  duplicateConnection: 'duplicate connection',
  invalidCredential: 'invalid credential',
  unsupportedSignal: 'unsupported signal',
  workspaceContextNotGranted: 'workspace context not granted',
} as const;

export const PROTECTED_RUNTIME_TEST_REF = {
  adminRoutes: 'apps/api/test/entrypoints/http/adminRoutes.test.ts',
  adminRebuildSnapshotAccess: 'apps/api/test/contracts/adminRebuildSnapshotAccessContract.test.ts',
  cancelRunParser: 'apps/api/test/entrypoints/http/cancelRunRouteParser.test.ts',
  cancelRunRoute: 'apps/api/test/entrypoints/http/cancelRunRoute.test.ts',
  compilePlanRoute: 'apps/api/test/entrypoints/http/compilePlanRoute.test.ts',
  costAttributionSummaryRoute:
    'apps/api/test/entrypoints/http/getCostAttributionSummaryRoute.test.ts',
  getRunEventsRoute: 'apps/api/test/entrypoints/http/getRunEventsRoute.test.ts',
  getRunRoute: 'apps/api/test/entrypoints/http/getRunRoute.test.ts',
  importPlanRoute: 'apps/api/test/entrypoints/http/importPlanRoute.test.ts',
  listRunsRoute: 'apps/api/test/entrypoints/http/listRunsRoute.test.ts',
  planRequestResolver: 'apps/api/test/entrypoints/http/planRouteRequestResolver.test.ts',
  planRouteSelectionParser: 'apps/api/test/entrypoints/http/planRouteSelectionParser.test.ts',
  previewPlanRouteAuth: 'apps/api/test/entrypoints/http/previewPlanRoute.auth.test.ts',
  previewPlanRouteInputPolicy:
    'apps/api/test/entrypoints/http/previewPlanRoute.inputPolicy.test.ts',
  protectedRuntimeRoutes: 'apps/api/test/entrypoints/http/registerProtectedRuntimeRoutes.test.ts',
  projectOnboardingRoutes: 'apps/api/test/entrypoints/http/projectOnboardingRoutes.test.ts',
  recoverRunParser: 'apps/api/test/entrypoints/http/recoverRunRouteParser.test.ts',
  recoverRunRoute: 'apps/api/test/entrypoints/http/recoverRunRoute.test.ts',
  sessionRoute: 'apps/api/test/entrypoints/http/sessionRoute.test.ts',
  signalRunParser: 'apps/api/test/entrypoints/http/signalRunRouteParser.test.ts',
  signalRunRoute: 'apps/api/test/entrypoints/http/signalRunRoute.test.ts',
  startRunAuthAndSuccess: 'apps/api/test/entrypoints/http/startRunRoute.authAndSuccess.test.ts',
  startRunAuthorizedFacadeAuth:
    'apps/api/test/application/services/startRunAuthorizedFacade.auth.test.ts',
  startRunDbtRunExecutionContextBinding:
    'apps/api/test/application/services/DbtRunExecutionContextBindingUseCase.test.ts',
  startRunDbtBundleSecurity:
    'apps/api/test/application/services/DbtRunExecutionContextBindingUseCase.bundleSecurity.test.ts',
  startRunPlanSourcePolicy: 'apps/api/test/entrypoints/http/startRunRoute.planSourcePolicy.test.ts',
  startRunValidation: 'apps/api/test/entrypoints/http/startRunRoute.validation.test.ts',
  workspaceDraftAuth:
    'apps/api/test/application/services/authorizeWorkspaceGraphDraftCapabilityService.test.ts',
  workspaceDraftRoutes: 'apps/api/test/entrypoints/http/workspaceGraphDraftRoutes.test.ts',
  dbtProjectGraphRoutes: 'apps/api/test/entrypoints/http/dbtProjectGraphRoutes.test.ts',
  dbtProjectAnalyzer: 'apps/api/test/infrastructure/dbt/DbtCliProjectAnalyzer.test.ts',
  workspaceContextRoute: 'apps/api/test/entrypoints/http/workspaceContextRoute.test.ts',
  workspacePluginCatalogRoutes:
    'apps/api/test/entrypoints/http/workspacePluginCatalogRoutes.test.ts',
  workspaceFilesRoutes: 'apps/api/test/entrypoints/http/workspaceFilesRoutes.test.ts',
  workspaceFileHistoryRoutes: 'apps/api/test/entrypoints/http/workspaceFileHistoryRoutes.test.ts',
  workspaceDiffChangesRoutes: 'apps/api/test/entrypoints/http/workspaceDiffChangesRoutes.test.ts',
  warehouseSourceImportRoutes: 'apps/api/test/entrypoints/http/warehouseSourceImportRoutes.test.ts',
} as const;

export const PROTECTED_RUNTIME_PLAN_RAIL = {
  compileExecutablePlan: {
    name: 'CompileExecutablePlan',
    boundedContext: 'Planner boundary',
    dddObject: 'Compiled plan read model',
    applicationPort: 'CompilePlanUseCase',
    adapterSurface: 'POST /plans/compile',
    scopeAndAuthorization: 'run:start authorization, tenant scope',
  },
  getRuntimeSession: {
    name: 'GetRuntimeSession',
    boundedContext: 'Runtime session admission',
    dddObject: 'Authenticated session read model',
    applicationPort: 'IAuthenticator',
    adapterSurface: 'GET /session',
    scopeAndAuthorization: 'authenticated principal bearer token',
  },
  importExecutablePlan: {
    name: 'ImportExecutablePlan',
    boundedContext: 'Runtime plan ingestion',
    dddObject: 'Imported executable plan',
    applicationPort: 'ImportPlanUseCase',
    adapterSurface: 'POST /plans/import',
    scopeAndAuthorization: 'run:start authorization, tenant scope',
  },
  previewExecutionPlan: {
    name: 'PreviewExecutionPlan',
    boundedContext: 'Planner/runtime admission',
    dddObject: 'Executable plan draft',
    applicationPort: 'PreviewPlanUseCase',
    adapterSurface: 'POST /plans/preview',
    scopeAndAuthorization: 'run:start authorization, tenant scope',
  },
  startRun: {
    name: 'StartRun',
    boundedContext: 'Runtime safety and admission',
    dddObject: 'Run command admission',
    applicationPort: 'StartRunAuthorizedFacade',
    adapterSurface: 'POST /runs/start',
    scopeAndAuthorization: 'run:start, tenant scope',
  },
} as const;

export const PROTECTED_RUNTIME_WORKSPACE_RAIL = {
  getEffectiveWorkspaceContext: {
    name: 'GetEffectiveWorkspaceContext',
    boundedContext: 'Protected runtime workspace context',
    dddObject: 'EffectiveWorkspaceContext',
    applicationPort: 'IWorkspaceContextQuery',
    adapterSurface: 'GET /workspace/context',
    scopeAndAuthorization:
      'authenticated principal plus backend grant store and runtime target-adapter registry',
  },
  listProjects: {
    name: 'ListProjects',
    boundedContext: 'Project onboarding',
    dddObject: 'ProjectCatalogReadModel',
    applicationPort: 'ListProjectsUseCase',
    adapterSurface: 'GET /projects',
    scopeAndAuthorization: 'authenticated principal with tenant grant',
  },
  createProject: {
    name: 'CreateProject',
    boundedContext: 'Project onboarding',
    dddObject: 'Project',
    applicationPort: 'CreateProjectUseCase',
    adapterSurface: 'POST /projects',
    scopeAndAuthorization: 'project:create tenant grant plus idempotency key',
  },
  getWorkspaceGraphDraft: {
    name: 'GetWorkspaceGraphDraft',
    boundedContext: 'Workspace graph drafting',
    dddObject: 'Workspace draft read model',
    applicationPort: 'getWorkspaceGraphDraftUseCase',
    adapterSurface: 'GET /workspace/graph/draft',
    scopeAndAuthorization: 'workspace:graph-draft:view, tenant/project/environment scope',
  },
  saveWorkspaceGraphDraft: {
    name: 'SaveWorkspaceGraphDraft',
    boundedContext: 'Workspace graph drafting',
    dddObject: 'Workspace draft aggregate',
    applicationPort: 'saveWorkspaceGraphDraftUseCase',
    adapterSurface: 'PUT /workspace/graph/draft',
    scopeAndAuthorization: 'workspace:graph-draft:save, tenant/project/environment scope',
  },
  projectDbtGraphFromFiles: {
    name: 'ProjectDbtGraphFromFiles',
    boundedContext: 'dbt project analysis and Canvas projection',
    dddObject: 'DbtProjectGraphProjection',
    applicationPort: 'ProjectDbtGraphFromFilesUseCase via IDbtProjectAnalyzerPort',
    adapterSurface: 'GET /workspace/dbt/graph',
    scopeAndAuthorization:
      'workspace:graph-draft:view plus workspace:files:view, tenant/project/environment scope',
  },
  workspaceFiles: {
    listName: 'ListWorkspaceFiles',
    getContentName: 'GetWorkspaceFileContent',
    saveContentName: 'SaveWorkspaceFileContent',
    boundedContext: 'Operational evidence read models',
    treeReadModel: 'WorkspaceFileTree',
    contentReadModel: 'WorkspaceFileContent and WorkspacePath',
    contentAggregate: 'WorkspaceFileContent',
    listPort: 'ListWorkspaceFilesUseCase',
    getContentPort: 'GetWorkspaceFileContentUseCase',
    saveContentPort: 'SaveWorkspaceFileContentUseCase',
    listSurface: 'GET /workspace/files',
    getContentSurface: 'GET /workspace/files/:path',
    saveContentSurface: 'POST /workspace/files/:path',
    scopeAndAuthorization: 'workspace:files:view, tenant/project/environment scope',
    saveScopeAndAuthorization: 'workspace:files:save, tenant/project/environment scope',
  },
  workspaceFileHistory: {
    name: 'GetWorkspaceFileHistory',
    boundedContext: 'Operational evidence read models',
    readModel: 'WorkspaceFileHistory',
    port: 'ListWorkspaceFileHistoryUseCase',
    surface: 'GET /workspace/file-history/:path',
    scopeAndAuthorization: 'workspace:files:view, tenant/project/environment scope',
  },
  workspaceDiffChanges: {
    name: 'GetWorkspaceDiffChanges',
    boundedContext: 'Operational evidence read models',
    readModel: 'WorkspaceDiffChanges',
    port: 'ListWorkspaceDiffChangesUseCase',
    surface: 'GET /workspace/diff/changes',
    scopeAndAuthorization: 'workspace:diff:view, tenant/project/environment scope',
  },
  workspacePluginCatalog: {
    name: 'ListWorkspacePlugins',
    boundedContext: 'Runtime plugin catalog',
    readModel: 'WorkspacePluginCatalog',
    port: 'ListWorkspacePluginsUseCase',
    surface: 'GET /workspace/plugins',
    scopeAndAuthorization: 'workspace:plugins:view, tenant/project/environment scope',
  },
  warehouseSourceImport: {
    listConnectionsName: 'ListWarehouseConnections',
    listSourceObjectsName: 'ListWarehouseConnectionSourceObjects',
    createConnectionName: 'CreateWarehouseConnection',
    testConnectionName: 'TestWarehouseConnection',
    importSourcesName: 'ImportWarehouseSources',
    boundedContext: 'Warehouse source import',
    connectionCatalogReadModel: 'WarehouseConnectionCatalog',
    sourceObjectCatalogReadModel: 'SourceObjectCatalog',
    connectionRegistryAggregate: 'WarehouseConnectionRegistry',
    connectionVerificationService: 'WarehouseConnectionVerification',
    sourceRegistrationAggregate: 'WorkspaceGraphAuthoringDraft via WarehouseSourceRegistration',
    listConnectionsPort: 'ListWarehouseConnectionsUseCase',
    listSourceObjectsPort: 'ListWarehouseConnectionSourceObjectsUseCase',
    createConnectionPort: 'CreateWarehouseConnectionUseCase',
    testConnectionPort: 'TestWarehouseConnectionUseCase',
    importSourcesPort: 'ImportWarehouseSourcesUseCase',
    listConnectionsSurface: 'GET /workspace/warehouse/connections',
    listSourceObjectsSurface: 'GET /workspace/warehouse/connections/:connectionId/objects',
    createConnectionSurface: 'POST /workspace/warehouse/connections',
    testConnectionSurface: 'POST /workspace/warehouse/connections/:connectionId/test',
    importSourcesSurface: 'POST /workspace/sources/import',
    scopeAndAuthorization: 'workspace:source-import:view, tenant/project/environment scope',
    connectionCreateScopeAndAuthorization:
      'workspace:source-connection:create, tenant/project/environment scope',
    connectionTestScopeAndAuthorization:
      'workspace:source-connection:test, tenant/project/environment scope',
    importScopeAndAuthorization: 'workspace:source-import:import, tenant/project/environment scope',
  },
} as const;
