name: Contract Proposal
description: Propose changes to engine contracts, interfaces, or types
title: '[Contract]: '
labels: ['types', 'priority: high']
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ Contract Change Process

        Contract changes are **high-impact** and require careful review. Please ensure:
        1. You've read the GLOSSARY.v1.md and RunEventCatalog.v1.md
        2. You've validated against anchor decisions (see engine-phases.md)
        3. You've considered cross-adapter compatibility (Temporal + Conductor)

  - type: dropdown
    id: contract-type
    attributes:
      label: Contract Type
      description: Which contract are you proposing to change?
      options:
        - IWorkflowEngine (engine interface)
        - ExecutionSemantics (state machine)
        - StateStoreAdapter (storage interface)
        - RunEventCatalog (event taxonomy)
        - TypeScript types (EngineRunRef, ArtifactRef, etc.)
        - Other
    validations:
      required: true

  - type: dropdown
    id: change-type
    attributes:
      label: Change Type
      description: Is this a breaking change?
      options:
        - Breaking (requires version bump, migration)
        - Non-breaking (backward compatible)
        - Clarification (no code change, docs only)
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this contract change needed?
      placeholder: |
        Current contract has limitation:
        - Problem 1: ...
        - Problem 2: ...

        This blocks: [use case]
    validations:
      required: true

  - type: textarea
    id: current-contract
    attributes:
      label: Current Contract
      description: Show the current contract definition
      render: typescript
      placeholder: |
        interface IWorkflowEngine {
          submit(plan: WorkflowPlan): Promise<EngineRunRef>;
          // ...
        }
    validations:
      required: true

  - type: textarea
    id: proposed-contract
    attributes:
      label: Proposed Contract
      description: Show the proposed contract definition
      render: typescript
      placeholder: |
        interface IWorkflowEngine {
          submit(plan: WorkflowPlan, options?: SubmitOptions): Promise<EngineRunRef>;
          // ...
        }
    validations:
      required: true

  - type: textarea
    id: impact-analysis
    attributes:
      label: Impact Analysis
      description: Which components are affected by this change?
      placeholder: |
        **Affected components**:
        - TemporalAdapter: needs update to...
        - PostgresStateStoreAdapter: needs migration...
        - Golden Paths: 2 fixtures need update

        **Migration path**:
        1. Step 1: ...
        2. Step 2: ...
    validations:
      required: true

  - type: checkboxes
    id: anchor-decisions
    attributes:
      label: Anchor Decision Compliance
      description: Have you validated against anchor decisions?
      options:
        - label: 'Complies with Anchor Decision A: Conductor Determinism Parity'
          required: true
        - label: 'Complies with Anchor Decision B: StateStore Indexing & Retention'
          required: true
        - label: 'Complies with Outbox Semantics anchor decision'
          required: true

  - type: checkboxes
    id: cross-adapter
    attributes:
      label: Cross-Adapter Compatibility
      description: Can this contract work with multiple adapters?
      options:
        - label: This contract works with Temporal.io
        - label: This contract works with Conductor (validated or blocked by design)
        - label: This contract requires adapter-specific implementation

  - type: textarea
    id: validation
    attributes:
      label: Validation Plan
      description: How will you validate this contract change?
      placeholder: |
        - [ ] Update golden paths to use new contract
        - [ ] Hash comparison test (replay → same result)
        - [ ] Contract compile gate passes
        - [ ] Integration tests pass (all adapters)
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to related docs, issues, or discussions
      placeholder: |
        - GLOSSARY.v1.md: [link]
        - RunEventCatalog.v1.md: [link]
        - Related issue: #123
        - Temporal docs: [link]
