-- Map the remaining Web root filesystem bucket into Planning DB components.
-- SYS-WEB-ROOT stays composite; old or nonfunctional files are deprecated
-- through explicit DB rows when drift queries prove that state, never by
-- deleting source or hiding ownership.

drop table if exists pg_temp.web_root_component_leaf_map;

create temporary table web_root_component_leaf_map (
  component_id text primary key,
  name text not null,
  parent_id text not null,
  relation_id text,
  local_status text not null,
  children_required boolean not null,
  architecture_kind text not null,
  architecture_layer text not null,
  architecture_owner text not null,
  repo_path text not null,
  public_contract text not null,
  runtime text not null,
  criticality text not null,
  architecture_status text not null,
  ddd_owner text not null,
  cq_rails text not null,
  owned_concern text not null,
  responsibility text not null,
  reason_to_change text not null,
  fowler_signal text not null,
  public_api text[] not null,
  owns text[] not null,
  test_id text not null,
  test_path text not null,
  test_kind text not null,
  coverage_level text not null,
  validation_command text not null
);

insert into web_root_component_leaf_map (
  component_id,
  name,
  parent_id,
  relation_id,
  local_status,
  children_required,
  architecture_kind,
  architecture_layer,
  architecture_owner,
  repo_path,
  public_contract,
  runtime,
  criticality,
  architecture_status,
  ddd_owner,
  cq_rails,
  owned_concern,
  responsibility,
  reason_to_change,
  fowler_signal,
  public_api,
  owns,
  test_id,
  test_path,
  test_kind,
  coverage_level,
  validation_command
)
values
  (
    'SYS-WEB-ROOT',
    'Web application root',
    'SYS-WEB',
    null,
    'review',
    true,
    'package',
    'ui',
    'Frontend / Web',
    'apps/web/src',
    '@dvt/web source root and browser application composition boundary',
    'browser',
    'medium',
    'implemented',
    'WebApplicationRoot',
    'ReadComponentProfile;ValidateComponentFilesystemCoverage',
    'Composite web application root. Concrete files are owned by child components.',
    'Route web package, source, app, Canvas, service, plugin, and support files to child components.',
    'Web root component taxonomy, filesystem ownership, or package-wide governance changes.',
    'responsibility_overload',
    array['@dvt/web']::text[],
    array[]::text[],
    'TEST-WEB-ROOT',
    'apps/web/src/app/Root.test.tsx',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:presentation:run -- src/app/Root.test.tsx'
  ),
  (
    'SYS-WEB-PACKAGE-CONFIG',
    'Web package configuration',
    'SYS-WEB-ROOT',
    'REL-WEB-ROOT-CONTAINS-PACKAGE-CONFIG',
    'review',
    false,
    'package',
    'infra',
    'Frontend / Web',
    'apps/web/package.json',
    '@dvt/web package, Vite, Vitest, Cypress, and documentation entrypoint configuration',
    'node',
    'medium',
    'review',
    'WebPackageConfiguration',
    'RunWebVitestSuites;RunWebCypressSuites;BuildWebApplication',
    'Owns web package-level configuration and local documentation files.',
    'Define package scripts, test suite routing, build entry configuration, and package-level docs.',
    'Web package scripts, Vite/Vitest config, Cypress config, or package docs change.',
    'hidden_authority',
    array['package.json', 'vite.config.ts', 'vitest.suites.ts']::text[],
    array[
      'apps/web/.env.e2e',
      'apps/web/ATTRIBUTIONS.md',
      'apps/web/cypress.config.ts',
      'apps/web/guidelines/**',
      'apps/web/index.html',
      'apps/web/package.json',
      'apps/web/postcss.config.mjs',
      'apps/web/README.md',
      'apps/web/tsconfig.json',
      'apps/web/turbo.json',
      'apps/web/vite%',
      'apps/web/vitest%'
    ]::text[],
    'TEST-WEB-PACKAGE-CONFIG',
    'apps/web/src/testing/vitestSuites.architecture.test.ts',
    'architecture',
    'boundary',
    'pnpm --filter @dvt/web test:architecture:run -- src/testing/vitestSuites.architecture.test.ts'
  ),
  (
    'SYS-WEB-CYPRESS-E2E',
    'Web Cypress end-to-end workflows',
    'SYS-WEB-ROOT',
    'REL-WEB-ROOT-CONTAINS-CYPRESS-E2E',
    'review',
    false,
    'module',
    'ui',
    'Frontend / Web QA',
    'apps/web/cypress/e2e',
    'Browser end-to-end workflows for web shell, Canvas, runs, templates, and artifacts',
    'browser',
    'medium',
    'review',
    'WebE2EWorkflowSuite',
    'RunWebCypressSuites;ValidateWebShellWorkflow',
    'Owns Cypress user workflows for the web application.',
    'Validate browser-level shell, Canvas, runs, templates, and artifact workflows.',
    'Cypress workflow, user journey, or e2e harness behavior changes.',
    'hidden_authority',
    array['cypress/e2e']::text[],
    array['apps/web/cypress/e2e/**']::text[],
    'TEST-WEB-CYPRESS-E2E',
    'apps/web/cypress/e2e/shell/startup-route-readiness.cy.ts',
    'e2e',
    'flow',
    'pnpm --filter @dvt/web cypress:run -- --spec cypress/e2e/shell/startup-route-readiness.cy.ts'
  ),
  (
    'SYS-WEB-CYPRESS-SUPPORT',
    'Web Cypress support adapters',
    'SYS-WEB-ROOT',
    'REL-WEB-ROOT-CONTAINS-CYPRESS-SUPPORT',
    'review',
    false,
    'adapter',
    'ui',
    'Frontend / Web QA',
    'apps/web/cypress/support',
    'Cypress support commands, API stubs, and live runtime adapters',
    'browser',
    'medium',
    'review',
    'WebCypressSupportAdapters',
    'RunWebCypressSuites;SeedWorkspaceSession',
    'Owns Cypress support adapters used by browser workflows.',
    'Provide Cypress API stubs, session helpers, and Canvas workflow support.',
    'Cypress support adapter or e2e test harness changes.',
    'hidden_authority',
    array['cypress/support']::text[],
    array['apps/web/cypress/support/**']::text[],
    'TEST-WEB-CYPRESS-SUPPORT',
    'apps/web/cypress/support/e2e.ts',
    'e2e',
    'smoke',
    'pnpm --filter @dvt/web cypress:run -- --spec cypress/e2e/shell/startup-route-readiness.cy.ts'
  ),
  (
    'SYS-WEB-FAVICON-ASSETS',
    'Web favicon and install assets',
    'SYS-WEB-ROOT',
    'REL-WEB-ROOT-CONTAINS-FAVICON-ASSETS',
    'review',
    false,
    'module',
    'ui',
    'Frontend / Web',
    'apps/web/favicon',
    'Browser favicon, manifest, and installable web app assets',
    'browser',
    'low',
    'review',
    'WebStaticAssetSet',
    'BuildWebApplication',
    'Owns static favicon and web app manifest assets.',
    'Keep browser install assets, favicons, and manifest files owned by a static asset component.',
    'Favicon, manifest, or install asset change.',
    'hidden_authority',
    array['site.webmanifest']::text[],
    array['apps/web/favicon/**']::text[],
    'TEST-WEB-FAVICON-ASSETS',
    'apps/web/favicon/site.webmanifest',
    'architecture',
    'smoke',
    'pnpm verify:prepush'
  ),
  (
    'SYS-WEB-SCRIPTS',
    'Web package helper scripts',
    'SYS-WEB-ROOT',
    'REL-WEB-ROOT-CONTAINS-SCRIPTS',
    'review',
    false,
    'module',
    'infra',
    'Frontend / Web',
    'apps/web/scripts',
    'Web package-local script helpers for Cypress and changed Vitest suite routing',
    'node',
    'medium',
    'review',
    'WebPackageScriptHelpers',
    'RunWebCypressSuites;RunChangedWebVitestSuites',
    'Owns package-local test runner helper scripts.',
    'Execute package-local Cypress and changed Vitest suite routing helpers.',
    'Web helper script or local suite routing changes.',
    'hidden_authority',
    array['run-cypress-docker.mjs', 'run-vitest-changed-suites.ts']::text[],
    array['apps/web/scripts/**']::text[],
    'TEST-WEB-SCRIPTS',
    'apps/web/scripts/run-vitest-changed-suites.ts',
    'architecture',
    'smoke',
    'pnpm verify:prepush'
  ),
  (
    'SYS-WEB-SRC-ENTRYPOINTS',
    'Web browser entrypoints',
    'SYS-WEB-ROOT',
    'REL-WEB-ROOT-CONTAINS-SRC-ENTRYPOINTS',
    'review',
    false,
    'module',
    'ui',
    'Frontend / Web',
    'apps/web/src/main.tsx',
    'Browser React entrypoint for @dvt/web',
    'browser',
    'medium',
    'review',
    'WebBrowserEntrypoint',
    'BootstrapWebApplication',
    'Owns the browser entrypoint that mounts the web app.',
    'Mount React providers and route shell into the browser DOM.',
    'Web entrypoint, browser mount, or application bootstrapping change.',
    'hidden_authority',
    array['main.tsx']::text[],
    array['apps/web/src/main.tsx']::text[],
    'TEST-WEB-SRC-ENTRYPOINTS',
    'apps/web/src/app/Root.test.tsx',
    'unit',
    'smoke',
    'pnpm --filter @dvt/web test:presentation:run -- src/app/Root.test.tsx'
  ),
  (
    'SYS-WEB-SRC-STYLES',
    'Web global styles',
    'SYS-WEB-ROOT',
    'REL-WEB-ROOT-CONTAINS-SRC-STYLES',
    'review',
    false,
    'module',
    'ui',
    'Frontend / Web',
    'apps/web/src/styles',
    'Global fonts, Tailwind, theme, and app stylesheet entrypoints',
    'browser',
    'low',
    'review',
    'WebGlobalStyleSet',
    'BuildWebApplication',
    'Owns global CSS and theme entrypoints for the web app.',
    'Provide global fonts, Tailwind base, theme variables, and app stylesheet imports.',
    'Global style, theme token, or CSS entrypoint changes.',
    'hidden_authority',
    array['fonts.css', 'theme.css']::text[],
    array['apps/web/src/styles/**']::text[],
    'TEST-WEB-SRC-STYLES',
    'apps/web/src/app/views/publicDataVisualSystem.architecture.test.ts',
    'architecture',
    'boundary',
    'pnpm --filter @dvt/web test:architecture:run -- src/app/views/publicDataVisualSystem.architecture.test.ts'
  ),
  (
    'SYS-WEB-SRC-TESTING',
    'Web shared testing support',
    'SYS-WEB-ROOT',
    'REL-WEB-ROOT-CONTAINS-SRC-TESTING',
    'review',
    false,
    'module',
    'ui',
    'Frontend / Web QA',
    'apps/web/src/testing',
    'Shared test doubles, fixtures, and React Query harnesses for @dvt/web',
    'node',
    'medium',
    'review',
    'WebTestingSupport',
    'RunWebVitestSuites;ValidateWebTestHarnesses',
    'Owns shared test doubles and test harnesses for web unit and presentation tests.',
    'Provide reusable test doubles, React Query harnesses, and suite routing architecture tests.',
    'Shared web test harness, fixture, or suite architecture changes.',
    'hidden_authority',
    array['reactQueryHarness', 'workspaceGraphDraftAuthoringPortDoubles']::text[],
    array['apps/web/src/testing/**', 'apps/web/src/app/testing/**']::text[],
    'TEST-WEB-SRC-TESTING',
    'apps/web/src/testing/reactQueryHarness.test.tsx',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:unit:run -- src/testing/reactQueryHarness.test.tsx src/testing/workspaceGraphDraftAuthoringPortDoubles.test.ts'
  ),
  (
    'SYS-WEB-CAPABILITIES-PLATFORM-HEALTH',
    'Web platform health capability',
    'SYS-WEB-ROOT',
    'REL-WEB-ROOT-CONTAINS-CAPABILITIES-PLATFORM-HEALTH',
    'review',
    false,
    'service',
    'application',
    'Frontend / Web',
    'apps/web/src/capabilities/platform-health',
    'Platform health read model, HTTP adapter, selectors, and presentation query hooks',
    'browser',
    'medium',
    'review',
    'PlatformHealthCapability',
    'ReadPlatformHealthSnapshot',
    'Owns the web platform-health capability across application, domain, infrastructure, presentation, contracts, and tests.',
    'Read platform-health status and expose it to the web shell through a typed capability boundary.',
    'Platform health DTO, HTTP client, selector, presentation hook, or fixture changes.',
    'hidden_authority',
    array['ReadPlatformHealthSnapshot']::text[],
    array['apps/web/src/capabilities/platform-health/**']::text[],
    'TEST-WEB-CAPABILITIES-PLATFORM-HEALTH',
    'apps/web/src/capabilities/platform-health/application/platformHealthCapability.test.ts',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:unit:run -- src/capabilities/platform-health/application/platformHealthCapability.test.ts src/capabilities/platform-health/infrastructure/httpPlatformHealthClient.test.ts src/capabilities/platform-health/presentation/usePlatformHealthSnapshotQuery.test.ts'
  ),
  (
    'SYS-WEB-CAPABILITIES-RUNTIME-CAPABILITIES',
    'Web runtime capabilities capability',
    'SYS-WEB-ROOT',
    'REL-WEB-ROOT-CONTAINS-CAPABILITIES-RUNTIME-CAPABILITIES',
    'review',
    false,
    'service',
    'application',
    'Frontend / Web',
    'apps/web/src/capabilities/runtime-capabilities',
    'Runtime capabilities read model, HTTP adapter, contracts, and presentation query hooks',
    'browser',
    'medium',
    'review',
    'RuntimeCapabilitiesCapability',
    'ReadRuntimeCapabilities',
    'Owns the web runtime-capabilities capability across application, infrastructure, contracts, and presentation.',
    'Read runtime capability flags and expose them to web presentation code.',
    'Runtime capability DTO, HTTP client, or presentation hook changes.',
    'hidden_authority',
    array['ReadRuntimeCapabilities']::text[],
    array['apps/web/src/capabilities/runtime-capabilities/**']::text[],
    'TEST-WEB-CAPABILITIES-RUNTIME-CAPABILITIES',
    'apps/web/src/capabilities/runtime-capabilities/application/runtimeCapabilitiesCapability.test.ts',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:unit:run -- src/capabilities/runtime-capabilities/application/runtimeCapabilitiesCapability.test.ts src/capabilities/runtime-capabilities/infrastructure/httpRuntimeCapabilitiesClient.test.ts src/capabilities/runtime-capabilities/presentation/useRuntimeCapabilitiesQuery.test.ts'
  ),
  (
    'SYS-WEB-APP-ROOT-SHELL',
    'Web app root shell',
    'SYS-WEB-ROOT',
    'REL-WEB-ROOT-CONTAINS-APP-ROOT-SHELL',
    'review',
    false,
    'ui-view',
    'ui',
    'Frontend / Web',
    'apps/web/src/app/Root.tsx',
    'Root App, providers, route error boundaries, and shell chrome bootstrap tests',
    'browser',
    'medium',
    'review',
    'WebAppRootShell',
    'RenderWebRootShell;ResolveAppRouteErrorBoundary',
    'Owns top-level app shell files under apps/web/src/app.',
    'Compose providers, root shell, route error boundaries, and top-level app tests.',
    'Root shell, provider, route error boundary, or app chrome bootstrap changes.',
    'responsibility_overload',
    array['Root', 'AppProviders', 'AppRouteErrorBoundary']::text[],
    array['apps/web/src/app/App%', 'apps/web/src/app/Root%', 'apps/web/src/app/appRoute%']::text[],
    'TEST-WEB-APP-ROOT-SHELL',
    'apps/web/src/app/Root.test.tsx',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:presentation:run -- src/app/Root.test.tsx src/app/AppProviders.test.tsx src/app/Root.shellChrome.test.tsx'
  ),
  (
    'SYS-WEB-APP-ROUTES',
    'Web app route registry',
    'SYS-WEB-ROOT',
    'REL-WEB-ROOT-CONTAINS-APP-ROUTES',
    'review',
    false,
    'module',
    'ui',
    'Frontend / Web',
    'apps/web/src/app/routes.ts',
    'Web route registry, route support, and route-level tests',
    'browser',
    'medium',
    'review',
    'WebRouteRegistry',
    'ResolveWebRoute;RenderRouteWorkbench',
    'Owns route registry and route-level support files.',
    'Resolve route definitions and route-level workbench support for web navigation.',
    'Route catalog, route support, or route navigation test changes.',
    'hidden_authority',
    array['routes']::text[],
    array['apps/web/src/app/routes/**', 'apps/web/src/app/routes.ts', 'apps/web/src/app/routes.test.tsx']::text[],
    'TEST-WEB-APP-ROUTES',
    'apps/web/src/app/routes.test.tsx',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:presentation:run -- src/app/routes.test.tsx'
  ),
  (
    'SYS-WEB-APP-BOOTSTRAP',
    'Web app route bootstrap',
    'SYS-WEB-ROOT',
    'REL-WEB-ROOT-CONTAINS-APP-BOOTSTRAP',
    'review',
    false,
    'module',
    'ui',
    'Frontend / Web',
    'apps/web/src/app/bootstrap',
    'Route bootstrap commands, readiness, registry, and auth route gates',
    'browser',
    'medium',
    'review',
    'WebRouteBootstrap',
    'BootstrapWebApplication;PublishRouteBootstrapReadiness',
    'Owns the route bootstrap model, auth gate, readiness checks, and bootstrap presentation.',
    'Coordinate route bootstrap registration, startup readiness, auth gating, and bootstrap screen presentation.',
    'Route bootstrap command, readiness, registry, or auth gate changes.',
    'hidden_authority',
    array['routeBootstrapRegistry', 'AuthRouteGate']::text[],
    array['apps/web/src/app/bootstrap/**']::text[],
    'TEST-WEB-APP-BOOTSTRAP',
    'apps/web/src/app/bootstrap/routeBootstrapRegistry.test.ts',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:unit:run -- src/app/bootstrap/routeBootstrapRegistry.test.ts src/app/bootstrap/routeBootstrapStartupReadiness.test.ts'
  ),
  (
    'SYS-WEB-APP-QUERIES',
    'Web app query hooks',
    'SYS-WEB-ROOT',
    'REL-WEB-ROOT-CONTAINS-APP-QUERIES',
    'review',
    false,
    'module',
    'application',
    'Frontend / Web',
    'apps/web/src/app/queries',
    'React Query hooks and read-model loaders for the web app',
    'browser',
    'medium',
    'review',
    'WebReadModelQueries',
    'ReadWorkspaceGraphDraft;ReadRunTimeline;ReadArtifactFiles',
    'Owns application query hooks and read-model loaders under the web app.',
    'Load web read models through query hooks without owning write semantics.',
    'Query hook, freshness, read-model loading, or cache policy changes.',
    'hidden_authority',
    array['React Query hooks']::text[],
    array['apps/web/src/app/queries/**']::text[],
    'TEST-WEB-APP-QUERIES',
    'apps/web/src/app/queries/workspaceGraphDraftQuery.test.ts',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:unit:run -- src/app/queries/workspaceGraphDraftQuery.test.ts'
  ),
  (
    'SYS-WEB-APP-PORTS',
    'Web app application ports',
    'SYS-WEB-ROOT',
    'REL-WEB-ROOT-CONTAINS-APP-PORTS',
    'review',
    false,
    'port',
    'application',
    'Frontend / Web',
    'apps/web/src/app/ports',
    'Application port contracts consumed by web services and route views',
    'browser',
    'medium',
    'review',
    'WebApplicationPorts',
    'ReadWorkspaceGraphDraft;SubmitWorkspaceGraphDraft;ReadRunTimeline',
    'Owns web application port definitions and port-level tests.',
    'Define web application ports without binding them to HTTP or mock adapters.',
    'Port contract, adapter boundary, or port test changes.',
    'hexagonal_boundary',
    array['WorkspacePort', 'RunsPort']::text[],
    array['apps/web/src/app/ports/**']::text[],
    'TEST-WEB-APP-PORTS',
    'apps/web/src/app/ports/workspaceGraphDraftAuthoringPort.test.ts',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:unit:run -- src/app/ports/workspaceGraphDraftAuthoringPort.test.ts'
  ),
  (
    'SYS-WEB-APP-STORES',
    'Web app client stores',
    'SYS-WEB-ROOT',
    'REL-WEB-ROOT-CONTAINS-APP-STORES',
    'review',
    false,
    'module',
    'application',
    'Frontend / Web',
    'apps/web/src/app/stores',
    'Client-side stores and store tests for web route state',
    'browser',
    'medium',
    'review',
    'WebClientStores',
    'PersistWebRoutePreference;ReadWebRoutePreference',
    'Owns client store modules and store-level tests.',
    'Manage scoped client state used by shell and route views.',
    'Client store model or persistence boundary changes.',
    'hidden_authority',
    array['web stores']::text[],
    array['apps/web/src/app/stores/**']::text[],
    'TEST-WEB-APP-STORES',
    'apps/web/src/app/stores/workbenchStore.test.ts',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:unit:run -- src/app/stores/workbenchStore.test.ts'
  ),
  (
    'SYS-WEB-APP-SHELL',
    'Web app shell support',
    'SYS-WEB-ROOT',
    'REL-WEB-ROOT-CONTAINS-APP-SHELL',
    'review',
    false,
    'ui-view',
    'ui',
    'Frontend / Web',
    'apps/web/src/app/shell',
    'Route shell support modules and shell tests',
    'browser',
    'medium',
    'review',
    'WebShellSupport',
    'RenderWebShell;ResolveShellNavigation',
    'Owns app shell support modules outside shared component shell widgets.',
    'Provide route shell state, shell navigation, and shell-level support utilities.',
    'Shell support module or route shell test changes.',
    'hidden_authority',
    array['shell support']::text[],
    array['apps/web/src/app/shell/**']::text[],
    'TEST-WEB-APP-SHELL',
    'apps/web/src/app/shell/shellNavigationModel.test.ts',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:unit:run -- src/app/shell/shellNavigationModel.test.ts'
  ),
  (
    'SYS-WEB-APP-TYPES',
    'Web app shared types',
    'SYS-WEB-ROOT',
    'REL-WEB-ROOT-CONTAINS-APP-TYPES',
    'review',
    false,
    'module',
    'contracts',
    'Frontend / Web',
    'apps/web/src/app/types',
    'Shared type definitions consumed by web views, services, and plugins',
    'browser',
    'low',
    'review',
    'WebSharedTypes',
    'CompileWebTypeContracts',
    'Owns app-local shared TypeScript type definitions.',
    'Define shared app-local types without owning a runtime adapter.',
    'Shared web type contract changes.',
    'hidden_authority',
    array['shared web types']::text[],
    array['apps/web/src/app/types/**']::text[],
    'TEST-WEB-APP-TYPES',
    'apps/web/src/app/views/publicDataVisualSystem.architecture.test.ts',
    'architecture',
    'boundary',
    'pnpm --filter @dvt/web test:architecture:run -- src/app/views/publicDataVisualSystem.architecture.test.ts'
  ),
  (
    'SYS-WEB-APP-SERVICES',
    'Web app services composite',
    'SYS-WEB-ROOT',
    'REL-WEB-ROOT-CONTAINS-APP-SERVICES',
    'review',
    true,
    'service',
    'application',
    'Frontend / Web',
    'apps/web/src/app/services',
    'Composite web services area; concrete services are owned by child leaves',
    'browser',
    'medium',
    'review',
    'WebApplicationServices',
    'ComposeWebApplicationServices;ReadWorkspaceGraphDraft;ReadRunTimeline',
    'Composite services component. Concrete service files are owned by service leaves.',
    'Route API, workspace, runs, config, session, plans, and service composition modules to service leaves.',
    'Web service taxonomy or service composition boundary changes.',
    'responsibility_overload',
    array['appServices']::text[],
    array[]::text[],
    'TEST-WEB-APP-SERVICES',
    'apps/web/src/app/services/composition/appServices.test.ts',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:unit:run -- src/app/services/composition/appServices.test.ts'
  ),
  (
    'SYS-WEB-SERVICES-CONTEXT',
    'Web services provider context',
    'SYS-WEB-APP-SERVICES',
    'REL-WEB-APP-SERVICES-CONTAINS-CONTEXT',
    'review',
    false,
    'service',
    'application',
    'Frontend / Web',
    'apps/web/src/app/services/AppServicesContext.tsx',
    'React provider context for composed web services',
    'browser',
    'medium',
    'review',
    'WebServicesProviderContext',
    'ComposeWebApplicationServices',
    'Owns the React context boundary for app services.',
    'Provide composed service instances to web presentation components.',
    'App service context or provider contract changes.',
    'hexagonal_boundary',
    array['AppServicesContext']::text[],
    array['apps/web/src/app/services/AppServicesContext%']::text[],
    'TEST-WEB-SERVICES-CONTEXT',
    'apps/web/src/app/services/AppServicesContext.test.tsx',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:presentation:run -- src/app/services/AppServicesContext.test.tsx'
  ),
  (
    'SYS-WEB-SERVICES-WORKSPACE',
    'Web workspace services',
    'SYS-WEB-APP-SERVICES',
    'REL-WEB-APP-SERVICES-CONTAINS-WORKSPACE',
    'review',
    false,
    'service',
    'adapter',
    'Frontend / Workspace',
    'apps/web/src/app/services/workspace',
    'Workspace HTTP clients, projections, ports API adapters, fixtures, and tests',
    'browser',
    'high',
    'review',
    'WorkspaceServiceAdapters',
    'ReadWorkspaceGraphDraft;SubmitWorkspaceGraphDraft;ReadWorkspaceFiles;ReadWorkspaceDiff',
    'Owns workspace service adapters, projections, and tests.',
    'Translate workspace HTTP API responses into web application port read models.',
    'Workspace adapter, projection, API payload, fixture, or port behavior changes.',
    'hexagonal_boundary',
    array['workspacePorts', 'workspaceGraphDraftProjection']::text[],
    array['apps/web/src/app/services/workspace/**']::text[],
    'TEST-WEB-SERVICES-WORKSPACE',
    'apps/web/src/app/services/workspace/workspacePorts.api.test.ts',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:unit:run -- src/app/services/workspace/workspacePorts.api.test.ts src/app/services/workspace/workspaceGraphDraftProjection.test.ts'
  ),
  (
    'SYS-WEB-SERVICES-RUNS',
    'Web runs services',
    'SYS-WEB-APP-SERVICES',
    'REL-WEB-APP-SERVICES-CONTAINS-RUNS',
    'review',
    false,
    'service',
    'adapter',
    'Frontend / Runs',
    'apps/web/src/app/services/runs',
    'Runs API decoders, service adapters, timeline presentation models, and tests',
    'browser',
    'high',
    'review',
    'RunsServiceAdapters',
    'StartRun;SignalRun;RecoverRun;GetRunEvents;ListRuns',
    'Owns runs service adapters, DTO mapping, and run timeline presentation models.',
    'Load and present run status, events, payloads, and workspace facade data.',
    'Runs service, event model, payload mapper, or timeline presentation changes.',
    'hexagonal_boundary',
    array['runsService', 'runEventTimelineModel']::text[],
    array['apps/web/src/app/services/runs/**']::text[],
    'TEST-WEB-SERVICES-RUNS',
    'apps/web/src/app/services/runs/runsService.test.ts',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:unit:run -- src/app/services/runs/runsService.test.ts src/app/services/runs/runEventTimelineModel.test.ts'
  ),
  (
    'SYS-WEB-SERVICES-API',
    'Web API client services',
    'SYS-WEB-APP-SERVICES',
    'REL-WEB-APP-SERVICES-CONTAINS-API',
    'review',
    false,
    'adapter',
    'adapter',
    'Frontend / Web',
    'apps/web/src/app/services/api',
    'Base API client, auth configuration, HTTP error classification, and protected runtime rejections',
    'browser',
    'medium',
    'review',
    'WebApiClientAdapter',
    'CallWebApi;ClassifyHttpError',
    'Owns base API client and HTTP error classification shared by web services.',
    'Provide authenticated HTTP client behavior and normalized error classification.',
    'API client, auth header, HTTP error, or protected runtime rejection changes.',
    'hexagonal_boundary',
    array['createApiClient', 'classifyHttpError']::text[],
    array['apps/web/src/app/services/api/**']::text[],
    'TEST-WEB-SERVICES-API',
    'apps/web/src/app/services/api/createApiClient.test.ts',
    'unit',
    'negative',
    'pnpm --filter @dvt/web test:unit:run -- src/app/services/api/createApiClient.test.ts src/app/services/api/classifyHttpError.test.ts'
  ),
  (
    'SYS-WEB-SERVICES-SESSION',
    'Web session services',
    'SYS-WEB-APP-SERVICES',
    'REL-WEB-APP-SERVICES-CONTAINS-SESSION',
    'review',
    false,
    'service',
    'application',
    'Frontend / Web',
    'apps/web/src/app/services/session',
    'Protected route session context and workspace scope selection port',
    'browser',
    'medium',
    'review',
    'WebSessionScope',
    'ReadSessionContext;SelectWorkspaceScope',
    'Owns session context and workspace scope selection ports for protected routes.',
    'Provide protected route session state and workspace scope selection behavior.',
    'Session context, protected route, or workspace scope selection changes.',
    'hexagonal_boundary',
    array['protectedRouteSessionContext', 'workspaceScopeSelectionPort']::text[],
    array['apps/web/src/app/services/session/**']::text[],
    'TEST-WEB-SERVICES-SESSION',
    'apps/web/src/app/services/session/protectedRouteSessionContext.test.ts',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:unit:run -- src/app/services/session/protectedRouteSessionContext.test.ts src/app/services/session/workspaceScopeSelectionPort.test.ts'
  ),
  (
    'SYS-WEB-SERVICES-COMPOSITION',
    'Web services composition',
    'SYS-WEB-APP-SERVICES',
    'REL-WEB-APP-SERVICES-CONTAINS-COMPOSITION',
    'review',
    false,
    'service',
    'application',
    'Frontend / Web',
    'apps/web/src/app/services/composition',
    'App services assembly and authority hard-cut architecture guards',
    'browser',
    'medium',
    'review',
    'WebServicesComposition',
    'ComposeWebApplicationServices',
    'Owns app service composition and mock/authority architecture guards.',
    'Assemble web service adapters and prevent mock semantics from becoming product authority.',
    'App service composition, mock hard-cut, or authority boundary changes.',
    'hexagonal_boundary',
    array['appServices']::text[],
    array['apps/web/src/app/services/composition/**']::text[],
    'TEST-WEB-SERVICES-COMPOSITION',
    'apps/web/src/app/services/composition/appServices.test.ts',
    'architecture',
    'boundary',
    'pnpm --filter @dvt/web test:unit:run -- src/app/services/composition/appServices.test.ts'
  ),
  (
    'SYS-WEB-SERVICES-CONFIG',
    'Web runtime configuration services',
    'SYS-WEB-APP-SERVICES',
    'REL-WEB-APP-SERVICES-CONTAINS-CONFIG',
    'review',
    false,
    'service',
    'application',
    'Frontend / Web',
    'apps/web/src/app/services/config',
    'Runtime data source mode and workspace config helpers',
    'browser',
    'medium',
    'review',
    'WebRuntimeConfiguration',
    'ReadRuntimeDataSourceMode;ReadWorkspaceConfig',
    'Owns runtime data source and workspace configuration services.',
    'Resolve data-source mode and workspace config without leaking test-only behavior.',
    'Runtime data source, workspace config, or config test changes.',
    'hidden_authority',
    array['dataSource', 'workspaceConfig']::text[],
    array['apps/web/src/app/services/config/**']::text[],
    'TEST-WEB-SERVICES-CONFIG',
    'apps/web/src/app/services/config/dataSource.test.ts',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:unit:run -- src/app/services/config/dataSource.test.ts'
  ),
  (
    'SYS-WEB-SERVICES-COST',
    'Web cost services',
    'SYS-WEB-APP-SERVICES',
    'REL-WEB-APP-SERVICES-CONTAINS-COST',
    'review',
    false,
    'service',
    'adapter',
    'Frontend / Cost',
    'apps/web/src/app/services/cost',
    'Cost API decoders and service adapter',
    'browser',
    'medium',
    'review',
    'CostServiceAdapter',
    'ReadCostDashboard',
    'Owns cost API decoding and service adapter behavior.',
    'Load cost read models from API responses and expose them to cost views.',
    'Cost decoder or service adapter changes.',
    'hexagonal_boundary',
    array['costService']::text[],
    array['apps/web/src/app/services/cost/**']::text[],
    'TEST-WEB-SERVICES-COST',
    'apps/web/src/app/services/cost/costService.api.test.ts',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:unit:run -- src/app/services/cost/costService.api.test.ts'
  ),
  (
    'SYS-WEB-SERVICES-PLANS',
    'Web plans services',
    'SYS-WEB-APP-SERVICES',
    'REL-WEB-APP-SERVICES-CONTAINS-PLANS',
    'review',
    false,
    'service',
    'adapter',
    'Frontend / Planner',
    'apps/web/src/app/services/plans',
    'Plans service API adapter and tests',
    'browser',
    'medium',
    'review',
    'PlansServiceAdapter',
    'ReadPlans;InspectPlanArtifacts',
    'Owns plans service adapter behavior for web views.',
    'Load plan read models and expose them to plan-related web surfaces.',
    'Plans service adapter, API mapper, or plan read model changes.',
    'hexagonal_boundary',
    array['plansService']::text[],
    array['apps/web/src/app/services/plans/**']::text[],
    'TEST-WEB-SERVICES-PLANS',
    'apps/web/src/app/services/plans/plansService.test.ts',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:unit:run -- src/app/services/plans/plansService.test.ts'
  ),
  (
    'SYS-WEB-SERVICES-PROJECT-ONBOARDING',
    'Web project onboarding services',
    'SYS-WEB-APP-SERVICES',
    'REL-WEB-APP-SERVICES-CONTAINS-PROJECT-ONBOARDING',
    'review',
    false,
    'service',
    'application',
    'Frontend / Web',
    'apps/web/src/app/services/projectOnboarding',
    'Project onboarding service and tests',
    'browser',
    'medium',
    'review',
    'ProjectOnboardingService',
    'CompleteProjectOnboarding;ReadProjectOnboardingState',
    'Owns project onboarding service behavior.',
    'Provide project onboarding read/write behavior to onboarding views.',
    'Project onboarding service or onboarding flow changes.',
    'hidden_authority',
    array['projectOnboardingService']::text[],
    array['apps/web/src/app/services/projectOnboarding/**']::text[],
    'TEST-WEB-SERVICES-PROJECT-ONBOARDING',
    'apps/web/src/app/services/projectOnboarding/projectOnboardingService.test.ts',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:unit:run -- src/app/services/projectOnboarding/projectOnboardingService.test.ts'
  ),
  (
    'SYS-WEB-SERVICES-CAPABILITIES',
    'Web capabilities service port',
    'SYS-WEB-APP-SERVICES',
    'REL-WEB-APP-SERVICES-CONTAINS-CAPABILITIES',
    'review',
    false,
    'port',
    'application',
    'Frontend / Web',
    'apps/web/src/app/services/capabilities',
    'Capabilities service port consumed by app services',
    'browser',
    'medium',
    'review',
    'CapabilitiesServicePort',
    'ReadRuntimeCapabilities',
    'Owns the app-services capabilities port.',
    'Expose runtime capabilities through a service port instead of direct transport calls.',
    'Capabilities port contract changes.',
    'hexagonal_boundary',
    array['capabilitiesPort']::text[],
    array['apps/web/src/app/services/capabilities/**']::text[],
    'TEST-WEB-SERVICES-CAPABILITIES',
    'apps/web/src/capabilities/runtime-capabilities/application/runtimeCapabilitiesCapability.test.ts',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:unit:run -- src/capabilities/runtime-capabilities/application/runtimeCapabilitiesCapability.test.ts'
  ),
  (
    'SYS-WEB-SERVICES-FEEDBACK',
    'Web shell feedback service port',
    'SYS-WEB-APP-SERVICES',
    'REL-WEB-APP-SERVICES-CONTAINS-FEEDBACK',
    'review',
    false,
    'port',
    'application',
    'Frontend / Web',
    'apps/web/src/app/services/feedback',
    'Shell feedback service port consumed by shell presentation',
    'browser',
    'low',
    'review',
    'ShellFeedbackPort',
    'SubmitShellFeedback',
    'Owns shell feedback service port definitions.',
    'Expose shell feedback behavior through a typed web service port.',
    'Shell feedback port contract changes.',
    'hexagonal_boundary',
    array['shellFeedbackPort']::text[],
    array['apps/web/src/app/services/feedback/**']::text[],
    'TEST-WEB-SERVICES-FEEDBACK',
    'apps/web/src/app/Root.test.tsx',
    'unit',
    'smoke',
    'pnpm --filter @dvt/web test:presentation:run -- src/app/Root.test.tsx'
  ),
  (
    'SYS-WEB-APP-PLUGINS',
    'Web app plugins composite',
    'SYS-WEB-ROOT',
    'REL-WEB-ROOT-CONTAINS-APP-PLUGINS',
    'review',
    true,
    'module',
    'application',
    'Frontend / Plugins',
    'apps/web/src/app/plugins',
    'Composite plugin runtime area; concrete plugin families are owned by child leaves',
    'browser',
    'medium',
    'review',
    'WebPluginRuntime',
    'RegisterNodeTypePlugin;ResolveCanvasSurfaceStrategy;ResolveGraphNodeCardReadModel',
    'Composite plugins component. Concrete plugin files are owned by child leaves.',
    'Route graph, dbt, dvt, cost, monitoring, contracts, and registry files to plugin leaves.',
    'Plugin taxonomy, runtime registry, or plugin surface boundary changes.',
    'responsibility_overload',
    array['PluginRegistry']::text[],
    array[]::text[],
    'TEST-WEB-APP-PLUGINS',
    'apps/web/src/app/plugins/registry.test.ts',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:unit:run -- src/app/plugins/registry.test.ts'
  ),
  (
    'SYS-WEB-PLUGINS-CORE',
    'Web plugin runtime core',
    'SYS-WEB-APP-PLUGINS',
    'REL-WEB-APP-PLUGINS-CONTAINS-CORE',
    'review',
    false,
    'module',
    'application',
    'Frontend / Plugins',
    'apps/web/src/app/plugins/registry.ts',
    'Plugin registry, event bus, strategy contracts, node type catalog, and fallback renderer',
    'browser',
    'medium',
    'review',
    'WebPluginRuntimeCore',
    'RegisterNodeTypePlugin;ResolveCanvasSurfaceStrategy;ResolveGraphNodeCardReadModel',
    'Owns core plugin runtime registry and contract files.',
    'Register plugin manifests, node types, graph strategies, and runtime projections.',
    'Plugin registry, event bus, strategy contract, or node type catalog changes.',
    'hexagonal_boundary',
    array['PluginRegistry', 'PluginEventBus', 'nodeTypeCatalog']::text[],
    array[
      'apps/web/src/app/plugins/canvasExecutionStrategyContracts.ts',
      'apps/web/src/app/plugins/canvasSurfaceStrategyContracts.ts',
      'apps/web/src/app/plugins/FallbackNodeRenderer.tsx',
      'apps/web/src/app/plugins/graphStrategyContracts.ts',
      'apps/web/src/app/plugins/graphStrategyRegistry.test.ts',
      'apps/web/src/app/plugins/graphStrategyRegistry.ts',
      'apps/web/src/app/plugins/mergeDecorations.ts',
      'apps/web/src/app/plugins/nodeTypeCatalog.dbt.ts',
      'apps/web/src/app/plugins/nodeTypeCatalog.ts',
      'apps/web/src/app/plugins/nodeTypeContracts.ts',
      'apps/web/src/app/plugins/nodeTypeRegistry.ts',
      'apps/web/src/app/plugins/PluginEventBus.ts',
      'apps/web/src/app/plugins/PluginRegistry.ts',
      'apps/web/src/app/plugins/PluginRegistryContext.tsx',
      'apps/web/src/app/plugins/pluginRuntimeProjection.architecture.test.ts',
      'apps/web/src/app/plugins/registry.test.ts',
      'apps/web/src/app/plugins/registry.ts'
    ]::text[],
    'TEST-WEB-PLUGINS-CORE',
    'apps/web/src/app/plugins/registry.test.ts',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:unit:run -- src/app/plugins/registry.test.ts src/app/plugins/graphStrategyRegistry.test.ts'
  ),
  (
    'SYS-WEB-PLUGINS-GRAPH',
    'Web graph plugins',
    'SYS-WEB-APP-PLUGINS',
    'REL-WEB-APP-PLUGINS-CONTAINS-GRAPH',
    'review',
    false,
    'module',
    'application',
    'Frontend / Graph',
    'apps/web/src/app/plugins/graph',
    'Graph node card read models, strategies, renderers, and visual tokens',
    'browser',
    'medium',
    'review',
    'GraphPluginRuntime',
    'ResolveGraphNodeCardReadModel;RenderGraphNodeCard',
    'Owns graph plugin read model, renderer, and strategy files.',
    'Render generic graph node cards and visual token strategy behavior.',
    'Graph plugin read model, strategy, renderer, or visual token changes.',
    'hexagonal_boundary',
    array['graphNodeCardReadModel', 'GraphNodeCardView']::text[],
    array['apps/web/src/app/plugins/graph/**']::text[],
    'TEST-WEB-PLUGINS-GRAPH',
    'apps/web/src/app/plugins/graph/graphNodeCardReadModel.test.ts',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:unit:run -- src/app/plugins/graph/graphNodeCardReadModel.test.ts'
  ),
  (
    'SYS-WEB-PLUGINS-DBT',
    'Web dbt plugins',
    'SYS-WEB-APP-PLUGINS',
    'REL-WEB-APP-PLUGINS-CONTAINS-DBT',
    'review',
    false,
    'adapter',
    'application',
    'Frontend / DBT',
    'apps/web/src/app/plugins/dbt',
    'DBT node adapters, renderers, graph card strategy, and contribution rules',
    'browser',
    'medium',
    'review',
    'DbtPluginRuntime',
    'ConfigureCanvasDbtNode;BuildDbtPlannerGraphSource;ResolveDbtNodeRendering',
    'Owns dbt-specific plugin adapters, renderers, and contribution files.',
    'Register dbt node behavior, rendering, graph strategy, and connection rules.',
    'DBT plugin adapter, contribution, renderer, or graph strategy changes.',
    'hexagonal_boundary',
    array['dbtContributions', 'DbtNodeRenderer']::text[],
    array['apps/web/src/app/plugins/dbt/**']::text[],
    'TEST-WEB-PLUGINS-DBT',
    'apps/web/src/app/plugins/dbt/dbtNodeAdapter.test.ts',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:unit:run -- src/app/plugins/dbt/dbtNodeAdapter.test.ts src/app/plugins/dbt/dbtContributions.connectionRules.test.ts'
  ),
  (
    'SYS-WEB-PLUGINS-DVT',
    'Web DVT plugins',
    'SYS-WEB-APP-PLUGINS',
    'REL-WEB-APP-PLUGINS-CONTAINS-DVT',
    'review',
    false,
    'adapter',
    'application',
    'Frontend / DVT',
    'apps/web/src/app/plugins/dvt',
    'DVT node catalog, contribution rules, canvas surface strategy, and transformation graph strategy',
    'browser',
    'medium',
    'review',
    'DvtPluginRuntime',
    'ConfigureCanvasDvtNode;GenerateTransformationWorkspaceArtifacts;ResolveDvtNodeRendering',
    'Owns DVT-specific plugin adapters, strategies, and contribution files.',
    'Register DVT node behavior, transformation graph strategy, and connection rules.',
    'DVT plugin contribution, strategy, catalog, or graph behavior changes.',
    'hexagonal_boundary',
    array['dvtContributions', 'transformationGraphStrategy']::text[],
    array['apps/web/src/app/plugins/dvt/**']::text[],
    'TEST-WEB-PLUGINS-DVT',
    'apps/web/src/app/plugins/dvt/dvtContributions.connectionRules.test.ts',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:unit:run -- src/app/plugins/dvt/dvtContributions.connectionRules.test.ts'
  ),
  (
    'SYS-WEB-PLUGINS-CONTRACTS',
    'Web plugin contracts',
    'SYS-WEB-APP-PLUGINS',
    'REL-WEB-APP-PLUGINS-CONTAINS-CONTRACTS',
    'review',
    false,
    'module',
    'contracts',
    'Frontend / Plugins',
    'apps/web/src/app/plugins/contracts',
    'Plugin context, services, manifests, node rendering, and connection rules contracts',
    'browser',
    'medium',
    'review',
    'PluginContractSet',
    'RegisterNodeTypePlugin;ResolvePluginContribution',
    'Owns app-local plugin contract definitions and contract tests.',
    'Define plugin manifests, context, services, rendering, and connection rule contracts.',
    'Plugin contract or connection rule changes.',
    'hexagonal_boundary',
    array['PluginManifest', 'ConnectionRules']::text[],
    array['apps/web/src/app/plugins/contracts/**']::text[],
    'TEST-WEB-PLUGINS-CONTRACTS',
    'apps/web/src/app/plugins/contracts/ConnectionRules.test.ts',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:unit:run -- src/app/plugins/contracts/ConnectionRules.test.ts'
  ),
  (
    'SYS-WEB-PLUGINS-COST',
    'Web cost plugins',
    'SYS-WEB-APP-PLUGINS',
    'REL-WEB-APP-PLUGINS-CONTAINS-COST',
    'review',
    false,
    'module',
    'application',
    'Frontend / Cost',
    'apps/web/src/app/plugins/cost',
    'Cost plugin contributions and route handle',
    'browser',
    'medium',
    'review',
    'CostPluginContribution',
    'ReadCostDashboard;RegisterCostPluginContribution',
    'Owns cost plugin contribution files.',
    'Register cost route and contribution behavior for the plugin runtime.',
    'Cost plugin contribution or route handle changes.',
    'hidden_authority',
    array['costContributions']::text[],
    array['apps/web/src/app/plugins/cost/**']::text[],
    'TEST-WEB-PLUGINS-COST',
    'apps/web/src/app/plugins/cost/costContributions.test.ts',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:unit:run -- src/app/plugins/cost/costContributions.test.ts'
  ),
  (
    'SYS-WEB-PLUGINS-MONITORING',
    'Web monitoring plugins',
    'SYS-WEB-APP-PLUGINS',
    'REL-WEB-APP-PLUGINS-CONTAINS-MONITORING',
    'review',
    false,
    'module',
    'application',
    'Frontend / Monitoring',
    'apps/web/src/app/plugins/monitoring',
    'Monitoring plugin contributions',
    'browser',
    'medium',
    'review',
    'MonitoringPluginContribution',
    'RegisterMonitoringPluginContribution',
    'Owns monitoring plugin contribution files.',
    'Register monitoring contribution behavior for the plugin runtime.',
    'Monitoring plugin contribution changes.',
    'hidden_authority',
    array['monitoringContributions']::text[],
    array['apps/web/src/app/plugins/monitoring/**']::text[],
    'TEST-WEB-PLUGINS-MONITORING',
    'apps/web/src/app/plugins/monitoring/monitoringContributions.test.ts',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:unit:run -- src/app/plugins/monitoring/monitoringContributions.test.ts'
  ),
  (
    'SYS-WEB-APP-COMPONENTS',
    'Web app components composite',
    'SYS-WEB-ROOT',
    'REL-WEB-ROOT-CONTAINS-APP-COMPONENTS',
    'review',
    true,
    'module',
    'ui',
    'Frontend / Web',
    'apps/web/src/app/components',
    'Composite shared component area; concrete component families are owned by child leaves',
    'browser',
    'medium',
    'implemented',
    'WebAppComponentsComposite',
    'RenderWebComponentShell;ReadComponentProfile',
    'Composite shared component module. Concrete files are owned by child components.',
    'Route component families to UI, shell, Monaco, Canvas, console, domain, Figma, workbench, and root widget leaves.',
    'Shared component taxonomy or cross-view presentation component changes.',
    'responsibility_overload',
    array['components']::text[],
    array[]::text[],
    'TEST-WEB-APP-COMPONENTS',
    'apps/web/src/app/components/domain/domainComponents.test.tsx',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:presentation:run -- src/app/components/domain/domainComponents.test.tsx'
  ),
  (
    'SYS-WEB-APP-COMPONENTS-UI',
    'Web UI primitives',
    'SYS-WEB-APP-COMPONENTS',
    'REL-WEB-APP-COMPONENTS-CONTAINS-UI',
    'review',
    false,
    'module',
    'ui',
    'Frontend / Web',
    'apps/web/src/app/components/ui',
    'Shared shadcn-style UI primitives and primitive tests',
    'browser',
    'medium',
    'review',
    'WebUiPrimitives',
    'RenderWebUiPrimitive',
    'Owns shared UI primitives under components/ui.',
    'Provide reusable UI primitives without owning page-specific behavior.',
    'UI primitive, primitive styling, or primitive test changes.',
    'hidden_authority',
    array['Button', 'Dialog', 'Tabs']::text[],
    array['apps/web/src/app/components/ui/**']::text[],
    'TEST-WEB-APP-COMPONENTS-UI',
    'apps/web/src/app/components/ui/calendar.test.tsx',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:presentation:run -- src/app/components/ui/calendar.test.tsx'
  ),
  (
    'SYS-WEB-APP-COMPONENTS-SHELL',
    'Web shell components',
    'SYS-WEB-APP-COMPONENTS',
    'REL-WEB-APP-COMPONENTS-CONTAINS-SHELL',
    'review',
    false,
    'ui-view',
    'ui',
    'Frontend / Web',
    'apps/web/src/app/components/shell',
    'Reusable shell frame, menus, drawers, project identity, and shell state controls',
    'browser',
    'medium',
    'review',
    'WebShellComponents',
    'RenderWebShell;ResolveShellNavigation',
    'Owns reusable shell presentation components.',
    'Render shell frame, app menu, operational drawers, project identity, and shell controls.',
    'Shell component, drawer, menu, or shell metadata changes.',
    'hidden_authority',
    array['AppShellFrame', 'OperationalDrawerPanels']::text[],
    array['apps/web/src/app/components/shell/**']::text[],
    'TEST-WEB-APP-COMPONENTS-SHELL',
    'apps/web/src/app/components/shell/AppShellFrame.test.tsx',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:presentation:run -- src/app/components/shell/AppShellFrame.test.tsx src/app/components/shell/OperationalDrawerPanels.test.tsx'
  ),
  (
    'SYS-WEB-APP-COMPONENTS-MONACO',
    'Web Monaco code components',
    'SYS-WEB-APP-COMPONENTS',
    'REL-WEB-APP-COMPONENTS-CONTAINS-MONACO',
    'review',
    false,
    'ui-view',
    'ui',
    'Frontend / Web',
    'apps/web/src/app/components/monaco',
    'Monaco code editor, viewer, diff surfaces, local workers, and architecture guards',
    'browser',
    'medium',
    'review',
    'MonacoCodeSurfaceComponents',
    'RenderCodeEditor;RenderCodeDiff;ReadWorkspaceFiles',
    'Owns Monaco editor and viewer components.',
    'Render code, diffs, and Monaco worker behavior without owning artifact semantics.',
    'Monaco editor, viewer, diff, token, or worker isolation changes.',
    'hexagonal_boundary',
    array['MonacoCodeEditor', 'MonacoDiffViewer']::text[],
    array['apps/web/src/app/components/monaco/**']::text[],
    'TEST-WEB-APP-COMPONENTS-MONACO',
    'apps/web/src/app/components/monaco/monacoBundleIsolation.architecture.test.ts',
    'architecture',
    'boundary',
    'pnpm --filter @dvt/web test:architecture:run -- src/app/components/monaco/monacoBundleIsolation.architecture.test.ts src/app/components/monaco/monacoVisualTokens.architecture.test.ts'
  ),
  (
    'SYS-WEB-APP-COMPONENTS-CANVAS',
    'Web Canvas shared components',
    'SYS-WEB-APP-COMPONENTS',
    'REL-WEB-APP-COMPONENTS-CONTAINS-CANVAS',
    'review',
    false,
    'ui-view',
    'ui',
    'Frontend / Canvas',
    'apps/web/src/app/components/canvas',
    'Canvas node shell, DBT node component, node context menu model, and workspace explorer model',
    'browser',
    'medium',
    'review',
    'CanvasSharedComponents',
    'RenderCanvasNodeShell;ResolveCanvasContextMenu',
    'Owns shared Canvas components outside route-specific Canvas views.',
    'Render Canvas node shell, DBT node component, node context menu model, and workspace explorer model.',
    'Shared Canvas component or Canvas node shell changes.',
    'hidden_authority',
    array['CanvasNodeShell', 'DbtNodeComponent']::text[],
    array['apps/web/src/app/components/canvas/**', 'apps/web/src/app/components/canvasWorkspaceExplorerModel%']::text[],
    'TEST-WEB-APP-COMPONENTS-CANVAS',
    'apps/web/src/app/components/canvas/CanvasNodeShell.test.tsx',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:presentation:run -- src/app/components/canvas/CanvasNodeShell.test.tsx'
  ),
  (
    'SYS-WEB-APP-COMPONENTS-CONSOLE',
    'Web console components',
    'SYS-WEB-APP-COMPONENTS',
    'REL-WEB-APP-COMPONENTS-CONTAINS-CONSOLE',
    'review',
    false,
    'ui-view',
    'ui',
    'Frontend / Web',
    'apps/web/src/app/components/console',
    'Console view, xterm console, log formatting, and stream hook',
    'browser',
    'medium',
    'review',
    'WebConsoleComponents',
    'ReadRunLogs;RenderConsoleOutput',
    'Owns console presentation components and log stream formatting.',
    'Render console output and normalize log line presentation.',
    'Console component, log stream, or log line formatting changes.',
    'hidden_authority',
    array['Console', 'XtermConsole']::text[],
    array['apps/web/src/app/components/console/**', 'apps/web/src/app/components/Console%']::text[],
    'TEST-WEB-APP-COMPONENTS-CONSOLE',
    'apps/web/src/app/components/Console.test.tsx',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:presentation:run -- src/app/components/Console.test.tsx'
  ),
  (
    'SYS-WEB-APP-COMPONENTS-DOMAIN',
    'Web domain display components',
    'SYS-WEB-APP-COMPONENTS',
    'REL-WEB-APP-COMPONENTS-CONTAINS-DOMAIN',
    'review',
    false,
    'module',
    'ui',
    'Frontend / Web',
    'apps/web/src/app/components/domain',
    'Domain display components such as stat cards, status indicators, headers, and overlays',
    'browser',
    'low',
    'review',
    'WebDomainDisplayComponents',
    'RenderDomainStatusSummary',
    'Owns shared domain display components.',
    'Render domain status, header, and overlay primitives reused by route views.',
    'Shared domain display component changes.',
    'hidden_authority',
    array['StatCard', 'StatusIndicator', 'ViewHeader']::text[],
    array['apps/web/src/app/components/domain/**']::text[],
    'TEST-WEB-APP-COMPONENTS-DOMAIN',
    'apps/web/src/app/components/domain/domainComponents.test.tsx',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:presentation:run -- src/app/components/domain/domainComponents.test.tsx'
  ),
  (
    'SYS-WEB-APP-COMPONENTS-FIGMA',
    'Web Figma fallback components',
    'SYS-WEB-APP-COMPONENTS',
    'REL-WEB-APP-COMPONENTS-CONTAINS-FIGMA',
    'review',
    false,
    'module',
    'ui',
    'Frontend / Web',
    'apps/web/src/app/components/figma',
    'Figma image fallback component and tests',
    'browser',
    'low',
    'review',
    'FigmaImageFallbackComponent',
    'RenderImageWithFallback',
    'Owns Figma image fallback behavior.',
    'Render images with fallback handling for imported Figma-like surfaces.',
    'Image fallback behavior changes.',
    'hidden_authority',
    array['ImageWithFallback']::text[],
    array['apps/web/src/app/components/figma/**']::text[],
    'TEST-WEB-APP-COMPONENTS-FIGMA',
    'apps/web/src/app/components/figma/ImageWithFallback.test.tsx',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:presentation:run -- src/app/components/figma/ImageWithFallback.test.tsx'
  ),
  (
    'SYS-WEB-APP-COMPONENTS-WORKBENCH',
    'Web route workbench components',
    'SYS-WEB-APP-COMPONENTS',
    'REL-WEB-APP-COMPONENTS-CONTAINS-WORKBENCH',
    'review',
    false,
    'ui-view',
    'ui',
    'Frontend / Web',
    'apps/web/src/app/components/workbench',
    'RouteWorkbenchFrame and workbench state components',
    'browser',
    'medium',
    'review',
    'RouteWorkbenchComponents',
    'RenderRouteWorkbench',
    'Owns route workbench frame and workbench state presentation components.',
    'Render route-level workbench frame, table tokens, and workbench state overlays.',
    'Route workbench frame, state, or table token changes.',
    'hidden_authority',
    array['RouteWorkbenchFrame', 'WorkbenchStates']::text[],
    array['apps/web/src/app/components/workbench/**']::text[],
    'TEST-WEB-APP-COMPONENTS-WORKBENCH',
    'apps/web/src/app/components/workbench/RouteWorkbenchFrame.test.tsx',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:presentation:run -- src/app/components/workbench/RouteWorkbenchFrame.test.tsx src/app/components/workbench/state/WorkbenchStates.test.tsx'
  ),
  (
    'SYS-WEB-APP-COMPONENTS-ROOT-WIDGETS',
    'Web root widgets',
    'SYS-WEB-APP-COMPONENTS',
    'REL-WEB-APP-COMPONENTS-CONTAINS-ROOT-WIDGETS',
    'review',
    false,
    'ui-view',
    'ui',
    'Frontend / Web',
    'apps/web/src/app/components/TopAppBar.tsx',
    'Top-level shared widgets under components that do not belong to a component family directory',
    'browser',
    'medium',
    'review',
    'WebRootWidgets',
    'RenderTopAppBar;RenderModals;RenderWebBrand',
    'Owns top-level shared widgets under apps/web/src/app/components.',
    'Render app brand, top app bar, navigation, modals, and shell health banner widgets.',
    'Top-level shared widget changes.',
    'responsibility_overload',
    array['TopAppBar', 'Modals', 'LeftNavigation']::text[],
    array[
      'apps/web/src/app/components/AppBrandMark.tsx',
      'apps/web/src/app/components/LeftNavigation.tsx',
      'apps/web/src/app/components/Modals%',
      'apps/web/src/app/components/ShellHealthBanner.tsx',
      'apps/web/src/app/components/TopAppBar%'
    ]::text[],
    'TEST-WEB-APP-COMPONENTS-ROOT-WIDGETS',
    'apps/web/src/app/components/TopAppBar.test.tsx',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:presentation:run -- src/app/components/TopAppBar.test.tsx src/app/components/Modals.test.tsx'
  ),
  (
    'SYS-WEB-CANVAS-SOURCE-IMPORT-WIZARD',
    'Web Canvas Source Import Wizard',
    'SYS-WEB-CANVAS-ADD-SOURCE-DIALOG',
    'REL-WEB-CANVAS-ADD-SOURCE-DIALOG-CONTAINS-SOURCE-IMPORT-WIZARD',
    'review',
    true,
    'ui-view',
    'ui',
    'Frontend / Canvas',
    'apps/web/src/app/components/sourceImportWizard',
    'Composite source import wizard; core, steps, frame, and tests are owned by child leaves',
    'browser',
    'medium',
    'implemented',
    'SourceImportWizard',
    'ListWarehouseConnections;ListWarehouseConnectionTables;ImportWarehouseSources',
    'Composite source import wizard boundary. Concrete files are owned by child components.',
    'Coordinate source import data loading, step flow, core model, frame, and tests through child leaves.',
    'Source import wizard workflow, data loading, metadata model, or child component ownership changes.',
    'responsibility_overload',
    array['SourceImportWizard']::text[],
    array[]::text[],
    'TEST-WEB-CANVAS-SOURCE-IMPORT-WIZARD',
    'apps/web/src/app/components/sourceImportWizard/sourceImportWizardModel.test.ts',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:unit:run -- src/app/components/sourceImportWizard/sourceImportWizardModel.test.ts'
  ),
  (
    'SYS-WEB-CANVAS-SOURCE-IMPORT-WIZARD-CORE',
    'Canvas source import wizard core',
    'SYS-WEB-CANVAS-SOURCE-IMPORT-WIZARD',
    'REL-WEB-CANVAS-SOURCE-IMPORT-WIZARD-CONTAINS-CORE',
    'review',
    false,
    'ui-view',
    'ui',
    'Frontend / Canvas',
    'apps/web/src/app/components/SourceImportWizard.tsx',
    'Source import wizard core component, model, hooks, copy, constants, and data loaders',
    'browser',
    'medium',
    'review',
    'SourceImportWizardCore',
    'ListWarehouseConnections;ListWarehouseConnectionTables;ImportWarehouseSources',
    'Owns the source import wizard core component, hooks, model, data loaders, copy, and contracts.',
    'Coordinate wizard state, data loading, command submission, and core source import model behavior.',
    'Source import wizard core component, hook, model, data loader, or copy changes.',
    'hexagonal_boundary',
    array['SourceImportWizard', 'useSourceImportWizard']::text[],
    array[
      'apps/web/src/app/components/SourceImportWizard%',
      'apps/web/src/app/components/sourceImportWizard/constants.ts',
      'apps/web/src/app/components/sourceImportWizard/copy.ts',
      'apps/web/src/app/components/sourceImportWizard/sourceImportWizardModel%',
      'apps/web/src/app/components/sourceImportWizard/types.ts',
      'apps/web/src/app/components/sourceImportWizard/useSourceImportWizard%',
      'apps/web/src/app/components/sourceImportWizard/useSourceImportWizardDataLoaders.ts'
    ]::text[],
    'TEST-WEB-CANVAS-SOURCE-IMPORT-WIZARD-CORE',
    'apps/web/src/app/components/sourceImportWizard/sourceImportWizardModel.test.ts',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:unit:run -- src/app/components/sourceImportWizard/sourceImportWizardModel.test.ts'
  ),
  (
    'SYS-WEB-CANVAS-SOURCE-IMPORT-WIZARD-STEPS',
    'Canvas source import wizard steps',
    'SYS-WEB-CANVAS-SOURCE-IMPORT-WIZARD',
    'REL-WEB-CANVAS-SOURCE-IMPORT-WIZARD-CONTAINS-STEPS',
    'review',
    false,
    'ui-view',
    'ui',
    'Frontend / Canvas',
    'apps/web/src/app/components/sourceImportWizard/ConnectionStep.tsx',
    'Source import wizard step presentation components',
    'browser',
    'medium',
    'review',
    'SourceImportWizardSteps',
    'ListWarehouseConnections;ListWarehouseConnectionTables;ImportWarehouseSources',
    'Owns the source import wizard step presentation components.',
    'Render connection, selection, grouping, options, review, result, and step content presentations.',
    'Source import wizard step presentation or section ordering changes.',
    'responsibility_overload',
    array['ConnectionStep', 'SelectionStep', 'WizardStepContent']::text[],
    array[
      'apps/web/src/app/components/sourceImportWizard/ConnectionStep.tsx',
      'apps/web/src/app/components/sourceImportWizard/GroupingStep.tsx',
      'apps/web/src/app/components/sourceImportWizard/OptionsStep.tsx',
      'apps/web/src/app/components/sourceImportWizard/ResultStep.tsx',
      'apps/web/src/app/components/sourceImportWizard/ReviewStep.tsx',
      'apps/web/src/app/components/sourceImportWizard/SelectionStep.tsx',
      'apps/web/src/app/components/sourceImportWizard/WizardStepContent.tsx'
    ]::text[],
    'TEST-WEB-CANVAS-SOURCE-IMPORT-WIZARD-STEPS',
    'apps/web/src/app/components/SourceImportWizard.test.tsx',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:presentation:run -- src/app/components/SourceImportWizard.test.tsx'
  ),
  (
    'SYS-WEB-CANVAS-INSPECTOR-NODE-PROPERTIES-TABS',
    'Web Canvas inspector node properties tabs',
    'SYS-WEB-APP-COMPONENTS',
    'REL-WEB-APP-COMPONENTS-CONTAINS-INSPECTOR-TABS',
    'review',
    true,
    'ui-view',
    'ui',
    'Frontend / Canvas',
    'apps/web/src/app/components/inspector',
    'Composite inspector tabs directory; presenter, read model, and tests are owned by child leaves',
    'browser',
    'medium',
    'review',
    'CanvasInspectorTabs',
    'InspectCanvasNodeProperties;RenderNodePropertiesTabs',
    'Composite inspector tabs boundary. Concrete files are owned by child leaves.',
    'Coordinate inspector node properties tabs, presenter, read model, and tests.',
    'Inspector tab vocabulary, read model, presenter, or tests change.',
    'responsibility_overload',
    array['NodePropertiesTabs']::text[],
    array[]::text[],
    'TEST-WEB-CANVAS-INSPECTOR-NODE-PROPERTIES-TABS',
    'apps/web/src/app/components/inspector/NodePropertiesTabs.test.tsx',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:presentation:run -- src/app/components/inspector/NodePropertiesTabs.test.tsx'
  ),
  (
    'SYS-WEB-CANVAS-INSPECTOR-NODE-PROPERTIES-READ-MODEL',
    'Canvas inspector node properties read model',
    'SYS-WEB-CANVAS-INSPECTOR-NODE-PROPERTIES-TABS',
    'REL-WEB-CANVAS-INSPECTOR-NODE-PROPERTIES-TABS-CONTAINS-READ-MODEL',
    'review',
    false,
    'module',
    'application',
    'Frontend / Canvas',
    'apps/web/src/app/components/inspector/nodePropertiesReadModel.ts',
    'Node properties read model and tests for Canvas inspector tabs',
    'browser',
    'medium',
    'review',
    'NodePropertiesReadModel',
    'InspectCanvasNodeProperties',
    'Owns node properties read model transformation and tests.',
    'Build the passive read model consumed by NodePropertiesTabs.',
    'Node properties read model or test changes.',
    'hidden_authority',
    array['nodePropertiesReadModel']::text[],
    array['apps/web/src/app/components/inspector/nodePropertiesReadModel%']::text[],
    'TEST-WEB-CANVAS-INSPECTOR-NODE-PROPERTIES-READ-MODEL',
    'apps/web/src/app/components/inspector/nodePropertiesReadModel.test.ts',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:unit:run -- src/app/components/inspector/nodePropertiesReadModel.test.ts'
  ),
  (
    'SYS-WEB-CANVAS-INSPECTOR-PANEL',
    'Canvas inspector panel',
    'SYS-WEB-CANVAS-NODE-WORKBENCH',
    'REL-WEB-CANVAS-NODE-WORKBENCH-CONTAINS-INSPECTOR-PANEL',
    'review',
    false,
    'ui-view',
    'ui',
    'Frontend / Canvas',
    'apps/web/src/app/components/InspectorPanel.tsx',
    'Canvas inspector panel presentation and tests',
    'browser',
    'medium',
    'implemented',
    'CanvasInspectorPanel',
    'InspectCanvasNodeProperties;RenderCanvasNodeShell',
    'Owns the canonical Canvas InspectorPanel component and its focused test.',
    'Render inspector panel layout and plugin tab handoff for node workbench flows.',
    'Inspector panel presentation, plugin tabs, or panel test changes.',
    'duplicate_semantics',
    array['InspectorPanel']::text[],
    array['apps/web/src/app/components/InspectorPanel%']::text[],
    'TEST-WEB-CANVAS-INSPECTOR-PANEL',
    'apps/web/src/app/components/InspectorPanel.test.tsx',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:presentation:run -- src/app/components/InspectorPanel.test.tsx'
  ),
  (
    'SYS-WEB-APP-VIEWS',
    'Web route views composite',
    'SYS-WEB-ROOT',
    'REL-WEB-ROOT-CONTAINS-APP-VIEWS',
    'review',
    true,
    'ui-view',
    'ui',
    'Frontend / Web',
    'apps/web/src/app/views',
    'Composite route views area; concrete route view files are owned by route leaves',
    'browser',
    'medium',
    'review',
    'WebRouteViews',
    'RenderRouteWorkbench;ReadRouteViewModel',
    'Composite route views component. Concrete route view files are owned by child leaves.',
    'Route admin, artifacts, code, cost, diff, lineage, plugins, runs, templates, onboarding, login, and support files to view leaves.',
    'Route view taxonomy or route view ownership changes.',
    'responsibility_overload',
    array['views']::text[],
    array[]::text[],
    'TEST-WEB-APP-VIEWS',
    'apps/web/src/app/views/publicDataVisualSystem.architecture.test.ts',
    'architecture',
    'boundary',
    'pnpm --filter @dvt/web test:architecture:run -- src/app/views/publicDataVisualSystem.architecture.test.ts'
  ),
  (
    'SYS-WEB-VIEW-CANVAS',
    'Web canvas view',
    'SYS-WEB-ROOT',
    'REL-WEB-ROOT-CONTAINS-CANVAS-VIEW',
    'review',
    true,
    'ui-view',
    'ui',
    'Frontend / Canvas',
    'apps/web/src/app/views/Canvas.tsx',
    'Canvas route composite; route files and Canvas subviews are owned by child leaves',
    'browser',
    'high',
    'implemented',
    'CanvasViewComposite',
    'RenderCanvasView;ReadWorkspaceGraphDraft;SubmitWorkspaceGraphDraft',
    'Composite Canvas route view. Concrete files are owned by child components.',
    'Coordinate Canvas route state, contextual workbench, shell main panel, route tests, and residual Canvas route surfaces.',
    'Canvas route-level state, shell composition, or contextual workbench routing changes.',
    'responsibility_overload',
    array['Canvas']::text[],
    array[]::text[],
    'TEST-WEB-VIEW-CANVAS',
    'apps/web/src/app/views/Canvas.architecture.test.ts',
    'architecture',
    'boundary',
    'pnpm --filter @dvt/web test:architecture:run -- src/app/views/Canvas.architecture.test.ts'
  ),
  (
    'SYS-WEB-VIEW-CANVAS-ROUTE',
    'Web Canvas route shell',
    'SYS-WEB-VIEW-CANVAS',
    'REL-WEB-CANVAS-VIEW-CONTAINS-ROUTE',
    'review',
    false,
    'ui-view',
    'ui',
    'Frontend / Canvas',
    'apps/web/src/app/views/Canvas.tsx',
    'Top-level Canvas route component, route tests, support files, and controller harnesses',
    'browser',
    'high',
    'review',
    'CanvasRouteShell',
    'RenderCanvasView;ReadWorkspaceGraphDraft;SubmitWorkspaceGraphDraft',
    'Owns top-level Canvas route files under apps/web/src/app/views.',
    'Render Canvas route shell and validate route states, draft recovery, read-only states, and controller support.',
    'Canvas top-level route component, route state, controller support, or route test changes.',
    'responsibility_overload',
    array['Canvas']::text[],
    array['apps/web/src/app/views/Canvas%']::text[],
    'TEST-WEB-VIEW-CANVAS-ROUTE',
    'apps/web/src/app/views/Canvas.routeStates.smoke.test.tsx',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:presentation:run -- src/app/views/Canvas.routeStates.smoke.test.tsx'
  ),
  (
    'SYS-WEB-VIEW-CANVAS-RESIDUAL-SURFACES',
    'Web Canvas residual route surfaces',
    'SYS-WEB-VIEW-CANVAS',
    'REL-WEB-CANVAS-VIEW-CONTAINS-RESIDUAL-SURFACES',
    'review',
    false,
    'ui-view',
    'ui',
    'Frontend / Canvas',
    'apps/web/src/app/views/canvas',
    'Residual Canvas route surfaces not yet split into narrower Canvas child components',
    'browser',
    'high',
    'review',
    'CanvasResidualRouteSurfaces',
    'RenderCanvasContextualGraphSurface;InspectCanvasNodeProperties;ResolveCanvasContextMenu',
    'Owns remaining Canvas route surface files while narrower leaves continue to override specific files.',
    'Keep the Canvas directory owned while focused child leaves continue to split graph, shell, node, context menu, and source import surfaces.',
    'Canvas route surface file change that has not yet been assigned to a more focused child component.',
    'responsibility_overload',
    array['Canvas route surfaces']::text[],
    array['apps/web/src/app/views/canvas/**']::text[],
    'TEST-WEB-VIEW-CANVAS-RESIDUAL-SURFACES',
    'apps/web/src/app/views/canvas/CanvasStateViews.test.tsx',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:presentation:run -- src/app/views/canvas/CanvasStateViews.test.tsx'
  ),
  (
    'SYS-WEB-VIEWS-ADMIN',
    'Web admin views',
    'SYS-WEB-APP-VIEWS',
    'REL-WEB-APP-VIEWS-CONTAINS-ADMIN',
    'review',
    false,
    'ui-view',
    'ui',
    'Frontend / Admin',
    'apps/web/src/app/views/AdminView.tsx',
    'Admin route view and admin view support files',
    'browser',
    'medium',
    'review',
    'AdminView',
    'ReadAdminDashboard',
    'Owns admin route view files.',
    'Render admin route and admin-specific read models.',
    'Admin route view or admin support changes.',
    'hidden_authority',
    array['AdminView']::text[],
    array['apps/web/src/app/views/admin/**', 'apps/web/src/app/views/AdminView%']::text[],
    'TEST-WEB-VIEWS-ADMIN',
    'apps/web/src/app/views/AdminView.test.tsx',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:presentation:run -- src/app/views/AdminView.test.tsx'
  ),
  (
    'SYS-WEB-VIEWS-ARTIFACTS',
    'Web artifacts views',
    'SYS-WEB-APP-VIEWS',
    'REL-WEB-APP-VIEWS-CONTAINS-ARTIFACTS',
    'review',
    false,
    'ui-view',
    'ui',
    'Frontend / Artifacts',
    'apps/web/src/app/views/ArtifactsView.tsx',
    'Artifacts route view and artifact view modules',
    'browser',
    'medium',
    'review',
    'ArtifactsView',
    'ReadArtifactFiles;ReadWorkspaceArtifacts',
    'Owns artifacts route view files.',
    'Render artifact files and artifact route read models.',
    'Artifacts route, artifact file, or artifact read model changes.',
    'hidden_authority',
    array['ArtifactsView']::text[],
    array['apps/web/src/app/views/artifacts/**', 'apps/web/src/app/views/ArtifactsView%']::text[],
    'TEST-WEB-VIEWS-ARTIFACTS',
    'apps/web/src/app/views/ArtifactsView.test.tsx',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:presentation:run -- src/app/views/ArtifactsView.test.tsx'
  ),
  (
    'SYS-WEB-VIEWS-CODE',
    'Web code views',
    'SYS-WEB-APP-VIEWS',
    'REL-WEB-APP-VIEWS-CONTAINS-CODE',
    'review',
    false,
    'ui-view',
    'ui',
    'Frontend / Code',
    'apps/web/src/app/views/CodeView.tsx',
    'Code route view and code workbench modules',
    'browser',
    'medium',
    'review',
    'CodeView',
    'ReadWorkspaceFiles;ReadWorkspaceDiff',
    'Owns code route view files.',
    'Render code workbench and workspace file read models.',
    'Code view, file tree, editor, or code route changes.',
    'hidden_authority',
    array['CodeView']::text[],
    array['apps/web/src/app/views/code/**', 'apps/web/src/app/views/CodeView%']::text[],
    'TEST-WEB-VIEWS-CODE',
    'apps/web/src/app/views/CodeView.test.tsx',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:presentation:run -- src/app/views/CodeView.test.tsx'
  ),
  (
    'SYS-WEB-VIEWS-COST',
    'Web cost views',
    'SYS-WEB-APP-VIEWS',
    'REL-WEB-APP-VIEWS-CONTAINS-COST',
    'review',
    false,
    'ui-view',
    'ui',
    'Frontend / Cost',
    'apps/web/src/app/views/CostView.tsx',
    'Cost route view and cost view modules',
    'browser',
    'medium',
    'review',
    'CostView',
    'ReadCostDashboard',
    'Owns cost route view files.',
    'Render cost dashboard read models and route state.',
    'Cost route view or cost dashboard presentation changes.',
    'hidden_authority',
    array['CostView']::text[],
    array['apps/web/src/app/views/cost/**', 'apps/web/src/app/views/CostView%']::text[],
    'TEST-WEB-VIEWS-COST',
    'apps/web/src/app/views/CostView.test.tsx',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:presentation:run -- src/app/views/CostView.test.tsx'
  ),
  (
    'SYS-WEB-VIEWS-DIFF',
    'Web diff views',
    'SYS-WEB-APP-VIEWS',
    'REL-WEB-APP-VIEWS-CONTAINS-DIFF',
    'review',
    false,
    'ui-view',
    'ui',
    'Frontend / Diff',
    'apps/web/src/app/views/DiffView.tsx',
    'Diff route view and diff view modules',
    'browser',
    'medium',
    'review',
    'DiffView',
    'ReadWorkspaceDiff',
    'Owns diff route view files.',
    'Render workspace diff read models and diff route state.',
    'Diff route view, diff file, or diff read model changes.',
    'hidden_authority',
    array['DiffView']::text[],
    array['apps/web/src/app/views/diff/**', 'apps/web/src/app/views/DiffView%']::text[],
    'TEST-WEB-VIEWS-DIFF',
    'apps/web/src/app/views/DiffView.test.tsx',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:presentation:run -- src/app/views/DiffView.test.tsx'
  ),
  (
    'SYS-WEB-VIEWS-LINEAGE',
    'Web lineage views',
    'SYS-WEB-APP-VIEWS',
    'REL-WEB-APP-VIEWS-CONTAINS-LINEAGE',
    'review',
    false,
    'ui-view',
    'ui',
    'Frontend / Lineage',
    'apps/web/src/app/views/LineageView.tsx',
    'Lineage route view and lineage modules',
    'browser',
    'medium',
    'review',
    'LineageView',
    'ReadLineageGraph',
    'Owns lineage route view files.',
    'Render lineage graph read models and route state.',
    'Lineage route view or lineage graph presentation changes.',
    'hidden_authority',
    array['LineageView']::text[],
    array['apps/web/src/app/views/lineage/**', 'apps/web/src/app/views/LineageView%']::text[],
    'TEST-WEB-VIEWS-LINEAGE',
    'apps/web/src/app/views/LineageView.test.tsx',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:presentation:run -- src/app/views/LineageView.test.tsx'
  ),
  (
    'SYS-WEB-VIEWS-PLUGINS',
    'Web plugins views',
    'SYS-WEB-APP-VIEWS',
    'REL-WEB-APP-VIEWS-CONTAINS-PLUGINS',
    'review',
    false,
    'ui-view',
    'ui',
    'Frontend / Plugins',
    'apps/web/src/app/views/PluginsView.tsx',
    'Plugins route view and plugin view modules',
    'browser',
    'medium',
    'review',
    'PluginsView',
    'ReadPluginCatalog',
    'Owns plugins route view files.',
    'Render plugin catalog read models and plugin route state.',
    'Plugins route view or plugin catalog presentation changes.',
    'hidden_authority',
    array['PluginsView']::text[],
    array['apps/web/src/app/views/plugins/**', 'apps/web/src/app/views/PluginsView%']::text[],
    'TEST-WEB-VIEWS-PLUGINS',
    'apps/web/src/app/views/PluginsView.test.tsx',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:presentation:run -- src/app/views/PluginsView.test.tsx'
  ),
  (
    'SYS-WEB-VIEWS-RUNS',
    'Web runs views',
    'SYS-WEB-APP-VIEWS',
    'REL-WEB-APP-VIEWS-CONTAINS-RUNS',
    'review',
    false,
    'ui-view',
    'ui',
    'Frontend / Runs',
    'apps/web/src/app/views/RunsView.tsx',
    'Runs route view and run timeline modules',
    'browser',
    'high',
    'review',
    'RunsView',
    'StartRun;SignalRun;RecoverRun;GetRunEvents;ListRuns',
    'Owns runs route view files.',
    'Render runs list, runtime status, and run timeline read models.',
    'Runs route view, timeline, or runtime status presentation changes.',
    'hidden_authority',
    array['RunsView']::text[],
    array['apps/web/src/app/views/runs/**', 'apps/web/src/app/views/RunsView%']::text[],
    'TEST-WEB-VIEWS-RUNS',
    'apps/web/src/app/views/RunsView.test.tsx',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:presentation:run -- src/app/views/RunsView.test.tsx'
  ),
  (
    'SYS-WEB-VIEWS-TEMPLATES',
    'Web templates views',
    'SYS-WEB-APP-VIEWS',
    'REL-WEB-APP-VIEWS-CONTAINS-TEMPLATES',
    'review',
    false,
    'ui-view',
    'ui',
    'Frontend / Templates',
    'apps/web/src/app/views/TemplatesView.tsx',
    'Templates route view and template modules',
    'browser',
    'medium',
    'review',
    'TemplatesView',
    'ReadTemplateCatalog',
    'Owns templates route view files.',
    'Render template catalog and template route state.',
    'Templates route view or template catalog changes.',
    'hidden_authority',
    array['TemplatesView']::text[],
    array['apps/web/src/app/views/templates/**', 'apps/web/src/app/views/TemplatesView%']::text[],
    'TEST-WEB-VIEWS-TEMPLATES',
    'apps/web/src/app/views/TemplatesView.test.tsx',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:presentation:run -- src/app/views/TemplatesView.test.tsx'
  ),
  (
    'SYS-WEB-VIEWS-PROJECT-ONBOARDING',
    'Web project onboarding view',
    'SYS-WEB-APP-VIEWS',
    'REL-WEB-APP-VIEWS-CONTAINS-PROJECT-ONBOARDING',
    'review',
    false,
    'ui-view',
    'ui',
    'Frontend / Web',
    'apps/web/src/app/views/ProjectOnboardingView.tsx',
    'Project onboarding route view and tests',
    'browser',
    'medium',
    'review',
    'ProjectOnboardingView',
    'CompleteProjectOnboarding;ReadProjectOnboardingState',
    'Owns project onboarding route view files.',
    'Render project onboarding route and onboarding state.',
    'Project onboarding route view changes.',
    'hidden_authority',
    array['ProjectOnboardingView']::text[],
    array['apps/web/src/app/views/ProjectOnboardingView%']::text[],
    'TEST-WEB-VIEWS-PROJECT-ONBOARDING',
    'apps/web/src/app/views/ProjectOnboardingView.test.tsx',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:presentation:run -- src/app/views/ProjectOnboardingView.test.tsx'
  ),
  (
    'SYS-WEB-VIEWS-LOGIN',
    'Web login view',
    'SYS-WEB-APP-VIEWS',
    'REL-WEB-APP-VIEWS-CONTAINS-LOGIN',
    'review',
    false,
    'ui-view',
    'ui',
    'Frontend / Web',
    'apps/web/src/app/views/LoginView.tsx',
    'Login route view',
    'browser',
    'medium',
    'review',
    'LoginView',
    'RenderLoginView',
    'Owns the login route view.',
    'Render login route shell and authentication entry copy.',
    'Login route view changes.',
    'hidden_authority',
    array['LoginView']::text[],
    array['apps/web/src/app/views/LoginView.tsx']::text[],
    'TEST-WEB-VIEWS-LOGIN',
    'apps/web/src/app/Root.test.tsx',
    'unit',
    'smoke',
    'pnpm --filter @dvt/web test:presentation:run -- src/app/Root.test.tsx'
  ),
  (
    'SYS-WEB-VIEWS-SUPPORT',
    'Web route view support',
    'SYS-WEB-APP-VIEWS',
    'REL-WEB-APP-VIEWS-CONTAINS-SUPPORT',
    'review',
    false,
    'module',
    'ui',
    'Frontend / Web',
    'apps/web/src/app/views/architecture.test.support.ts',
    'Route view architecture support and public data visual system tests',
    'node',
    'medium',
    'review',
    'WebRouteViewSupport',
    'ValidateWebRouteArchitecture',
    'Owns route-view architecture support files.',
    'Provide shared support for route view architecture tests and visual system guards.',
    'Route view architecture support changes.',
    'hidden_authority',
    array['architecture.test.support']::text[],
    array['apps/web/src/app/views/architecture.test.support.ts', 'apps/web/src/app/views/publicDataVisualSystem.architecture.test.ts']::text[],
    'TEST-WEB-VIEWS-SUPPORT',
    'apps/web/src/app/views/publicDataVisualSystem.architecture.test.ts',
    'architecture',
    'boundary',
    'pnpm --filter @dvt/web test:architecture:run -- src/app/views/publicDataVisualSystem.architecture.test.ts'
  ),
  (
    'SYS-WEB-CANVAS-CONTEXTUAL-WORKBENCH',
    'Canvas contextual workbench',
    'SYS-WEB-VIEW-CANVAS',
    'REL-WEB-CANVAS-VIEW-CONTAINS-CONTEXTUAL-WORKBENCH',
    'review',
    true,
    'ui-view',
    'ui',
    'Frontend / Canvas',
    'apps/web/src/app/views/canvas/canvasWorkbenchStateModel.ts',
    'Canvas contextual workbench composite',
    'browser',
    'high',
    'implemented',
    'CanvasContextualWorkbench',
    'RenderCanvasContextualGraphSurface;InspectCanvasNodeProperties;ResolveCanvasContextMenu',
    'Composite Canvas contextual workbench. Concrete files are owned by child leaves.',
    'Coordinate Canvas contextual graph, node, source import, context menu, and workbench state surfaces.',
    'Canvas workbench state model or child workbench composition changes.',
    'responsibility_overload',
    array['canvasWorkbenchStateModel']::text[],
    array[]::text[],
    'TEST-WEB-CANVAS-CONTEXTUAL-WORKBENCH',
    'apps/web/src/app/views/canvas/canvasWorkbenchStateModel.test.ts',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:unit:run -- src/app/views/canvas/canvasWorkbenchStateModel.test.ts'
  ),
  (
    'SYS-WEB-CANVAS-ADD-SOURCE-DIALOG',
    'Canvas add source dialog',
    'SYS-WEB-CANVAS-CONTEXTUAL-WORKBENCH',
    'REL-WEB-CANVAS-CONTEXTUAL-WORKBENCH-CONTAINS-ADD-SOURCE-DIALOG',
    'review',
    true,
    'ui-view',
    'ui',
    'Frontend / Canvas',
    'apps/web/src/app/views/canvas/CanvasModalHost.tsx',
    'Canvas add-source dialog composite and source import entry boundary',
    'browser',
    'medium',
    'implemented',
    'CanvasAddSourceDialog',
    'ListWarehouseConnections;ListWarehouseConnectionTables;ImportWarehouseSources',
    'Composite add-source dialog. Source import wizard children own concrete source import files.',
    'Open warehouse source import workflows from the Canvas modal host.',
    'Add-source modal host or source import entry behavior changes.',
    'responsibility_overload',
    array['CanvasModalHost']::text[],
    array[]::text[],
    'TEST-WEB-CANVAS-ADD-SOURCE-DIALOG',
    'apps/web/src/app/views/canvas/CanvasModalHost.architecture.test.tsx',
    'architecture',
    'boundary',
    'pnpm --filter @dvt/web test:architecture:run -- src/app/views/canvas/CanvasModalHost.architecture.test.tsx'
  ),
  (
    'SYS-WEB-CANVAS-CANVAS-CONTEXT-MENU',
    'Canvas context menu',
    'SYS-WEB-CANVAS-CONTEXTUAL-WORKBENCH',
    'REL-WEB-CANVAS-CONTEXTUAL-WORKBENCH-CONTAINS-CONTEXT-MENU',
    'review',
    true,
    'ui-view',
    'ui',
    'Frontend / Canvas',
    'apps/web/src/app/views/canvas/CanvasContextMenuView.tsx',
    'Canvas context menu composite',
    'browser',
    'medium',
    'implemented',
    'CanvasContextMenu',
    'ResolveCanvasContextMenu',
    'Composite Canvas context-menu boundary. Presenter and tests own concrete files.',
    'Coordinate context-menu view, presenter, palette, and focused tests.',
    'Canvas context menu presentation or action routing changes.',
    'responsibility_overload',
    array['CanvasContextMenuView']::text[],
    array[]::text[],
    'TEST-WEB-CANVAS-CONTEXT-MENU',
    'apps/web/src/app/views/canvas/CanvasContextMenuView.test.tsx',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:presentation:run -- src/app/views/canvas/CanvasContextMenuView.test.tsx'
  ),
  (
    'SYS-WEB-CANVAS-GRAPH-SURFACE',
    'Canvas graph surface',
    'SYS-WEB-CANVAS-CONTEXTUAL-WORKBENCH',
    'REL-WEB-CANVAS-CONTEXTUAL-WORKBENCH-CONTAINS-GRAPH-SURFACE',
    'review',
    true,
    'ui-view',
    'ui',
    'Frontend / Canvas',
    'apps/web/src/app/views/canvas/CanvasCenterSurface.tsx',
    'Canvas graph surface composite',
    'browser',
    'high',
    'implemented',
    'CanvasGraphSurface',
    'RenderCanvasContextualGraphSurface',
    'Composite Canvas graph surface. Graph viewport and residual route surfaces own concrete files.',
    'Coordinate Canvas graph surface composition and graph viewport child routing.',
    'Canvas graph surface rendering or viewport composition changes.',
    'responsibility_overload',
    array['CanvasCenterSurface']::text[],
    array[]::text[],
    'TEST-WEB-CANVAS-GRAPH-SURFACE',
    'apps/web/src/app/views/canvas/CanvasCenterSurface.architecture.test.ts',
    'architecture',
    'boundary',
    'pnpm --filter @dvt/web test:architecture:run -- src/app/views/canvas/CanvasCenterSurface.architecture.test.ts'
  ),
  (
    'SYS-WEB-CANVAS-GRAPH-VIEWPORT',
    'Web Canvas Graph Viewport',
    'SYS-WEB-CANVAS-GRAPH-SURFACE',
    'REL-WEB-CANVAS-GRAPH-SURFACE-CONTAINS-GRAPH-VIEWPORT',
    'review',
    true,
    'ui-view',
    'ui',
    'Frontend / Canvas',
    'apps/web/src/app/views/canvas/CanvasViewport.tsx',
    'Canvas graph viewport composite',
    'browser',
    'high',
    'implemented',
    'CanvasGraphViewport',
    'RenderCanvasContextualGraphSurface;ResolveCanvasContextMenu',
    'Composite Canvas graph viewport. Presentation, model tests, and harness leaves own concrete files.',
    'Coordinate graph viewport rendering, graph model projection, and viewport harness behavior.',
    'Canvas viewport rendering, graph model projection, or viewport harness behavior changes.',
    'responsibility_overload',
    array['CanvasViewport']::text[],
    array[]::text[],
    'TEST-WEB-CANVAS-GRAPH-VIEWPORT',
    'apps/web/src/app/views/canvas/CanvasViewport.test.tsx',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:presentation:run -- src/app/views/canvas/CanvasViewport.test.tsx'
  ),
  (
    'SYS-WEB-CANVAS-NODE-WORKBENCH',
    'Canvas node workbench',
    'SYS-WEB-CANVAS-CONTEXTUAL-WORKBENCH',
    'REL-WEB-CANVAS-CONTEXTUAL-WORKBENCH-CONTAINS-NODE-WORKBENCH',
    'review',
    true,
    'ui-view',
    'ui',
    'Frontend / Canvas',
    'apps/web/src/app/views/canvas/CanvasInspectorPanel.tsx',
    'Canvas node workbench composite',
    'browser',
    'high',
    'implemented',
    'CanvasNodeWorkbench',
    'InspectCanvasNodeProperties;RenderCanvasNodeShell',
    'Composite Canvas node workbench. Inspector panel, DBT/DVT fields, overlays, panels, and test leaves own concrete files.',
    'Coordinate node workbench composition for inspector, fields, panel, overlay, and node authoring children.',
    'Node workbench composition, authoring model, or inspector child routing changes.',
    'responsibility_overload',
    array['CanvasInspectorPanel']::text[],
    array[]::text[],
    'TEST-WEB-CANVAS-NODE-WORKBENCH',
    'apps/web/src/app/views/canvas/CanvasInspectorPanel.authoring.test.tsx',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:presentation:run -- src/app/views/canvas/CanvasInspectorPanel.authoring.test.tsx'
  ),
  (
    'SYS-WEB-CANVAS-SHELL-MAIN-PANEL',
    'Canvas shell main panel',
    'SYS-WEB-VIEW-CANVAS',
    'REL-WEB-CANVAS-VIEW-CONTAINS-SHELL-MAIN-PANEL',
    'review',
    true,
    'ui-view',
    'ui',
    'Frontend / Canvas',
    'apps/web/src/app/views/canvas/CanvasShell.tsx',
    'Canvas shell main panel composite',
    'browser',
    'high',
    'implemented',
    'CanvasShellMainPanel',
    'RenderCanvasShell;ListWarehouseConnections;ImportWarehouseSources',
    'Composite Canvas shell main panel. Shell tests and residual Canvas route surfaces own concrete files.',
    'Coordinate Canvas shell panel composition, contextual dialogs, and source import availability.',
    'Canvas shell panel composition, source import availability, or contextual dialog routing changes.',
    'responsibility_overload',
    array['CanvasShell']::text[],
    array[]::text[],
    'TEST-WEB-CANVAS-SHELL-MAIN-PANEL',
    'apps/web/src/app/views/canvas/CanvasShell.test.tsx',
    'unit',
    'behavior',
    'pnpm --filter @dvt/web test:presentation:run -- src/app/views/canvas/CanvasShell.test.tsx'
  );

insert into architecture.design (
  design_id,
  work_item_id,
  title,
  owner,
  status,
  rationale,
  fowler_signal,
  rail_ref,
  approved_at
)
values (
  'PLANNING-DB-WEB-ROOT-FILESYSTEM-LEAF-COMPONENTS-20260618',
  'PLANNING-DB-COMPONENT-INTEGRITY-VOCABULARY-RAIL-20260612',
  'Web root filesystem leaf component mapping',
  'Architecture / Planning DB / Frontend',
  'review',
  'SYS-WEB-ROOT still owned most apps/web files directly. This design creates filesystem-backed child components and local parent definitions so component-profile can answer files, subcomponents, commands, queries, adapters, ports, tests, docs, and Fowler/DDD ownership without a side inventory.',
  'responsibility_overload',
  'CreateGovernanceComponent;RecordArchitectureComponent;RecordArchitectureRelation;RecordArchitectureTestEvidence;CheckPlanningDbComponentIntegrity',
  now()
)
on conflict (design_id) do update set
  status = excluded.status,
  rationale = excluded.rationale,
  fowler_signal = excluded.fowler_signal,
  rail_ref = excluded.rail_ref,
  updated_at = now();

insert into architecture.design_scope (
  design_id,
  subject_kind,
  subject_id,
  scope_kind,
  required
)
select
  'PLANNING-DB-WEB-ROOT-FILESYSTEM-LEAF-COMPONENTS-20260618',
  scope.subject_kind,
  scope.subject_id,
  scope.scope_kind,
  true
from (
  select 'component'::text as subject_kind, component_id as subject_id, 'may_create'::text as scope_kind
  from web_root_component_leaf_map
  where component_id <> 'SYS-WEB-ROOT'
  union all
  select 'component', 'SYS-WEB-ROOT', 'may_update'
  union all
  select 'path', 'apps/web/**', 'may_update'
  union all
  select 'relation', relation_id, 'may_create'
  from web_root_component_leaf_map
  where relation_id is not null
  union all
  select 'test', test_id, 'may_create'
  from web_root_component_leaf_map
) scope
on conflict (design_id, subject_kind, subject_id, scope_kind) do update set
  required = excluded.required;

insert into planning_query_store.governance_component_local_definitions (
  component_id,
  source_path,
  source_content_sha256,
  revision,
  name,
  level,
  parent_id,
  root_unit,
  domain_unit,
  status,
  children_required,
  owned_concern,
  ddd_owner,
  cq_rails,
  created_by
)
select
  component_id,
  'planning_query_store.governance_component_local_definitions',
  md5(component_id || ':128') || md5(name || ':128'),
  0,
  name,
  'component',
  parent_id,
  'SYS-DVT',
  'SYS-DVT',
  local_status,
  children_required,
  owned_concern,
  ddd_owner,
  cq_rails,
  'codex'
from web_root_component_leaf_map
on conflict (component_id) do update set
  source_path = excluded.source_path,
  source_content_sha256 = excluded.source_content_sha256,
  name = excluded.name,
  level = excluded.level,
  parent_id = excluded.parent_id,
  root_unit = excluded.root_unit,
  domain_unit = excluded.domain_unit,
  status = excluded.status,
  children_required = excluded.children_required,
  owned_concern = excluded.owned_concern,
  ddd_owner = excluded.ddd_owner,
  cq_rails = excluded.cq_rails;

insert into planning_query_store.governance_component_local_ownership_patterns (
  component_id,
  pattern_kind,
  pattern,
  pattern_order
)
select
  component_id,
  'owns',
  own.pattern,
  own.pattern_order - 1
from web_root_component_leaf_map
cross join lateral unnest(owns) with ordinality as own(pattern, pattern_order)
on conflict (component_id, pattern_kind, pattern) do update set
  pattern_order = excluded.pattern_order;

insert into planning_query_store.governance_component_local_semantic_items (
  component_id,
  item_kind,
  item_value,
  item_order
)
select
  item.component_id,
  item.item_kind,
  item.item_value,
  item.item_order
from (
  select component_id, 'responsibility' as item_kind, responsibility as item_value, 0 as item_order
  from web_root_component_leaf_map
  union all
  select component_id, 'reason_to_change', reason_to_change, 0
  from web_root_component_leaf_map
  union all
  select
    component_id,
    'invariant',
    case
      when component_id = 'SYS-WEB-ROOT'
        then 'SYS-WEB-ROOT stays composite; direct web files must be owned by child components.'
      when children_required
        then 'This component stays composite; concrete files must be owned by child components.'
      else 'Concrete files matching this component responsibility are owned by this leaf.'
    end,
    0
  from web_root_component_leaf_map
  union all
  select
    component_id,
    'transition',
    'review -> implemented after component-quality shows no direct files owned by SYS-WEB-ROOT and relevant tests pass.',
    0
  from web_root_component_leaf_map
  union all
  select component_id, 'consumer', 'planning:db:query component-profile and component-quality', 0
  from web_root_component_leaf_map
  union all
  select
    component_id,
    'governance_ref',
    'docs/planning/proposals/mandatory/governance-and-docs/planning-db-component-integrity-vocabulary-rail-plan-20260612.md',
    0
  from web_root_component_leaf_map
  union all
  select component_id, 'fowler_signal', fowler_signal, 0
  from web_root_component_leaf_map
  union all
  select component_id, 'public_api', api.value, api.item_order - 1
  from web_root_component_leaf_map
  cross join lateral unnest(public_api) with ordinality as api(value, item_order)
) item
on conflict (component_id, item_kind, item_value) do update set
  item_order = excluded.item_order;

insert into architecture.component (
  component_id,
  name,
  kind,
  layer,
  owner,
  repo_path,
  public_contract,
  runtime,
  criticality,
  status,
  parent_component_id
)
select
  component_id,
  name,
  architecture_kind,
  architecture_layer,
  architecture_owner,
  repo_path,
  public_contract,
  runtime,
  criticality,
  architecture_status,
  nullif(parent_id, 'SYS-WEB')
from web_root_component_leaf_map
on conflict (component_id) do update set
  name = excluded.name,
  kind = excluded.kind,
  layer = excluded.layer,
  owner = excluded.owner,
  repo_path = excluded.repo_path,
  public_contract = excluded.public_contract,
  runtime = excluded.runtime,
  criticality = excluded.criticality,
  status = excluded.status,
  parent_component_id = excluded.parent_component_id,
  updated_at = now();

insert into architecture.component_responsibility (
  responsibility_id,
  component_id,
  responsibility,
  reason_to_change,
  ddd_owner,
  status
)
select
  'RESP-' || component_id,
  component_id,
  responsibility,
  reason_to_change,
  ddd_owner,
  'proposed'
from web_root_component_leaf_map
on conflict (responsibility_id) do update set
  component_id = excluded.component_id,
  responsibility = excluded.responsibility,
  reason_to_change = excluded.reason_to_change,
  ddd_owner = excluded.ddd_owner,
  status = excluded.status;

insert into architecture.component_relation (
  relation_id,
  source_component_id,
  target_component_id,
  relation_type,
  direction,
  sync_async,
  contract_id,
  failure_mode,
  authorization_scope,
  source_refs,
  status
)
select
  relation_id,
  parent_id,
  component_id,
  'contains',
  'outbound',
  'sync',
  null,
  'not_applicable',
  'internal-ui-component-ownership',
  '["docs/planning/proposals/mandatory/governance-and-docs/planning-db-component-integrity-vocabulary-rail-plan-20260612.md"]'::jsonb,
  'implemented'
from web_root_component_leaf_map
where relation_id is not null
on conflict (relation_id) do update set
  source_component_id = excluded.source_component_id,
  target_component_id = excluded.target_component_id,
  relation_type = excluded.relation_type,
  direction = excluded.direction,
  sync_async = excluded.sync_async,
  contract_id = excluded.contract_id,
  failure_mode = excluded.failure_mode,
  authorization_scope = excluded.authorization_scope,
  source_refs = excluded.source_refs,
  status = excluded.status,
  updated_at = now();

insert into architecture.component_test (
  test_id,
  component_id,
  test_path,
  test_kind,
  coverage_level,
  required,
  validation_command
)
select
  test_id,
  component_id,
  test_path,
  test_kind,
  coverage_level,
  true,
  validation_command
from web_root_component_leaf_map
on conflict (test_id) do update set
  component_id = excluded.component_id,
  test_path = excluded.test_path,
  test_kind = excluded.test_kind,
  coverage_level = excluded.coverage_level,
  required = excluded.required,
  validation_command = excluded.validation_command;

drop table if exists pg_temp.web_root_component_leaf_map;
