-- Give the remaining API, runtime, and adapter component buckets explicit
-- architecture authority. Split the over-broad adapter root into concrete
-- Postgres and Temporal adapter leaves instead of leaving package files owned
-- by a generic root bucket.

drop table if exists pg_temp.adapter_leaf_map;
drop table if exists pg_temp.architecture_authority_seed;

update planning_query_store.governance_components component
set
  status = 'legacy',
  governance_state = 'legacy',
  canonical_role = 'none',
  evidence_state = 'retired',
  is_legacy = true,
  children_required = false,
  cq_rails = 'ReadRuntimeArchitectureDocsViaDocsGovernance',
  fowler_signals = jsonb_build_array('duplicate_authority', 'documentation_ownership_drift'),
  raw_component = component.raw_component || jsonb_build_object(
    'status',
    'legacy',
    'governanceState',
    'legacy',
    'evidenceState',
    'retired',
    'isLegacy',
    true,
    'cqRails',
    'ReadRuntimeArchitectureDocsViaDocsGovernance',
    'deprecatedBy',
    '147_api_runtime_adapter_component_authority',
    'deprecationRationale',
    'Runtime architecture docs are real files but are owned by SYS-DOCS-GOVERNANCE-ARCHITECTURE, SYS-DOCS-GOVERNANCE-EVIDENCE, and SYS-DOCS-GOVERNANCE-RISK-REGISTER.'
  )
where component.component_id = 'SYS-RUNTIME-ARCHITECTURE-DOCS';

update planning_query_store.governance_components component
set
  name = 'Adapter packages root component',
  children_required = true,
  cq_rails = 'MapAdapterPackageComponents;ReadAdapterPackageComponentProfile',
  fowler_signals = jsonb_build_array('bounded_context', 'adapter_boundary', 'component_split'),
  raw_component = component.raw_component || jsonb_build_object(
    'name',
    'Adapter packages root component',
    'childrenRequired',
    true,
    'cqRails',
    'MapAdapterPackageComponents;ReadAdapterPackageComponentProfile',
    'reconciledBy',
    '147_api_runtime_adapter_component_authority'
  )
where component.component_id = 'SYS-ADAPTERS-ROOT';

create temporary table adapter_leaf_map (
  component_id text primary key,
  parent_id text not null,
  name text not null,
  kind text not null,
  layer text not null,
  ddd_owner text not null,
  cq_rails text not null,
  owned_concern text not null,
  responsibility text not null,
  reason_to_change text not null,
  repo_path text not null,
  public_contract text not null,
  fowler_signal text not null,
  port_name text not null,
  port_kind text not null,
  port_direction text not null,
  negative_tests text[] not null,
  owns text[] not null,
  test_path text not null,
  test_kind text not null,
  validation_command text not null,
  observability_signal text not null
);

insert into adapter_leaf_map (
  component_id,
  parent_id,
  name,
  kind,
  layer,
  ddd_owner,
  cq_rails,
  owned_concern,
  responsibility,
  reason_to_change,
  repo_path,
  public_contract,
  fowler_signal,
  port_name,
  port_kind,
  port_direction,
  negative_tests,
  owns,
  test_path,
  test_kind,
  validation_command,
  observability_signal
)
values
  (
    'SYS-ADAPTERS-POSTGRES-PACKAGE-SHELL',
    'SYS-ADAPTERS-ROOT',
    'Postgres adapter package shell',
    'package',
    'adapter',
    'PostgresAdapterPackageShell',
    'ImportPostgresAdapterPackage;ValidatePostgresAdapterPackageSurface',
    'Owns Postgres adapter package metadata, root exports, design note, package configs, and smoke proof.',
    'Expose the Postgres adapter package surface without owning individual storage, state, outbox, or session semantics.',
    'Postgres adapter exports, package config, package smoke test, or public package documentation changes.',
    'packages/@dvt/adapter-postgres/src/index.ts',
    'Postgres adapter package export boundary',
    'published_language',
    'ImportPostgresAdapterPackage',
    'api',
    'inbound',
    array['packages/@dvt/adapter-postgres/test/smoke.test.ts']::text[],
    array[
      'packages/@dvt/adapter-postgres/DESIGN.md',
      'packages/@dvt/adapter-postgres/package.json',
      'packages/@dvt/adapter-postgres/src/index.ts',
      'packages/@dvt/adapter-postgres/src/PostgresAdapterConstants.ts',
      'packages/@dvt/adapter-postgres/src/types.ts',
      'packages/@dvt/adapter-postgres/test/smoke.test.ts',
      'packages/@dvt/adapter-postgres/tsconfig.eslint.json',
      'packages/@dvt/adapter-postgres/tsconfig.json',
      'packages/@dvt/adapter-postgres/vitest.config.ts'
    ]::text[],
    'packages/@dvt/adapter-postgres/test/smoke.test.ts',
    'unit',
    'pnpm --filter @dvt/adapter-postgres test -- smoke.test.ts',
    'Package shell has no independent runtime loop; adapter operations emit through concrete Postgres adapter leaves.'
  ),
  (
    'SYS-ADAPTERS-POSTGRES-SCHEMA-MIGRATIONS',
    'SYS-ADAPTERS-ROOT',
    'Postgres adapter schema and migration lifecycle',
    'adapter',
    'adapter',
    'PostgresSchemaMigration',
    'ApplyPostgresRuntimeStoreMigrations;ValidatePostgresSchemaRollback',
    'Owns SQL migrations, schema managers, runtime-store migration command, and zero-downtime rollback proofs.',
    'Create and validate Postgres runtime schema safely across runtime store versions.',
    'Postgres migration SQL, schema manager, rollback behavior, or runtime-store migration command changes.',
    'packages/@dvt/adapter-postgres/src/migratePostgresRuntimeStores.ts',
    'Postgres runtime-store schema migration boundary',
    'temporal_coupling',
    'ApplyPostgresRuntimeStoreMigrations',
    'command',
    'inbound',
    array[
      'packages/@dvt/adapter-postgres/test/PostgresSchemaManager.rollback.test.ts',
      'packages/@dvt/adapter-postgres/test/PostgresSchemaRollbackZeroDowntime.architecture.test.ts'
    ]::text[],
    array[
      'packages/@dvt/adapter-postgres/migrations/**',
      'packages/@dvt/adapter-postgres/src/migratePostgresRuntimeStores.ts',
      'packages/@dvt/adapter-postgres/src/PostgresSchemaManager.ts',
      'packages/@dvt/adapter-postgres/src/PostgresSchemaManagerSql.ts',
      'packages/@dvt/adapter-postgres/src/StartRunIntentSchemaManager.ts',
      'packages/@dvt/adapter-postgres/test/migratePostgresRuntimeStores.test.ts',
      'packages/@dvt/adapter-postgres/test/PostgresSchemaManager.rollback.test.ts',
      'packages/@dvt/adapter-postgres/test/PostgresSchemaRollbackZeroDowntime.architecture.test.ts',
      'packages/@dvt/adapter-postgres/test/StartRunIntentSchemaManager.test.ts'
    ]::text[],
    'packages/@dvt/adapter-postgres/test/PostgresSchemaManager.rollback.test.ts',
    'architecture',
    'pnpm --filter @dvt/adapter-postgres test -- PostgresSchemaManager.rollback.test.ts PostgresSchemaRollbackZeroDowntime.architecture.test.ts',
    'Migration lifecycle emits operational evidence through migration and rollback validation.'
  ),
  (
    'SYS-ADAPTERS-POSTGRES-SESSION-SECURITY',
    'SYS-ADAPTERS-ROOT',
    'Postgres adapter session and tenant security',
    'adapter',
    'adapter',
    'PostgresSessionTenantSecurity',
    'OpenPostgresAdapterSession;ValidatePostgresTenantIsolation',
    'Owns Postgres client session setup, connection strings, SQL utilities, tenant isolation policy, service capabilities, and RLS proof harnesses.',
    'Keep tenant-scoped Postgres access and role/session semantics behind one security adapter boundary.',
    'Connection/session handling, SQL helper semantics, tenant isolation, service access capability, or RLS proof changes.',
    'packages/@dvt/adapter-postgres/src/PostgresAdapterClientSession.ts',
    'Postgres adapter tenant-scoped session boundary',
    'hidden_authority',
    'OpenPostgresAdapterSession',
    'storage',
    'outbound',
    array[
      'packages/@dvt/adapter-postgres/test/PostgresTenantIsolationPolicy.test.ts',
      'packages/@dvt/adapter-postgres/test/PostgresTenantRlsEnforcement.integration.test.ts'
    ]::text[],
    array[
      'packages/@dvt/adapter-postgres/src/PostgresAdapterClientSession.ts',
      'packages/@dvt/adapter-postgres/src/PostgresAdapterClientSessionConstants.ts',
      'packages/@dvt/adapter-postgres/src/PostgresAdapterClientSessionSql.ts',
      'packages/@dvt/adapter-postgres/src/PostgresAdapterConnectionString.ts',
      'packages/@dvt/adapter-postgres/src/PostgresRelationalExecutionCapability.ts',
      'packages/@dvt/adapter-postgres/src/PostgresServiceAccessCapability.ts',
      'packages/@dvt/adapter-postgres/src/PostgresTenantIsolationPolicy.ts',
      'packages/@dvt/adapter-postgres/src/sqlUtils.ts',
      'packages/@dvt/adapter-postgres/test/helpers/postgresIntegrationHarness.ts',
      'packages/@dvt/adapter-postgres/test/helpers/postgresRlsProofHarness.ts',
      'packages/@dvt/adapter-postgres/test/PostgresAdapterClientSession.test.ts',
      'packages/@dvt/adapter-postgres/test/PostgresAppRoleRuntime.integration.test.ts',
      'packages/@dvt/adapter-postgres/test/PostgresServiceAccessCapability.architecture.test.ts',
      'packages/@dvt/adapter-postgres/test/PostgresTenantIsolationPolicy.test.ts',
      'packages/@dvt/adapter-postgres/test/PostgresTenantIsolationSemantic.architecture.test.ts',
      'packages/@dvt/adapter-postgres/test/PostgresTenantRlsEnforcement.integration.test.ts'
    ]::text[],
    'packages/@dvt/adapter-postgres/test/PostgresTenantIsolationPolicy.test.ts',
    'integration',
    'pnpm --filter @dvt/adapter-postgres test -- PostgresTenantIsolationPolicy.test.ts PostgresTenantRlsEnforcement.integration.test.ts',
    'Session and tenant security evidence is captured by RLS and tenant-isolation tests.'
  ),
  (
    'SYS-ADAPTERS-POSTGRES-RUN-EVENT-STORE',
    'SYS-ADAPTERS-ROOT',
    'Postgres run-event store adapter',
    'adapter',
    'adapter',
    'PostgresRunEventStore',
    'AppendRunEventsToPostgres;ReadPostgresRunEvents',
    'Owns Postgres run-event persistence, envelope policy, write repository, run-event storage SQL, and run-event fixtures.',
    'Persist, read, and validate run-event envelopes in Postgres while preserving ordering and idempotency invariants.',
    'Run-event SQL, envelope policy, event write repository, event storage behavior, or retention architecture changes.',
    'packages/@dvt/adapter-postgres/src/PostgresRunEventStore.ts',
    'Postgres run-event storage boundary',
    'event_sourcing',
    'AppendRunEventsToPostgres',
    'storage',
    'outbound',
    array[
      'packages/@dvt/adapter-postgres/test/PostgresRunEventStore.test.ts',
      'packages/@dvt/adapter-postgres/test/PostgresRunEventRetentionPolicy.architecture.test.ts'
    ]::text[],
    array[
      'packages/@dvt/adapter-postgres/src/PostgresRunEventStorage.ts',
      'packages/@dvt/adapter-postgres/src/PostgresRunEventStore.ts',
      'packages/@dvt/adapter-postgres/src/PostgresRunEventStoreSql.ts',
      'packages/@dvt/adapter-postgres/src/RunEventWriteRepository.ts',
      'packages/@dvt/adapter-postgres/src/runEventEnvelopePolicy.ts',
      'packages/@dvt/adapter-postgres/src/runEventStoreErrors.ts',
      'packages/@dvt/adapter-postgres/test/helpers/runEventFixtures.ts',
      'packages/@dvt/adapter-postgres/test/PostgresRunEventRetentionPolicy.architecture.test.ts',
      'packages/@dvt/adapter-postgres/test/PostgresRunEventStore.test.ts'
    ]::text[],
    'packages/@dvt/adapter-postgres/test/PostgresRunEventStore.test.ts',
    'unit',
    'pnpm --filter @dvt/adapter-postgres test -- PostgresRunEventStore.test.ts PostgresRunEventRetentionPolicy.architecture.test.ts',
    'Run-event adapter evidence is validated through storage and retention-policy tests.'
  ),
  (
    'SYS-ADAPTERS-POSTGRES-RUN-STATE-STORE',
    'SYS-ADAPTERS-ROOT',
    'Postgres run-state and snapshot store adapter',
    'adapter',
    'adapter',
    'PostgresRunStateStore',
    'WritePostgresRunState;ReadPostgresRunSnapshot;BridgeRunStateCommandPort',
    'Owns Postgres run-state adapters, snapshot store, run-state coordinator, start-run intent store, metadata repository, and command-port bridge.',
    'Persist run state, snapshots, command-port writes, and start-run intent data behind Postgres state-store ports.',
    'Run-state adapter, snapshot store, start-run intent store, metadata repository, or command bridge changes.',
    'packages/@dvt/adapter-postgres/src/PostgresRunStateStoreAdapter.ts',
    'Postgres run-state store boundary',
    'aggregate_lifecycle',
    'WritePostgresRunState',
    'storage',
    'outbound',
    array[
      'packages/@dvt/adapter-postgres/test/PostgresRunSnapshotStore.cas-guard.test.ts',
      'packages/@dvt/adapter-postgres/test/PostgresStateStoreAdapter.abort.test.ts'
    ]::text[],
    array[
      'packages/@dvt/adapter-postgres/src/PostgresRunMetadataRepository.ts',
      'packages/@dvt/adapter-postgres/src/PostgresRunSnapshotStore.ts',
      'packages/@dvt/adapter-postgres/src/PostgresRunStateCoordinator.ts',
      'packages/@dvt/adapter-postgres/src/PostgresRunStateCoordinatorConstants.ts',
      'packages/@dvt/adapter-postgres/src/PostgresRunStateStoreAdapter.ts',
      'packages/@dvt/adapter-postgres/src/PostgresStartRunIntentStore.ts',
      'packages/@dvt/adapter-postgres/src/PostgresStateStoreAdapter.ts',
      'packages/@dvt/adapter-postgres/src/PostgresStateStoreAdminAdapter.ts',
      'packages/@dvt/adapter-postgres/src/PostgresStateStoreRuntime.ts',
      'packages/@dvt/adapter-postgres/src/PostgresStateStoreRuntimeComposer.ts',
      'packages/@dvt/adapter-postgres/src/PostgresStateStoreRuntimeConfig.ts',
      'packages/@dvt/adapter-postgres/src/runStateCommandPortBridge.ts',
      'packages/@dvt/adapter-postgres/test/PostgresRunMetadataRepository.test.ts',
      'packages/@dvt/adapter-postgres/test/PostgresRunSnapshotStore.cas-guard.test.ts',
      'packages/@dvt/adapter-postgres/test/PostgresRunSnapshotStore.test.ts',
      'packages/@dvt/adapter-postgres/test/PostgresRunStateCoordinator.test.ts',
      'packages/@dvt/adapter-postgres/test/PostgresStartRunIntentStore.context.test.ts',
      'packages/@dvt/adapter-postgres/test/PostgresStartRunIntentStore.test.ts',
      'packages/@dvt/adapter-postgres/test/PostgresStateStoreAdapter.abort.test.ts',
      'packages/@dvt/adapter-postgres/test/PostgresStateStoreAdapter.migrate.test.ts',
      'packages/@dvt/adapter-postgres/test/PostgresStateStoreAdapter.sharding.test.ts',
      'packages/@dvt/adapter-postgres/test/PostgresStateTransitions.integration.test.ts',
      'packages/@dvt/adapter-postgres/test/PostgresTransformationStepActivities.test.ts',
      'packages/@dvt/adapter-postgres/test/RunDomainStateTransitions.contract.test.ts',
      'packages/@dvt/adapter-postgres/test/runStateCommandPortBridge.test.ts'
    ]::text[],
    'packages/@dvt/adapter-postgres/test/PostgresRunStateCoordinator.test.ts',
    'integration',
    'pnpm --filter @dvt/adapter-postgres test -- PostgresRunStateCoordinator.test.ts PostgresStateStoreAdapter.abort.test.ts PostgresRunSnapshotStore.cas-guard.test.ts',
    'Run-state adapter evidence is captured by state, snapshot, and command-port bridge tests.'
  ),
  (
    'SYS-ADAPTERS-POSTGRES-OUTBOX-MAINTENANCE',
    'SYS-ADAPTERS-ROOT',
    'Postgres outbox, archive, and maintenance adapters',
    'adapter',
    'adapter',
    'PostgresOutboxMaintenance',
    'ClaimPostgresOutboxWork;ReadPostgresSnapshotStaleness;PurgePostgresDeliveryBuffer',
    'Owns Postgres outbox, lineage outbox, archive lease, run archive, delivery-buffer purge, backpressure, snapshot queue, and maintenance access adapters.',
    'Coordinate asynchronous Postgres maintenance, outbox delivery, lineage retries, archive retention, and snapshot staleness reads.',
    'Outbox SQL, lineage retry behavior, archive retention, maintenance access, snapshot queue, or staleness query changes.',
    'packages/@dvt/adapter-postgres/src/PostgresOutboxStore.ts',
    'Postgres outbox and maintenance boundary',
    'event_driven_boundary',
    'ClaimPostgresOutboxWork',
    'storage',
    'outbound',
    array[
      'packages/@dvt/adapter-postgres/test/PostgresLineageOutboxStore.dead-letter.test.ts',
      'packages/@dvt/adapter-postgres/test/PostgresSnapshotStalenessQuery.test.ts'
    ]::text[],
    array[
      'packages/@dvt/adapter-postgres/src/lineageOutboxStorePolicy.ts',
      'packages/@dvt/adapter-postgres/src/PostgresArchiveLeaseStore.ts',
      'packages/@dvt/adapter-postgres/src/PostgresBackpressureSnapshotReader.ts',
      'packages/@dvt/adapter-postgres/src/PostgresBackpressureSnapshotReaderSql.ts',
      'packages/@dvt/adapter-postgres/src/PostgresDeliveryBufferPurgeStore.ts',
      'packages/@dvt/adapter-postgres/src/PostgresLineageOutboxStore.ts',
      'packages/@dvt/adapter-postgres/src/PostgresLineageOutboxStoreSql.ts',
      'packages/@dvt/adapter-postgres/src/PostgresMaintenanceAccess.ts',
      'packages/@dvt/adapter-postgres/src/PostgresOutboxStore.ts',
      'packages/@dvt/adapter-postgres/src/PostgresRunArchiveStore.ts',
      'packages/@dvt/adapter-postgres/src/PostgresSnapshotQueueAdapter.ts',
      'packages/@dvt/adapter-postgres/src/PostgresSnapshotStalenessQuery.ts',
      'packages/@dvt/adapter-postgres/src/PostgresSnapshotStalenessQuerySql.ts',
      'packages/@dvt/adapter-postgres/src/PostgresSnapshotWorkQueue.ts',
      'packages/@dvt/adapter-postgres/test/helpers/lineageOutboxIntegrationHarness.ts',
      'packages/@dvt/adapter-postgres/test/helpers/lineageOutboxUnitSupport.ts',
      'packages/@dvt/adapter-postgres/test/PostgresBackpressureSnapshotReader.test.ts',
      'packages/@dvt/adapter-postgres/test/PostgresLineageOutboxStore.dead-letter.test.ts',
      'packages/@dvt/adapter-postgres/test/PostgresLineageOutboxStore.failures.test.ts',
      'packages/@dvt/adapter-postgres/test/PostgresLineageOutboxStore.integration.test.ts',
      'packages/@dvt/adapter-postgres/test/PostgresLineageOutboxStore.pending.test.ts',
      'packages/@dvt/adapter-postgres/test/PostgresOutboxStore.test.ts',
      'packages/@dvt/adapter-postgres/test/PostgresRunArchiveStore.tenant-retention.integration.test.ts',
      'packages/@dvt/adapter-postgres/test/PostgresRunArchiveStore.tenant-retention.test.ts',
      'packages/@dvt/adapter-postgres/test/PostgresSnapshotStalenessQuery.test.ts',
      'packages/@dvt/adapter-postgres/test/S19F1SnapshotWorkQueueClosure.integration.test.ts'
    ]::text[],
    'packages/@dvt/adapter-postgres/test/PostgresOutboxStore.test.ts',
    'integration',
    'pnpm --filter @dvt/adapter-postgres test -- PostgresOutboxStore.test.ts PostgresLineageOutboxStore.dead-letter.test.ts PostgresSnapshotStalenessQuery.test.ts',
    'Outbox and maintenance adapters expose metrics through their store tests and lineage failure scenarios.'
  ),
  (
    'SYS-ADAPTERS-TEMPORAL-PACKAGE-SHELL',
    'SYS-ADAPTERS-ROOT',
    'Temporal adapter package shell',
    'package',
    'adapter',
    'TemporalAdapterPackageShell',
    'ImportTemporalAdapterPackage;ValidateTemporalAdapterPackageSurface',
    'Owns Temporal adapter package metadata, root exports, config, versioning, package scripts, and smoke proof.',
    'Expose the Temporal adapter package surface without owning activities, workflows, plugins, or client semantics.',
    'Temporal adapter exports, package config, runtime config, versioning, or package smoke behavior changes.',
    'packages/@dvt/adapter-temporal/src/index.ts',
    'Temporal adapter package export boundary',
    'published_language',
    'ImportTemporalAdapterPackage',
    'api',
    'inbound',
    array['packages/@dvt/adapter-temporal/test/smoke.test.ts']::text[],
    array[
      'packages/@dvt/adapter-temporal/package.json',
      'packages/@dvt/adapter-temporal/scripts/run-postgres-integration.cjs',
      'packages/@dvt/adapter-temporal/src/config.ts',
      'packages/@dvt/adapter-temporal/src/engine-types.ts',
      'packages/@dvt/adapter-temporal/src/index.ts',
      'packages/@dvt/adapter-temporal/src/versioning.ts',
      'packages/@dvt/adapter-temporal/test/smoke.test.ts',
      'packages/@dvt/adapter-temporal/tsconfig.eslint.json',
      'packages/@dvt/adapter-temporal/tsconfig.json',
      'packages/@dvt/adapter-temporal/tsconfig.test.json',
      'packages/@dvt/adapter-temporal/vitest.config.ts'
    ]::text[],
    'packages/@dvt/adapter-temporal/test/smoke.test.ts',
    'unit',
    'pnpm --filter @dvt/adapter-temporal test -- smoke.test.ts',
    'Package shell has no independent runtime loop; Temporal client and worker leaves own runtime telemetry.'
  ),
  (
    'SYS-ADAPTERS-TEMPORAL-ACTIVITIES',
    'SYS-ADAPTERS-ROOT',
    'Temporal adapter activity dispatch',
    'adapter',
    'adapter',
    'TemporalActivityDispatch',
    'DispatchTemporalStepActivity;ValidateTemporalActivityInput',
    'Owns Temporal activity factory, activity failure mapping, activity types, gateway step activity, step dispatcher, and activity validation.',
    'Dispatch and validate workflow activities behind the Temporal worker activity boundary.',
    'Temporal activity factory, dispatch routing, validation, failure policy, or activity test changes.',
    'packages/@dvt/adapter-temporal/src/activities/stepActivityDispatcher.ts',
    'Temporal activity dispatch boundary',
    'workflow_activity_boundary',
    'DispatchTemporalStepActivity',
    'command',
    'inbound',
    array[
      'packages/@dvt/adapter-temporal/test/activities.test.ts',
      'packages/@dvt/adapter-temporal/test/activityDeps.typecheck.ts'
    ]::text[],
    array[
      'packages/@dvt/adapter-temporal/src/activities/**',
      'packages/@dvt/adapter-temporal/test/activities.test.ts',
      'packages/@dvt/adapter-temporal/test/activityDeps.typecheck.ts',
      'packages/@dvt/adapter-temporal/test/dbtRuntimeFixtures.test.ts',
      'packages/@dvt/adapter-temporal/test/helpers/integration/dbtRuntimeFixtures.ts',
      'packages/@dvt/adapter-temporal/test/helpers/integration/testActivities.ts'
    ]::text[],
    'packages/@dvt/adapter-temporal/test/activities.test.ts',
    'unit',
    'pnpm --filter @dvt/adapter-temporal test -- activities.test.ts activityDeps.typecheck.ts',
    'Activity execution evidence is validated through activity unit and dependency typecheck tests.'
  ),
  (
    'SYS-ADAPTERS-TEMPORAL-CLIENT-ADAPTER',
    'SYS-ADAPTERS-ROOT',
    'Temporal adapter client and worker host',
    'adapter',
    'adapter',
    'TemporalClientAdapter',
    'StartTemporalRun;SignalTemporalRun;ReadTemporalProviderStatus',
    'Owns Temporal adapter/client facade, observed adapter wrapper, policy mapper, error policy, worker host, observability binding, and run-state command circuit breaker.',
    'Translate DVT runtime commands and provider status reads into Temporal client and worker-host operations.',
    'Temporal adapter facade, client behavior, policy mapping, worker lifecycle, observability wrapper, or circuit breaker changes.',
    'packages/@dvt/adapter-temporal/src/TemporalAdapter.ts',
    'Temporal adapter client boundary',
    'anti_corruption_layer',
    'StartTemporalRun',
    'command',
    'outbound',
    array[
      'packages/@dvt/adapter-temporal/test/TemporalAdapter.control.test.ts',
      'packages/@dvt/adapter-temporal/test/RunStateCommandPortCircuitBreaker.test.ts'
    ]::text[],
    array[
      'packages/@dvt/adapter-temporal/src/ObservedTemporalAdapter.ts',
      'packages/@dvt/adapter-temporal/src/RunStateCommandPortCircuitBreaker.ts',
      'packages/@dvt/adapter-temporal/src/TemporalAdapter.ts',
      'packages/@dvt/adapter-temporal/src/TemporalClient.ts',
      'packages/@dvt/adapter-temporal/src/temporalErrorPolicy.ts',
      'packages/@dvt/adapter-temporal/src/temporalObservability.ts',
      'packages/@dvt/adapter-temporal/src/TemporalPolicyMapper.ts',
      'packages/@dvt/adapter-temporal/src/TemporalWorkerHost.ts',
      'packages/@dvt/adapter-temporal/test/helpers/mockObservability.ts',
      'packages/@dvt/adapter-temporal/test/ObservedTemporalAdapter.test.ts',
      'packages/@dvt/adapter-temporal/test/RunStateCommandPortCircuitBreaker.test.ts',
      'packages/@dvt/adapter-temporal/test/TemporalAdapter.control.test.ts',
      'packages/@dvt/adapter-temporal/test/TemporalAdapter.getProviderStatusView.test.ts',
      'packages/@dvt/adapter-temporal/test/TemporalAdapter.lookupRunRef.test.ts',
      'packages/@dvt/adapter-temporal/test/TemporalAdapter.startRun.test.ts',
      'packages/@dvt/adapter-temporal/test/temporalErrorPolicy.test.ts',
      'packages/@dvt/adapter-temporal/test/TemporalPolicyMapper.test.ts',
      'packages/@dvt/adapter-temporal/test/TemporalWorkerHost.lifecycle.test.ts',
      'packages/@dvt/adapter-temporal/test/worker-scaling-strategy.architecture.test.ts'
    ]::text[],
    'packages/@dvt/adapter-temporal/test/TemporalAdapter.startRun.test.ts',
    'unit',
    'pnpm --filter @dvt/adapter-temporal test -- TemporalAdapter.startRun.test.ts TemporalAdapter.control.test.ts TemporalWorkerHost.lifecycle.test.ts',
    'Temporal client and worker host telemetry is validated through observed adapter and worker lifecycle tests.'
  ),
  (
    'SYS-ADAPTERS-TEMPORAL-WORKFLOW-RUNTIME',
    'SYS-ADAPTERS-ROOT',
    'Temporal run-plan workflow runtime',
    'workflow',
    'adapter',
    'TemporalRunPlanWorkflow',
    'ExecuteTemporalRunPlanWorkflow;SignalTemporalRunPlanWorkflow;ContinueTemporalRunPlanWorkflow',
    'Owns Temporal workflow runtime, workflow helpers, cancellation, signals, state, layer execution, cursor helpers, and integration fixtures.',
    'Execute DVT run plans inside Temporal workflows while preserving lifecycle, cancellation, signal, retry, and continue-as-new semantics.',
    'Workflow runtime, workflow helper, signal/cancellation, execution segment, retry, compiled-code ref, or time-skipping integration changes.',
    'packages/@dvt/adapter-temporal/src/workflows/RunPlanWorkflow.ts',
    'Temporal run-plan workflow boundary',
    'workflow_orchestration',
    'ExecuteTemporalRunPlanWorkflow',
    'command',
    'inbound',
    array[
      'packages/@dvt/adapter-temporal/test/runPlanWorkflow.cancellation.test.ts',
      'packages/@dvt/adapter-temporal/test/workflow-retry-policy.test.ts'
    ]::text[],
    array[
      'packages/@dvt/adapter-temporal/src/workflows/**',
      'packages/@dvt/adapter-temporal/test/helpers/contractFixtures.ts',
      'packages/@dvt/adapter-temporal/test/helpers/integration/runtimeState.ts',
      'packages/@dvt/adapter-temporal/test/helpers/integration/testPlans.ts',
      'packages/@dvt/adapter-temporal/test/helpers/integration/waitForCondition.ts',
      'packages/@dvt/adapter-temporal/test/helpers/integration/workflowArtifacts.ts',
      'packages/@dvt/adapter-temporal/test/helpers/lookupRunRefHarness.ts',
      'packages/@dvt/adapter-temporal/test/helpers/workflowComponentGuideSupport.ts',
      'packages/@dvt/adapter-temporal/test/integration.postgres.time-skipping.test.ts',
      'packages/@dvt/adapter-temporal/test/integration.time-skipping.shared.ts',
      'packages/@dvt/adapter-temporal/test/integration.time-skipping.test.ts',
      'packages/@dvt/adapter-temporal/test/integration.transformation.time-skipping.test.ts',
      'packages/@dvt/adapter-temporal/test/runPlanWorkflow.cancellation.test.ts',
      'packages/@dvt/adapter-temporal/test/runPlanWorkflow.layers.order.test.ts',
      'packages/@dvt/adapter-temporal/test/runPlanWorkflow.signals.test.ts',
      'packages/@dvt/adapter-temporal/test/workflow-compiled-code-ref.test.ts',
      'packages/@dvt/adapter-temporal/test/workflow-continue-as-new.test.ts',
      'packages/@dvt/adapter-temporal/test/workflow-dag-scheduler.test.ts',
      'packages/@dvt/adapter-temporal/test/workflow-execution-segment.test.ts',
      'packages/@dvt/adapter-temporal/test/workflow-literals.test.ts',
      'packages/@dvt/adapter-temporal/test/workflowMapper.typecheck.ts',
      'packages/@dvt/adapter-temporal/test/workflow-retry-policy.test.ts',
      'packages/@dvt/adapter-temporal/test/workflowRuntimePayloadHelpers.test.ts',
      'packages/@dvt/adapter-temporal/test/workflow-step-activity-routing.test.ts'
    ]::text[],
    'packages/@dvt/adapter-temporal/test/runPlanWorkflow.cancellation.test.ts',
    'integration',
    'pnpm --filter @dvt/adapter-temporal test -- runPlanWorkflow.cancellation.test.ts workflow-retry-policy.test.ts workflowRuntimePayloadHelpers.test.ts',
    'Workflow runtime evidence is validated by workflow, signal, retry, and time-skipping integration tests.'
  ),
  (
    'SYS-ADAPTERS-TEMPORAL-PLUGIN-RUNNER',
    'SYS-ADAPTERS-ROOT',
    'Temporal step plugin runner',
    'adapter',
    'adapter',
    'TemporalStepPluginRunner',
    'RunTemporalStepPlugin;ValidateTemporalStepPluginProfile',
    'Owns Temporal step plugin profile and runner plus plugin extraction and decoupling architecture proofs.',
    'Run step plugins inside Temporal without coupling workflow code to dbt package internals.',
    'Temporal plugin profile, plugin runner, dbt decoupling, test executor, or plugin extraction architecture changes.',
    'packages/@dvt/adapter-temporal/src/plugins/TemporalStepPluginRunner.ts',
    'Temporal step plugin runner boundary',
    'plugin_boundary',
    'RunTemporalStepPlugin',
    'command',
    'inbound',
    array[
      'packages/@dvt/adapter-temporal/test/dbt-core-decoupling.architecture.test.ts',
      'packages/@dvt/adapter-temporal/test/dbt-package-extraction.architecture.test.ts'
    ]::text[],
    array[
      'packages/@dvt/adapter-temporal/src/plugins/**',
      'packages/@dvt/adapter-temporal/test/dbt-core-decoupling.architecture.test.ts',
      'packages/@dvt/adapter-temporal/test/dbt-package-extraction.architecture.test.ts',
      'packages/@dvt/adapter-temporal/test/helpers/testExecutors.ts'
    ]::text[],
    'packages/@dvt/adapter-temporal/test/dbt-core-decoupling.architecture.test.ts',
    'architecture',
    'pnpm --filter @dvt/adapter-temporal test -- dbt-core-decoupling.architecture.test.ts dbt-package-extraction.architecture.test.ts',
    'Plugin runner evidence is validated by dbt decoupling and package-extraction architecture tests.'
  );

insert into planning_query_store.governance_component_local_definitions (
  component_id,
  source_path,
  source_content_sha256,
  revision,
  name,
  level,
  parent_id,
  root_unit,
  domain_unit,
  status,
  children_required,
  owned_concern,
  ddd_owner,
  cq_rails,
  created_by
)
select
  component_id,
  'planning_query_store.governance_component_local_definitions',
  repeat('a', 64),
  0,
  name,
  'component',
  parent_id,
  'SYS-DVT',
  'SYS-ADAPTERS',
  'review',
  false,
  owned_concern,
  ddd_owner,
  cq_rails,
  'codex'
from adapter_leaf_map
on conflict (component_id) do update set
  source_path = excluded.source_path,
  source_content_sha256 = excluded.source_content_sha256,
  name = excluded.name,
  level = excluded.level,
  parent_id = excluded.parent_id,
  root_unit = excluded.root_unit,
  domain_unit = excluded.domain_unit,
  status = excluded.status,
  children_required = excluded.children_required,
  owned_concern = excluded.owned_concern,
  ddd_owner = excluded.ddd_owner,
  cq_rails = excluded.cq_rails;

insert into planning_query_store.governance_component_local_ownership_patterns (
  component_id,
  pattern_kind,
  pattern,
  pattern_order
)
select
  component_id,
  'owns',
  ownership.pattern,
  ownership.pattern_order - 1
from adapter_leaf_map
cross join lateral unnest(owns) with ordinality as ownership(pattern, pattern_order)
on conflict (component_id, pattern_kind, pattern) do update set
  pattern_order = excluded.pattern_order;

insert into planning_query_store.governance_component_local_semantic_items (
  component_id,
  item_kind,
  item_value,
  item_order
)
select
  item.component_id,
  item.item_kind,
  item.item_value,
  item.item_order
from (
  select component_id, 'responsibility' as item_kind, responsibility as item_value, 0 as item_order
  from adapter_leaf_map
  union all
  select component_id, 'reason_to_change', reason_to_change, 0
  from adapter_leaf_map
  union all
  select
    component_id,
    'invariant',
    'Files claimed by this adapter leaf must not fall through to SYS-ADAPTERS-ROOT.',
    0
  from adapter_leaf_map
  union all
  select
    component_id,
    'transition',
    'review -> implemented after component-quality shows no direct adapter package files owned by SYS-ADAPTERS-ROOT and adapter package tests remain green.',
    0
  from adapter_leaf_map
  union all
  select
    component_id,
    'consumer',
    'DVT runtime engine, workers, API runtime composition, and adapter package tests',
    0
  from adapter_leaf_map
  union all
  select
    component_id,
    'governance_ref',
    'docs/architecture/command-query-rail-governance.md',
    0
  from adapter_leaf_map
  union all
  select
    component_id,
    'governance_ref',
    'docs/planning/proposals/mandatory/governance-and-docs/planning-db-component-integrity-vocabulary-rail-plan-20260612.md',
    1
  from adapter_leaf_map
  union all
  select component_id, 'fowler_signal', fowler_signal, 0
  from adapter_leaf_map
  union all
  select component_id, 'public_api', port_name, 0
  from adapter_leaf_map
) item
on conflict (component_id, item_kind, item_value) do update set
  item_order = excluded.item_order;

create temporary table architecture_authority_seed (
  component_id text primary key,
  name text not null,
  parent_component_id text,
  kind text not null,
  layer text not null,
  owner text not null,
  repo_path text not null,
  public_contract text not null,
  runtime text not null,
  criticality text not null,
  status text not null,
  port_name text not null,
  port_kind text not null,
  port_direction text not null,
  test_path text not null,
  test_kind text not null,
  validation_command text not null,
  responsibility text not null,
  reason_to_change text not null,
  observability_signal text not null,
  negative_tests text[] not null
);

insert into architecture_authority_seed (
  component_id,
  name,
  parent_component_id,
  kind,
  layer,
  owner,
  repo_path,
  public_contract,
  runtime,
  criticality,
  status,
  port_name,
  port_kind,
  port_direction,
  test_path,
  test_kind,
  validation_command,
  responsibility,
  reason_to_change,
  observability_signal,
  negative_tests
)
values
  (
    'SYS-API-ROOT',
    'API root module',
    null,
    'api',
    'application',
    'Architecture / API',
    'apps/api',
    'API package root, HTTP application, protected runtime routes, app bootstrap, and API test harness.',
    'node',
    'high',
    'review',
    'ServeApiRuntime',
    'api',
    'inbound',
    'apps/api/test/server.test.ts',
    'integration',
    'pnpm --filter @dvt/api test -- server.test.ts',
    'Own the API bounded context root and contain API ports, services, HTTP entrypoints, infrastructure, docs, and tests.',
    'API package structure, app composition, route surface, or API bounded-context ownership changes.',
    'API root observability is provided through app, route, and runtime composition tests rather than an independent component loop.',
    array['apps/api/test/server.test.ts']::text[]
  ),
  (
    'SYS-RUNTIME-ROOT',
    'Runtime root module',
    null,
    'module',
    'application',
    'Architecture / Runtime',
    'packages/@dvt',
    'Runtime package family root for engine, state-store, delivery, DSL, canonical utilities, plan interpretation, and plan verification.',
    'node',
    'critical',
    'review',
    'ExecuteRuntimeLifecycle',
    'command',
    'inbound',
    'packages/@dvt/engine/test/architecture/workflowEngineSemanticClosure.architecture.test.ts',
    'architecture',
    'pnpm --filter @dvt/engine test -- workflowEngineSemanticClosure.architecture.test.ts',
    'Own the runtime bounded context root and contain runtime packages, engine core, state-store lifecycle, delivery projections, and runtime verification utilities.',
    'Runtime package family boundaries, lifecycle semantics, or runtime ownership model changes.',
    'Runtime root observability is validated through engine observability and runtime package architecture tests.',
    array['packages/@dvt/engine/test/architecture/workflowEngineSemanticClosure.architecture.test.ts']::text[]
  ),
  (
    'SYS-ADAPTERS-ROOT',
    'Adapter packages root component',
    null,
    'package',
    'adapter',
    'Architecture / Adapters',
    'packages/@dvt/adapter-postgres',
    'Adapter package family root for Postgres and Temporal integration adapters.',
    'node',
    'high',
    'review',
    'MapAdapterPackageComponents',
    'api',
    'inbound',
    'packages/@dvt/adapter-postgres/test/smoke.test.ts',
    'unit',
    'pnpm --filter @dvt/adapter-postgres test -- smoke.test.ts',
    'Own the adapter package family as a composite root and delegate concrete files to Postgres and Temporal adapter leaves.',
    'Adapter package family structure, adapter ownership, or root package mapping changes.',
    'Adapter root has no independent runtime loop; concrete adapter leaves own runtime telemetry.',
    array['packages/@dvt/adapter-postgres/test/smoke.test.ts']::text[]
  ),
  (
    'SYS-RUNTIME-ARCHITECTURE-DOCS',
    'Runtime subsystem architecture documentation',
    'SYS-RUNTIME-ROOT',
    'module',
    'infra',
    'Architecture / Runtime Docs',
    'docs/architecture/system/subsystems/runtime/runtime-root-subdivision-component.md',
    'Deprecated runtime-doc component alias; docs ownership is canonical under documentation governance components.',
    'none',
    'low',
    'deprecated',
    'ReadRuntimeArchitectureDocsViaDocsGovernance',
    'query',
    'inbound',
    'docs/architecture/system/subsystems/runtime/runtime-root-subdivision-component.md',
    'architecture',
    'pnpm ci:docs',
    'Retain an explicit deprecated authority row for the previous runtime docs component so queries explain why it no longer owns files.',
    'Only changes when the deprecated runtime docs alias is retired from imported governance projections.',
    'Deprecated component has no runtime observability requirement.',
    array['docs/architecture/system/subsystems/runtime/runtime-root-subdivision-component.md']::text[]
  );

insert into architecture_authority_seed (
  component_id,
  name,
  parent_component_id,
  kind,
  layer,
  owner,
  repo_path,
  public_contract,
  runtime,
  criticality,
  status,
  port_name,
  port_kind,
  port_direction,
  test_path,
  test_kind,
  validation_command,
  responsibility,
  reason_to_change,
  observability_signal,
  negative_tests
)
select
  component_id,
  name,
  parent_id,
  kind,
  layer,
  'Architecture / Adapters',
  repo_path,
  public_contract,
  'node',
  'high',
  'review',
  port_name,
  port_kind,
  port_direction,
  test_path,
  test_kind,
  validation_command,
  responsibility,
  reason_to_change,
  observability_signal,
  negative_tests
from adapter_leaf_map;

insert into architecture_authority_seed (
  component_id,
  name,
  parent_component_id,
  kind,
  layer,
  owner,
  repo_path,
  public_contract,
  runtime,
  criticality,
  status,
  port_name,
  port_kind,
  port_direction,
  test_path,
  test_kind,
  validation_command,
  responsibility,
  reason_to_change,
  observability_signal,
  negative_tests
)
values
  (
    'SYS-API-APPLICATION-PORTS',
    'API application ports',
    'SYS-API-ROOT',
    'port',
    'application',
    'Architecture / API',
    'apps/api/src/application/ports/accessDecisionActions.ts',
    'API application port contracts for access decisions, command scopes, run status, and workspace capabilities.',
    'node',
    'high',
    'review',
    'AuthorizeApiAccessDecision',
    'command',
    'inbound',
    'apps/api/test/application/ports/accessDecision.test.ts',
    'unit',
    'pnpm --filter @dvt/api test -- accessDecision.test.ts',
    'Own API application ports that separate HTTP adapters from application services and runtime dependencies.',
    'API port signatures, authorization port contracts, or application boundary semantics change.',
    'API application ports have no independent runtime loop; callers own telemetry.',
    array['apps/api/test/application/ports/accessDecision.test.ts']::text[]
  ),
  (
    'SYS-API-APPLICATION-SERVICES',
    'API application services and use cases',
    'SYS-API-ROOT',
    'service',
    'application',
    'Architecture / API',
    'apps/api/src/application/services/authorizeCommandScopeService.ts',
    'API use cases for plan compilation/import, run command execution, run reads, workspace graph drafts, and start-run authorization.',
    'node',
    'high',
    'review',
    'ExecuteApiUseCase',
    'command',
    'inbound',
    'apps/api/test/application/services/startRunApplicationComponent.architecture.test.ts',
    'architecture',
    'pnpm --filter @dvt/api test -- startRunApplicationComponent.architecture.test.ts',
    'Own API application use cases and orchestration services behind HTTP entrypoints and application ports.',
    'API use-case orchestration, authorization, plan/run behavior, or workspace graph service changes.',
    'API service telemetry is validated by start-run admission and application service architecture tests.',
    array['apps/api/test/application/services/startRunApplicationComponent.architecture.test.ts']::text[]
  ),
  (
    'SYS-API-BOOTSTRAP',
    'API bootstrap and composition entry',
    'SYS-API-ROOT',
    'api',
    'application',
    'Architecture / API',
    'apps/api/src/app.ts',
    'API app and server bootstrap entrypoint.',
    'node',
    'high',
    'review',
    'BootstrapApiApp',
    'command',
    'inbound',
    'apps/api/test/app.test.ts',
    'integration',
    'pnpm --filter @dvt/api test -- app.test.ts server.test.ts',
    'Own API app and server bootstrap wiring.',
    'Express/Fastify app bootstrap, server lifecycle, or top-level API composition changes.',
    'API bootstrap telemetry is validated by app and server tests.',
    array['apps/api/test/app.test.ts']::text[]
  ),
  (
    'SYS-API-DOCS',
    'API local documentation',
    'SYS-API-ROOT',
    'module',
    'infra',
    'Architecture / API Docs',
    'apps/api/docs/start-run-application-component.md',
    'API component-level local documentation sources.',
    'none',
    'medium',
    'review',
    'ReadApiComponentDocs',
    'query',
    'inbound',
    'apps/api/docs/start-run-application-component.md',
    'architecture',
    'pnpm ci:docs',
    'Own API local component documentation and keep it linked to API implementation components.',
    'API local documentation, component guide, or docs-to-code mapping changes.',
    'Documentation component has no runtime observability requirement.',
    array['apps/api/docs/start-run-application-component.md']::text[]
  ),
  (
    'SYS-API-DOMAIN-AUTH',
    'API domain auth model',
    'SYS-API-ROOT',
    'module',
    'domain',
    'Architecture / API',
    'apps/api/src/domain/auth/types.ts',
    'API auth domain types and access vocabulary.',
    'node',
    'high',
    'review',
    'ReadApiAuthDomainTypes',
    'query',
    'inbound',
    'apps/api/test/application/services/authorizeCommandScopeService.test.ts',
    'unit',
    'pnpm --filter @dvt/api test -- authorizeCommandScopeService.test.ts',
    'Own API domain auth vocabulary consumed by application authorization services and HTTP scopes.',
    'API auth domain type or access decision vocabulary changes.',
    'Auth domain model has no independent runtime loop; authorization service tests validate behavior.',
    array['apps/api/test/application/services/authorizeCommandScopeService.test.ts']::text[]
  ),
  (
    'SYS-API-HTTP-ENTRYPOINTS',
    'API HTTP entrypoints and route mappers',
    'SYS-API-ROOT',
    'api',
    'adapter',
    'Architecture / API',
    'apps/api/src/entrypoints/http/adminRoutes.ts',
    'HTTP route parsing, request resolution, response mapping, error mapping, protected runtime routes, and scope guards.',
    'node',
    'high',
    'review',
    'HandleApiHttpRequest',
    'api',
    'inbound',
    'apps/api/test/entrypoints/http/planRouteHardCutSemantic.architecture.test.ts',
    'architecture',
    'pnpm --filter @dvt/api test -- planRouteHardCutSemantic.architecture.test.ts',
    'Own API HTTP adapters and route mappers that translate external requests into API application commands and queries.',
    'HTTP route, parser, mapper, route group, authorization header, or HTTP error translation changes.',
    'HTTP entrypoint telemetry is validated by route and protected runtime route tests.',
    array['apps/api/test/entrypoints/http/planRouteHardCutSemantic.architecture.test.ts']::text[]
  ),
  (
    'SYS-API-HTTP-ENTRYPOINT-TESTS',
    'API HTTP entrypoint tests',
    'SYS-API-ROOT',
    'module',
    'infra',
    'Architecture / API Tests',
    'apps/api/test/entrypoints/http/adminRoutes.test.ts',
    'API HTTP route and parser test suite.',
    'none',
    'medium',
    'review',
    'ValidateApiHttpEntrypoints',
    'query',
    'inbound',
    'apps/api/test/entrypoints/http/adminRoutes.test.ts',
    'unit',
    'pnpm --filter @dvt/api test -- adminRoutes.test.ts',
    'Own HTTP entrypoint test files and keep them mapped as validation evidence, not production API behavior.',
    'API HTTP test organization, route test harness, or parser fixture changes.',
    'Test component has no runtime observability requirement.',
    array['apps/api/test/entrypoints/http/adminRoutes.test.ts']::text[]
  ),
  (
    'SYS-API-INFRASTRUCTURE',
    'API infrastructure adapters',
    'SYS-API-ROOT',
    'adapter',
    'adapter',
    'Architecture / API',
    'apps/api/src/db/pool.ts',
    'API infrastructure adapters for persistence, runtime modules, auth tokens, warehouse sources, and external runtime dependencies.',
    'node',
    'high',
    'review',
    'OpenApiInfrastructureAdapter',
    'storage',
    'outbound',
    'apps/api/test/infrastructure/backpressure/RawSqlBackpressureStore.test.ts',
    'unit',
    'pnpm --filter @dvt/api test -- RawSqlBackpressureStore.test.ts',
    'Own API infrastructure adapters that satisfy application ports and runtime dependency builders.',
    'API infrastructure adapter, database pool, warehouse source, token provider, or external dependency wiring changes.',
    'API infrastructure telemetry is validated by infrastructure and protected runtime composition tests.',
    array['apps/api/test/infrastructure/backpressure/RawSqlBackpressureStore.test.ts']::text[]
  ),
  (
    'SYS-API-OPS-ROUTES',
    'API operational health routes',
    'SYS-API-ROOT',
    'api',
    'adapter',
    'Architecture / API',
    'apps/api/src/routes/capabilities.ts',
    'API operational readiness, health, and capability routes.',
    'node',
    'medium',
    'review',
    'ReadApiOperationalHealth',
    'query',
    'inbound',
    'apps/api/test/app/healthReadiness.test.ts',
    'integration',
    'pnpm --filter @dvt/api test -- healthReadiness.test.ts',
    'Own API operational health and capability route surfaces.',
    'Health, readiness, capability, or operational route behavior changes.',
    'Operational route telemetry is validated by health readiness tests.',
    array['apps/api/test/app/healthReadiness.test.ts']::text[]
  ),
  (
    'SYS-API-REPO-CONFIG',
    'API repository configuration and app metadata',
    'SYS-API-ROOT',
    'package',
    'infra',
    'Architecture / API',
    'apps/api/package.json',
    'API package configuration, dependency cruiser config, TypeScript configs, and Vitest configs.',
    'none',
    'medium',
    'review',
    'ValidateApiPackageConfiguration',
    'query',
    'inbound',
    'apps/api/package.json',
    'unit',
    'pnpm --filter @dvt/api typecheck',
    'Own API repository configuration and package-level metadata.',
    'API package config, dependency cruiser rule, TypeScript config, or Vitest config changes.',
    'Repository config component has no runtime observability requirement.',
    array['apps/api/package.json']::text[]
  ),
  (
    'SYS-API-RUNTIME-COMPOSITION',
    'API runtime composition modules',
    'SYS-API-ROOT',
    'service',
    'application',
    'Architecture / API',
    'apps/api/src/modules/buildProtectedRuntimeModule.ts',
    'Protected runtime module composition and runtime dependency builders.',
    'node',
    'high',
    'review',
    'ComposeProtectedRuntimeModule',
    'command',
    'inbound',
    'apps/api/test/app/protectedRuntimeComposition.test.ts',
    'integration',
    'pnpm --filter @dvt/api test -- protectedRuntimeComposition.test.ts',
    'Own API runtime composition modules that wire protected runtime dependencies and adapters.',
    'Protected runtime module, dependency builder, runtime app composition, or module boundary changes.',
    'Runtime composition telemetry is validated by protected runtime composition tests.',
    array['apps/api/test/app/protectedRuntimeComposition.test.ts']::text[]
  ),
  (
    'SYS-API-TESTS',
    'API app, integration, module, infrastructure, and fixture tests',
    'SYS-API-ROOT',
    'module',
    'infra',
    'Architecture / API Tests',
    'apps/api/test/app/appEnvTestSupport.ts',
    'API test harness, fixtures, app tests, integration tests, and architecture proof tests.',
    'none',
    'medium',
    'review',
    'ValidateApiBehavior',
    'query',
    'inbound',
    'apps/api/test/modules.test.ts',
    'unit',
    'pnpm --filter @dvt/api test -- modules.test.ts',
    'Own API test support and cross-cutting validation files as evidence components.',
    'API test harness, fixture, integration proof, or module test organization changes.',
    'Test component has no runtime observability requirement.',
    array['apps/api/test/modules.test.ts']::text[]
  ),
  (
    'SYS-RUNTIME-CLI-VALIDATION',
    'Runtime CLI validation surfaces',
    'SYS-RUNTIME-ROOT',
    'api',
    'adapter',
    'Architecture / Runtime',
    'packages/cli/validate-contracts.cjs',
    'Runtime CLI validation entrypoints for contract and golden-result checks.',
    'node',
    'medium',
    'review',
    'RunRuntimeCliValidation',
    'command',
    'inbound',
    'packages/@dvt/cli/test/smoke.test.ts',
    'unit',
    'pnpm --filter @dvt/cli test',
    'Own runtime CLI validation surfaces and connect duplicated CLI packages to one validation component.',
    'Runtime validation CLI, contract validation command, or CLI package compatibility changes.',
    'CLI validation has no independent service loop; command tests validate behavior.',
    array['packages/@dvt/cli/test/smoke.test.ts']::text[]
  ),
  (
    'SYS-RUNTIME-DELIVERY',
    'Runtime delivery and projection movement',
    'SYS-RUNTIME-ROOT',
    'service',
    'application',
    'Architecture / Runtime',
    'packages/@dvt/delivery/package.json',
    'Runtime delivery package for projection movement and delivery-buffer operations.',
    'node',
    'high',
    'review',
    'MoveRuntimeDeliveryProjection',
    'command',
    'inbound',
    'packages/@dvt/delivery/test/OutboxWorker.delivery.test.ts',
    'unit',
    'pnpm --filter @dvt/delivery test',
    'Own runtime delivery and projection movement behavior.',
    'Delivery package, projection movement, delivery-buffer behavior, or delivery tests change.',
    'Delivery package telemetry is validated by delivery tests.',
    array['packages/@dvt/delivery/test/OutboxWorker.delivery.test.ts']::text[]
  ),
  (
    'SYS-RUNTIME-DETERMINISM-UTILITIES',
    'Runtime deterministic canonical utilities',
    'SYS-RUNTIME-ROOT',
    'module',
    'domain',
    'Architecture / Runtime',
    'packages/@dvt/canonical/package.json',
    'Runtime deterministic canonicalization utilities.',
    'node',
    'high',
    'review',
    'CanonicalizeRuntimePayload',
    'query',
    'inbound',
    'packages/@dvt/canonical/test/canonical.test.ts',
    'unit',
    'pnpm --filter @dvt/canonical test',
    'Own deterministic canonical utilities used by runtime hashing and replay-sensitive behavior.',
    'Canonicalization, deterministic helper, hash input, or canonical package behavior changes.',
    'Determinism utilities have no independent runtime loop; canonical tests validate behavior.',
    array['packages/@dvt/canonical/test/canonical.test.ts']::text[]
  ),
  (
    'SYS-RUNTIME-DSL',
    'Runtime DSL language layer',
    'SYS-RUNTIME-ROOT',
    'module',
    'domain',
    'Architecture / Runtime',
    'packages/@dvt/dsl/package.json',
    'Runtime DSL package for workflow and step language constructs.',
    'node',
    'high',
    'review',
    'ReadRuntimeDsl',
    'query',
    'inbound',
    'packages/@dvt/dsl/test/dsl-v1.test.ts',
    'unit',
    'pnpm --filter @dvt/dsl test',
    'Own runtime DSL language primitives and package-level DSL validation.',
    'Runtime DSL vocabulary, parser, package exports, or DSL tests change.',
    'DSL language layer has no independent runtime loop; DSL tests validate behavior.',
    array['packages/@dvt/dsl/test/dsl-v1.test.ts']::text[]
  ),
  (
    'SYS-RUNTIME-ENGINE-CORE',
    'Runtime engine core',
    'SYS-RUNTIME-ROOT',
    'service',
    'application',
    'Architecture / Runtime Engine',
    'packages/@dvt/engine/src',
    'Runtime engine composite boundary containing engine contracts, core lifecycle, state, services, adapters, security, and workflow use cases.',
    'node',
    'critical',
    'review',
    'ExecuteWorkflowEngineCore',
    'command',
    'inbound',
    'packages/@dvt/engine/test/architecture/workflowEngineSemanticClosure.architecture.test.ts',
    'architecture',
    'pnpm --filter @dvt/engine test -- workflowEngineSemanticClosure.architecture.test.ts',
    'Own the runtime engine composite boundary and contain concrete engine subcomponents.',
    'Engine core decomposition, lifecycle boundary, public runtime semantics, or engine component split changes.',
    'Engine core observability is validated by workflow engine observability and semantic closure tests.',
    array['packages/@dvt/engine/test/architecture/workflowEngineSemanticClosure.architecture.test.ts']::text[]
  ),
  (
    'SYS-RUNTIME-ENGINE-ADAPTERS',
    'Runtime engine provider adapters',
    'SYS-RUNTIME-ENGINE-CORE',
    'adapter',
    'adapter',
    'Architecture / Runtime Engine',
    'packages/@dvt/engine/src/adapters/CircuitBreakingProviderAdapter.ts',
    'Runtime engine provider adapter interfaces and in-memory/circuit-breaking adapters.',
    'node',
    'high',
    'review',
    'CallRuntimeProviderAdapter',
    'command',
    'outbound',
    'packages/@dvt/engine/test/adapters/CircuitBreakingProviderAdapter.test.ts',
    'unit',
    'pnpm --filter @dvt/engine test -- CircuitBreakingProviderAdapter.test.ts',
    'Own provider adapter abstractions used by the engine core.',
    'Provider adapter contract, in-memory adapter, circuit breaker, or provider adapter test changes.',
    'Provider adapter telemetry is validated by adapter tests.',
    array['packages/@dvt/engine/test/adapters/CircuitBreakingProviderAdapter.test.ts']::text[]
  ),
  (
    'SYS-RUNTIME-ENGINE-APPLICATION',
    'Runtime engine application services',
    'SYS-RUNTIME-ENGINE-CORE',
    'service',
    'application',
    'Architecture / Runtime Engine',
    'packages/@dvt/engine/src/application/IStartRunApplicationService.ts',
    'Runtime engine application services for start-run and recovery orchestration.',
    'node',
    'critical',
    'review',
    'StartRuntimeRunApplication',
    'command',
    'inbound',
    'packages/@dvt/engine/test/application/providerSelection.test.ts',
    'unit',
    'pnpm --filter @dvt/engine test -- providerSelection.test.ts',
    'Own engine application service orchestration above engine domain ports.',
    'Start-run application service, recovery service, provider selection, or admission guard changes.',
    'Application services telemetry is validated by engine application tests.',
    array['packages/@dvt/engine/test/application/providerSelection.test.ts']::text[]
  ),
  (
    'SYS-RUNTIME-ENGINE-ARCHITECTURE-TESTS',
    'Runtime engine architecture test harness',
    'SYS-RUNTIME-ENGINE-CORE',
    'module',
    'infra',
    'Architecture / Runtime Engine Tests',
    'packages/@dvt/engine/test/architecture/adapterCircuitBreaker.architecture.test.ts',
    'Runtime engine architecture and boundary test harness.',
    'none',
    'medium',
    'review',
    'ValidateRuntimeEngineArchitecture',
    'query',
    'inbound',
    'packages/@dvt/engine/test/architecture/workflowEngineBoundaryFitness.architecture.test.ts',
    'architecture',
    'pnpm --filter @dvt/engine test -- workflowEngineBoundaryFitness.architecture.test.ts',
    'Own runtime engine architecture tests as evidence components.',
    'Engine architecture test harness, boundary proof, or architecture fixture changes.',
    'Architecture test component has no runtime observability requirement.',
    array['packages/@dvt/engine/test/architecture/workflowEngineBoundaryFitness.architecture.test.ts']::text[]
  ),
  (
    'SYS-RUNTIME-ENGINE-CONTRACTS',
    'Runtime engine contracts',
    'SYS-RUNTIME-ENGINE-CORE',
    'port',
    'contracts',
    'Architecture / Runtime Engine',
    'packages/@dvt/engine/src/contracts/engine/IProvider.v1.ts',
    'Runtime engine contracts, errors, execution plan policy, run events, enrichment service, and plan schema policies.',
    'node',
    'critical',
    'review',
    'ValidateRuntimeEngineContracts',
    'query',
    'inbound',
    'packages/@dvt/engine/test/contracts/engine.test.ts',
    'contract',
    'pnpm --filter @dvt/engine test -- engine.test.ts',
    'Own runtime engine contract declarations and contract tests.',
    'Engine contract declaration, error contract, execution plan policy, run event contract, or contract test changes.',
    'Contract component has no independent runtime loop; contract tests validate behavior.',
    array['packages/@dvt/engine/test/contracts/engine.test.ts']::text[]
  ),
  (
    'SYS-RUNTIME-ENGINE-CORE-LIFECYCLE',
    'Runtime engine lifecycle core',
    'SYS-RUNTIME-ENGINE-CORE',
    'service',
    'domain',
    'Architecture / Runtime Engine',
    'packages/@dvt/engine/src/core/WorkflowEngine.ts',
    'Workflow engine lifecycle core, facade, snapshot projector, idempotency, and lifecycle runtime.',
    'node',
    'critical',
    'review',
    'ExecuteWorkflowEngineLifecycle',
    'command',
    'inbound',
    'packages/@dvt/engine/test/core/WorkflowEngine.test.ts',
    'unit',
    'pnpm --filter @dvt/engine test -- WorkflowEngine.test.ts',
    'Own runtime engine lifecycle core behavior.',
    'Workflow engine lifecycle, facade construction, snapshot projection, idempotency, or lifecycle tests change.',
    'Lifecycle telemetry is validated by workflow engine observability tests.',
    array['packages/@dvt/engine/test/core/WorkflowEngine.test.ts']::text[]
  ),
  (
    'SYS-RUNTIME-ENGINE-DETERMINISM-UTILS',
    'Runtime engine determinism and utility support',
    'SYS-RUNTIME-ENGINE-CORE',
    'module',
    'domain',
    'Architecture / Runtime Engine',
    'packages/@dvt/engine/src/utils/clock.ts',
    'Runtime engine deterministic utility support and metric abstractions.',
    'node',
    'high',
    'review',
    'ReadRuntimeDeterministicUtility',
    'query',
    'inbound',
    'packages/@dvt/engine/test/utils/clock.test.ts',
    'unit',
    'pnpm --filter @dvt/engine test -- clock.test.ts',
    'Own deterministic utilities used by runtime engine behavior.',
    'Clock, deterministic helper, metric interface, or utility test changes.',
    'Determinism utility component has no independent runtime loop; utility tests validate behavior.',
    array['packages/@dvt/engine/test/utils/clock.test.ts']::text[]
  ),
  (
    'SYS-RUNTIME-ENGINE-DOMAIN-PORTS',
    'Runtime engine domain ports',
    'SYS-RUNTIME-ENGINE-CORE',
    'port',
    'domain',
    'Architecture / Runtime Engine',
    'packages/@dvt/engine/src/domain/IRunCommandService.ts',
    'Runtime engine domain ports for run commands, state, transitions, workflow engine, and execution dependencies.',
    'node',
    'critical',
    'review',
    'ExecuteRunCommandPort',
    'command',
    'inbound',
    'packages/@dvt/engine/test/domain/startRunIntentPolicy.test.ts',
    'unit',
    'pnpm --filter @dvt/engine test -- startRunIntentPolicy.test.ts',
    'Own engine domain ports and domain policies consumed by application services and adapters.',
    'Domain port interface, run command service, state dependency, or domain policy changes.',
    'Domain port component has no independent runtime loop; domain tests validate behavior.',
    array['packages/@dvt/engine/test/domain/startRunIntentPolicy.test.ts']::text[]
  ),
  (
    'SYS-RUNTIME-ENGINE-OUTBOX',
    'Runtime engine outbox rate limiting',
    'SYS-RUNTIME-ENGINE-CORE',
    'port',
    'application',
    'Architecture / Runtime Engine',
    'packages/@dvt/engine/src/outbox/IOutboxRateLimiter.ts',
    'Runtime engine outbox rate-limiter port and in-memory limiter.',
    'node',
    'high',
    'review',
    'LimitRuntimeOutboxDispatch',
    'command',
    'inbound',
    'packages/@dvt/engine/test/state/InMemoryTxStore.outbox.test.ts',
    'unit',
    'pnpm --filter @dvt/engine test -- InMemoryTxStore.outbox.test.ts',
    'Own outbox rate-limiting port semantics for runtime dispatch.',
    'Outbox rate limiter interface, limiter behavior, or outbox dispatch tests change.',
    'Outbox limiter telemetry is validated through outbox state tests.',
    array['packages/@dvt/engine/test/state/InMemoryTxStore.outbox.test.ts']::text[]
  ),
  (
    'SYS-RUNTIME-ENGINE-PACKAGE-SURFACE',
    'Runtime engine package and public surface',
    'SYS-RUNTIME-ENGINE-CORE',
    'package',
    'application',
    'Architecture / Runtime Engine',
    'packages/@dvt/engine/package.json',
    'Runtime engine package metadata, public exports, testing entrypoints, and build config.',
    'none',
    'medium',
    'review',
    'ImportRuntimeEnginePackage',
    'api',
    'inbound',
    'packages/@dvt/engine/test/contracts/package-surface.test.ts',
    'contract',
    'pnpm --filter @dvt/engine test -- package-surface.test.ts',
    'Own engine package metadata and public package surface.',
    'Engine package export, package config, test config, or public entrypoint changes.',
    'Package surface component has no runtime observability requirement.',
    array['packages/@dvt/engine/test/contracts/package-surface.test.ts']::text[]
  ),
  (
    'SYS-RUNTIME-ENGINE-RUN-CONTROL',
    'Runtime engine run control and signal services',
    'SYS-RUNTIME-ENGINE-CORE',
    'service',
    'application',
    'Architecture / Runtime Engine',
    'packages/@dvt/engine/src/services/runControl/RunCommandService.ts',
    'Runtime run command and signal control services.',
    'node',
    'critical',
    'review',
    'SubmitRuntimeRunCommand',
    'command',
    'inbound',
    'packages/@dvt/engine/test/services/SignalTransitionGuard.test.ts',
    'unit',
    'pnpm --filter @dvt/engine test -- SignalTransitionGuard.test.ts',
    'Own runtime run-control and signal transition services.',
    'Run command service, signal transition guard, run-control semantics, or signal tests change.',
    'Run-control telemetry is validated by signal transition tests.',
    array['packages/@dvt/engine/test/services/SignalTransitionGuard.test.ts']::text[]
  ),
  (
    'SYS-RUNTIME-ENGINE-RUN-MAINTENANCE',
    'Runtime engine run maintenance and reconciliation',
    'SYS-RUNTIME-ENGINE-CORE',
    'service',
    'application',
    'Architecture / Runtime Engine',
    'packages/@dvt/engine/src/services/RunMaintenanceService.ts',
    'Runtime run maintenance, reconciliation policy, dispatched-intent handling, and snapshot staleness coordination.',
    'node',
    'high',
    'review',
    'ReconcileRuntimeRunMaintenance',
    'command',
    'inbound',
    'packages/@dvt/engine/test/services/RunMaintenanceService.test.ts',
    'unit',
    'pnpm --filter @dvt/engine test -- RunMaintenanceService.test.ts',
    'Own runtime maintenance and reconciliation services.',
    'Run maintenance policy, reconciliation behavior, snapshot staleness, or maintenance tests change.',
    'Run maintenance telemetry is validated through maintenance service tests.',
    array['packages/@dvt/engine/test/services/RunMaintenanceService.test.ts']::text[]
  ),
  (
    'SYS-RUNTIME-ENGINE-RUNTIME-SERVICES',
    'Runtime engine run status and enrichment services',
    'SYS-RUNTIME-ENGINE-CORE',
    'service',
    'application',
    'Architecture / Runtime Engine',
    'packages/@dvt/engine/src/services/RunStatusQueryService.ts',
    'Runtime run status, run enrichment, execution-context admission, and query services.',
    'node',
    'high',
    'review',
    'ReadRuntimeRunStatus',
    'query',
    'inbound',
    'packages/@dvt/engine/test/services/RunStatusQueryService.test.ts',
    'unit',
    'pnpm --filter @dvt/engine test -- RunStatusQueryService.test.ts',
    'Own runtime run-status and enrichment read services.',
    'Run status query, enrichment service, execution-context admission, or runtime service tests change.',
    'Runtime read service telemetry is validated through run-status and enrichment tests.',
    array['packages/@dvt/engine/test/services/RunStatusQueryService.test.ts']::text[]
  ),
  (
    'SYS-RUNTIME-ENGINE-SECURITY',
    'Runtime engine authorization and URI policy',
    'SYS-RUNTIME-ENGINE-CORE',
    'module',
    'domain',
    'Architecture / Runtime Engine',
    'packages/@dvt/engine/src/security/AuthorizationError.ts',
    'Runtime engine authorization, authorizer policies, plan-ref policy, and plan URI security.',
    'node',
    'critical',
    'review',
    'AuthorizeRuntimeEngineRequest',
    'command',
    'inbound',
    'packages/@dvt/engine/test/security/authorizer.deny.test.ts',
    'unit',
    'pnpm --filter @dvt/engine test -- authorizer.deny.test.ts planRefPolicy.test.ts',
    'Own runtime authorization and plan URI security policy.',
    'Authorization policy, plan-ref security, URI leakage guard, or security test changes.',
    'Security policy has no independent runtime loop; security tests validate behavior.',
    array['packages/@dvt/engine/test/security/authorizer.deny.test.ts']::text[]
  ),
  (
    'SYS-RUNTIME-ENGINE-START-RUN',
    'Runtime engine start-run orchestration',
    'SYS-RUNTIME-ENGINE-CORE',
    'service',
    'application',
    'Architecture / Runtime Engine',
    'packages/@dvt/engine/src/services/startRun/StartRunAdmissionService.ts',
    'Runtime engine start-run orchestration, admission policy, event factory, and decomposition services.',
    'node',
    'critical',
    'review',
    'StartRuntimeRun',
    'command',
    'inbound',
    'packages/@dvt/engine/test/services/StartRunApplicationService.test.ts',
    'unit',
    'pnpm --filter @dvt/engine test -- StartRunApplicationService.test.ts',
    'Own runtime start-run orchestration and admission behavior.',
    'Start-run service, event factory, execution-context admission, decomposition, or start-run tests change.',
    'Start-run telemetry is validated by start-run decomposition and service tests.',
    array['packages/@dvt/engine/test/services/StartRunApplicationService.test.ts']::text[]
  ),
  (
    'SYS-RUNTIME-ENGINE-STATE',
    'Runtime engine in-memory state and snapshots',
    'SYS-RUNTIME-ENGINE-CORE',
    'adapter',
    'adapter',
    'Architecture / Runtime Engine',
    'packages/@dvt/engine/src/state/InMemoryRunStateStore.ts',
    'Runtime engine in-memory state stores, transaction store, snapshots, provider refs, and bootstrap support.',
    'node',
    'high',
    'review',
    'WriteInMemoryRunState',
    'storage',
    'outbound',
    'packages/@dvt/engine/test/state/InMemoryRunStateStore.appendInvariants.test.ts',
    'unit',
    'pnpm --filter @dvt/engine test -- InMemoryRunStateStore.appendInvariants.test.ts',
    'Own in-memory runtime state and snapshot adapters used by engine tests and local runtime execution.',
    'In-memory state store, transaction store, snapshot rebuild, provider ref, or state test changes.',
    'In-memory state telemetry is validated through state-store tests.',
    array['packages/@dvt/engine/test/state/InMemoryRunStateStore.appendInvariants.test.ts']::text[]
  ),
  (
    'SYS-RUNTIME-ENGINE-WORKFLOW-USE-CASES',
    'Runtime engine workflow use cases',
    'SYS-RUNTIME-ENGINE-CORE',
    'service',
    'application',
    'Architecture / Runtime Engine',
    'packages/@dvt/engine/src/application/workflow-engine-use-cases/buildWorkflowEngineUseCases.ts',
    'Runtime workflow engine use-case facade and use-case construction.',
    'node',
    'high',
    'review',
    'BuildWorkflowEngineUseCases',
    'command',
    'inbound',
    'packages/@dvt/engine/test/application/workflowEngineUseCases.factory.test.ts',
    'unit',
    'pnpm --filter @dvt/engine test -- workflowEngineUseCases.factory.test.ts',
    'Own workflow engine use-case facade construction.',
    'Workflow use-case facade, use-case factory, or workflow use-case tests change.',
    'Workflow use-case telemetry is validated through use-case factory tests.',
    array['packages/@dvt/engine/test/application/workflowEngineUseCases.factory.test.ts']::text[]
  ),
  (
    'SYS-RUNTIME-PLAN-INTERPRETATION',
    'Runtime plan interpretation',
    'SYS-RUNTIME-ROOT',
    'module',
    'domain',
    'Architecture / Runtime',
    'packages/@dvt/plan-interpreter/package.json',
    'Runtime plan interpretation package.',
    'node',
    'high',
    'review',
    'InterpretRuntimePlan',
    'query',
    'inbound',
    'packages/@dvt/plan-interpreter/test/dagAnalyzer.test.ts',
    'unit',
    'pnpm --filter @dvt/plan-interpreter test',
    'Own runtime plan interpretation behavior.',
    'Plan interpretation package, interpreter semantics, or interpreter tests change.',
    'Plan interpretation has no independent runtime loop; interpreter tests validate behavior.',
    array['packages/@dvt/plan-interpreter/test/dagAnalyzer.test.ts']::text[]
  ),
  (
    'SYS-RUNTIME-PLAN-VERIFICATION',
    'Runtime plan verification',
    'SYS-RUNTIME-ROOT',
    'module',
    'domain',
    'Architecture / Runtime',
    'packages/@dvt/plan-verifier/package.json',
    'Runtime plan verification package.',
    'node',
    'high',
    'review',
    'VerifyRuntimePlan',
    'query',
    'inbound',
    'packages/@dvt/plan-verifier/test/verify.test.ts',
    'unit',
    'pnpm --filter @dvt/plan-verifier test',
    'Own runtime plan verification behavior.',
    'Plan verifier package, verification semantics, or verifier tests change.',
    'Plan verification has no independent runtime loop; verifier tests validate behavior.',
    array['packages/@dvt/plan-verifier/test/verify.test.ts']::text[]
  ),
  (
    'SYS-RUNTIME-RUN-DOMAIN',
    'Runtime run domain model',
    'SYS-RUNTIME-ROOT',
    'module',
    'domain',
    'Architecture / Runtime',
    'packages/@dvt/run-domain/package.json',
    'Runtime run-domain package.',
    'node',
    'high',
    'review',
    'ReadRuntimeRunDomain',
    'query',
    'inbound',
    'packages/@dvt/run-domain/test/applyRunEvent.test.ts',
    'unit',
    'pnpm --filter @dvt/run-domain test',
    'Own runtime run-domain model vocabulary and package behavior.',
    'Run-domain model, package exports, domain vocabulary, or run-domain tests change.',
    'Run-domain model has no independent runtime loop; domain tests validate behavior.',
    array['packages/@dvt/run-domain/test/applyRunEvent.test.ts']::text[]
  ),
  (
    'SYS-RUNTIME-STATE-STORE',
    'Runtime state-store lifecycle',
    'SYS-RUNTIME-ROOT',
    'port',
    'application',
    'Architecture / Runtime',
    'packages/@dvt/state-store/package.json',
    'Runtime state-store package and lifecycle contracts.',
    'node',
    'critical',
    'review',
    'WriteRuntimeStateStore',
    'storage',
    'outbound',
    'packages/@dvt/state-store/test/command-port.test.ts',
    'unit',
    'pnpm --filter @dvt/state-store test',
    'Own runtime state-store lifecycle package and state-store port behavior.',
    'State-store package, lifecycle contract, state persistence semantics, or state-store tests change.',
    'State-store telemetry is validated through state-store tests.',
    array['packages/@dvt/state-store/test/command-port.test.ts']::text[]
  );

insert into architecture.component (
  component_id,
  name,
  kind,
  layer,
  owner,
  repo_path,
  public_contract,
  runtime,
  criticality,
  status,
  parent_component_id
)
select
  component_id,
  name,
  kind,
  layer,
  owner,
  repo_path,
  public_contract,
  runtime,
  criticality,
  status,
  parent_component_id
from architecture_authority_seed
on conflict (component_id) do update set
  name = excluded.name,
  kind = excluded.kind,
  layer = excluded.layer,
  owner = excluded.owner,
  repo_path = excluded.repo_path,
  public_contract = excluded.public_contract,
  runtime = excluded.runtime,
  criticality = excluded.criticality,
  status = excluded.status,
  parent_component_id = excluded.parent_component_id,
  updated_at = now();

insert into architecture.component_responsibility (
  responsibility_id,
  component_id,
  responsibility,
  reason_to_change,
  ddd_owner,
  status
)
select
  'RESP-' || component_id,
  component_id,
  responsibility,
  reason_to_change,
  owner,
  case when status = 'deprecated' then 'implemented' else 'implemented' end
from architecture_authority_seed
on conflict (responsibility_id) do update set
  component_id = excluded.component_id,
  responsibility = excluded.responsibility,
  reason_to_change = excluded.reason_to_change,
  ddd_owner = excluded.ddd_owner,
  status = excluded.status;

insert into architecture.component_port (
  port_id,
  component_id,
  port_name,
  port_kind,
  direction,
  negative_tests,
  status
)
select
  'PORT-' || component_id || '-PRIMARY',
  component_id,
  port_name,
  port_kind,
  port_direction,
  negative_tests,
  'implemented'
from architecture_authority_seed
where status <> 'deprecated'
on conflict (port_id) do update set
  component_id = excluded.component_id,
  port_name = excluded.port_name,
  port_kind = excluded.port_kind,
  direction = excluded.direction,
  negative_tests = excluded.negative_tests,
  status = excluded.status;

insert into architecture.component_test (
  test_id,
  component_id,
  test_path,
  test_kind,
  coverage_level,
  required,
  validation_command
)
select
  'TEST-' || component_id || '-PRIMARY',
  component_id,
  test_path,
  test_kind,
  case
    when test_kind = 'architecture' then 'boundary'
    when test_kind = 'contract' then 'boundary'
    when test_kind = 'integration' then 'flow'
    else 'behavior'
  end,
  true,
  validation_command
from architecture_authority_seed
where status <> 'deprecated'
on conflict (test_id) do update set
  component_id = excluded.component_id,
  test_path = excluded.test_path,
  test_kind = excluded.test_kind,
  coverage_level = excluded.coverage_level,
  required = excluded.required,
  validation_command = excluded.validation_command;

insert into architecture.component_observability (
  observability_id,
  component_id,
  signal_name,
  signal_kind,
  required,
  status
)
select
  'OBS-' || component_id || '-PRIMARY',
  component_id,
  observability_signal,
  'log',
  true,
  'not_applicable'
from architecture_authority_seed
where status <> 'deprecated'
on conflict (observability_id) do update set
  component_id = excluded.component_id,
  signal_name = excluded.signal_name,
  signal_kind = excluded.signal_kind,
  required = excluded.required,
  status = excluded.status;

insert into architecture.component_relation (
  relation_id,
  source_component_id,
  target_component_id,
  relation_type,
  direction,
  sync_async,
  contract_id,
  failure_mode,
  authorization_scope,
  source_refs,
  status
)
select
  'REL-' || replace(parent_component_id, 'SYS-', '') || '-CONTAINS-' || replace(component_id, 'SYS-', ''),
  parent_component_id,
  component_id,
  'contains',
  'outbound',
  'build_time',
  null,
  'Component profile becomes incomplete if this child is remapped without a governed Planning DB component update.',
  'repo-local component governance',
  jsonb_build_array(
    'docs/architecture/command-query-rail-governance.md',
    'docs/planning/proposals/mandatory/governance-and-docs/planning-db-component-integrity-vocabulary-rail-plan-20260612.md',
    repo_path
  ),
  'implemented'
from architecture_authority_seed
where parent_component_id is not null
  and status <> 'deprecated'
on conflict (relation_id) do update set
  source_component_id = excluded.source_component_id,
  target_component_id = excluded.target_component_id,
  relation_type = excluded.relation_type,
  direction = excluded.direction,
  sync_async = excluded.sync_async,
  contract_id = excluded.contract_id,
  failure_mode = excluded.failure_mode,
  authorization_scope = excluded.authorization_scope,
  source_refs = excluded.source_refs,
  status = excluded.status,
  updated_at = now();

drop table if exists pg_temp.architecture_authority_seed;
drop table if exists pg_temp.adapter_leaf_map;
