-- DB-first feature-mechanization manifest for the Canvas-first retirement of
-- fixed add-node palette surfaces and the governance import delete handling
-- required to validate that retirement before commit.

insert into planning_query_store.feature_mechanization_local_rails (
  rail_id,
  feature_id,
  mechanization_status,
  rail_name,
  normalized_rail_name,
  rail_type,
  ddd_owner,
  rail_status,
  symbol_refs,
  implementation_refs,
  documentation_refs,
  governing_sources,
  allowed_implementation_surfaces,
  architecture_guards,
  completion_gate,
  source_path,
  source_content_sha256,
  raw_rail,
  raw_manifest,
  revision,
  created_by
)
values (
  'local#UXDB-CANVAS-CONTEXT-MENU-P0-1#command#retirecanvasfixedaddnodepalette',
  'UXDB-CANVAS-CONTEXT-MENU-P0-1',
  'implemented',
  'RetireCanvasFixedAddNodePalette',
  'retirecanvasfixedaddnodepalette',
  'command',
  'CanvasContextMenu',
  'implemented',
  jsonb_build_array(
    'apps/web/src/app/views/canvas/CanvasStateViews.tsx#CanvasEmptyStateView',
    'scripts/planning-db-import.cjs#readTrackedDocumentPaths',
    'scripts/planning-db/code-symbol-inventory.cjs#listTrackedCodeFiles',
    'scripts/planning-db/command-query-rail-catalog.cjs#readTrackedDocumentPaths'
  ),
  jsonb_build_array(
    'apps/web/src/app/plugins/dbt/dbtContributions.ts',
    'apps/web/src/app/plugins/dvt/dvtContributions.ts',
    'apps/web/src/app/plugins/nodeTypeContracts.ts',
    'apps/web/src/app/views/Canvas.routeStates.first-canvas-catalog.test.tsx',
    'apps/web/src/app/views/Canvas.routeStates.first-canvas-policy.test.tsx',
    'apps/web/src/app/views/Canvas.routeStates.host-cycle-persistence.test.tsx',
    'apps/web/src/app/views/Canvas.test.controller.defaults.ts',
    'apps/web/src/app/views/Canvas.test.hostCycleScenario.ts',
    'apps/web/src/app/views/canvas/CanvasAddNodePalette.test.tsx',
    'apps/web/src/app/views/canvas/CanvasAddNodePalette.tsx',
    'apps/web/src/app/views/canvas/CanvasCenterSurface.architecture.test.ts',
    'apps/web/src/app/views/canvas/CanvasEmptyAuthoringEntrypoint.architecture.test.ts',
    'apps/web/src/app/views/canvas/CanvasPlaygroundHost.test.tsx',
    'apps/web/src/app/views/canvas/CanvasPlaygroundTabStrip.test.tsx',
    'apps/web/src/app/views/canvas/CanvasShell.architecture.test.tsx',
    'apps/web/src/app/views/canvas/CanvasStateViews.test.tsx',
    'apps/web/src/app/views/canvas/CanvasStateViews.tsx',
    'apps/web/src/app/views/canvas/canvasCenterSurfaceWorkbench.tsx',
    'apps/web/src/app/views/canvas/canvasCopy.types.ts',
    'apps/web/src/app/views/canvas/canvasCopyCatalog.route.es.ts',
    'apps/web/src/app/views/canvas/canvasCopyCatalog.route.ts',
    'apps/web/src/app/views/canvas/canvasCopyCatalog.toolbar.es.ts',
    'apps/web/src/app/views/canvas/canvasCopyCatalog.toolbar.ts',
    'apps/web/src/app/views/canvas/canvasHostCycleState.test.ts',
    'apps/web/src/app/views/canvas/canvasHostCycleState.ts',
    'apps/web/src/app/views/canvas/canvasKindRegistration.testSupport.ts',
    'apps/web/src/app/views/canvas/canvasOutputTargetTemplateCatalog.ts',
    'apps/web/src/app/views/canvas/canvasPlaygroundTabState.test.ts',
    'apps/web/src/app/views/canvas/canvasPlaygroundTabStripModel.test.ts',
    'apps/web/src/app/views/canvas/canvasTemplatePresentation.test.ts',
    'apps/web/src/app/views/canvas/canvasTransformationTemplateCatalog.ts',
    'apps/web/src/app/views/canvas/copy.test.ts',
    'apps/web/src/app/views/canvas/useCanvasController.test.projectionMocks.ts',
    'docs/architecture/components/web/graph/canvas-interaction-command-surface-component.md',
    'docs/architecture/components/web/graph/canvas-ready-node-authoring-entrypoint-component.md',
    'docs/planning/proposals/mandatory/frontend-and-ux/f29c-canvas-insert-palette-plan-20260525.md',
    'scripts/planning-db-import.cjs',
    'scripts/planning-db-import.test.cjs',
    'scripts/planning-db/code-symbol-inventory.cjs',
    'scripts/planning-db/command-query-rail-catalog.cjs',
    'tools/planning-db/migrations/147_web_canvas_legacy_add_node_palette_retirement.sql',
    'tools/planning-db/migrations/148_web_canvas_context_menu_retired_palette_vocabulary.sql',
    'tools/planning-db/migrations/149_web_canvas_legacy_palette_deprecated_paths.sql',
    'tools/planning-db/migrations/150_web_canvas_context_menu_retirement_feature_mechanization.sql'
  ),
  jsonb_build_array(
    'docs/architecture/components/web/graph/canvas-interaction-command-surface-component.md',
    'docs/architecture/components/web/graph/canvas-ready-node-authoring-entrypoint-component.md',
    'docs/planning/proposals/mandatory/frontend-and-ux/f29c-canvas-insert-palette-plan-20260525.md'
  ),
  jsonb_build_array(
    'AGENTS.md',
    'docs/planning/status/governance-document-rule-inventory.md',
    'docs/guides/ai-work-protocol.md',
    'docs/planning/state/planning-control-tower.md',
    'docs/architecture/command-query-rail-governance.md',
    'docs/architecture/fowler-opportunity-planning-governance.md',
    'buzon/TAREA.TXT'
  ),
  jsonb_build_array(
    'apps/web/src/app/plugins/dbt/dbtContributions.ts',
    'apps/web/src/app/plugins/dvt/dvtContributions.ts',
    'apps/web/src/app/plugins/nodeTypeContracts.ts',
    'apps/web/src/app/views/Canvas.routeStates.first-canvas-catalog.test.tsx',
    'apps/web/src/app/views/Canvas.routeStates.first-canvas-policy.test.tsx',
    'apps/web/src/app/views/Canvas.routeStates.host-cycle-persistence.test.tsx',
    'apps/web/src/app/views/Canvas.test.controller.defaults.ts',
    'apps/web/src/app/views/Canvas.test.hostCycleScenario.ts',
    'apps/web/src/app/views/canvas/CanvasAddNodePalette.test.tsx',
    'apps/web/src/app/views/canvas/CanvasAddNodePalette.tsx',
    'apps/web/src/app/views/canvas/CanvasCenterSurface.architecture.test.ts',
    'apps/web/src/app/views/canvas/CanvasEmptyAuthoringEntrypoint.architecture.test.ts',
    'apps/web/src/app/views/canvas/CanvasPlaygroundHost.test.tsx',
    'apps/web/src/app/views/canvas/CanvasPlaygroundTabStrip.test.tsx',
    'apps/web/src/app/views/canvas/CanvasShell.architecture.test.tsx',
    'apps/web/src/app/views/canvas/CanvasStateViews.test.tsx',
    'apps/web/src/app/views/canvas/CanvasStateViews.tsx',
    'apps/web/src/app/views/canvas/canvasCenterSurfaceWorkbench.tsx',
    'apps/web/src/app/views/canvas/canvasCopy.types.ts',
    'apps/web/src/app/views/canvas/canvasCopyCatalog.route.es.ts',
    'apps/web/src/app/views/canvas/canvasCopyCatalog.route.ts',
    'apps/web/src/app/views/canvas/canvasCopyCatalog.toolbar.es.ts',
    'apps/web/src/app/views/canvas/canvasCopyCatalog.toolbar.ts',
    'apps/web/src/app/views/canvas/canvasHostCycleState.test.ts',
    'apps/web/src/app/views/canvas/canvasHostCycleState.ts',
    'apps/web/src/app/views/canvas/canvasKindRegistration.testSupport.ts',
    'apps/web/src/app/views/canvas/canvasOutputTargetTemplateCatalog.ts',
    'apps/web/src/app/views/canvas/canvasPlaygroundTabState.test.ts',
    'apps/web/src/app/views/canvas/canvasPlaygroundTabStripModel.test.ts',
    'apps/web/src/app/views/canvas/canvasTemplatePresentation.test.ts',
    'apps/web/src/app/views/canvas/canvasTransformationTemplateCatalog.ts',
    'apps/web/src/app/views/canvas/copy.test.ts',
    'apps/web/src/app/views/canvas/useCanvasController.test.projectionMocks.ts',
    'docs/architecture/components/web/graph/canvas-interaction-command-surface-component.md',
    'docs/architecture/components/web/graph/canvas-ready-node-authoring-entrypoint-component.md',
    'docs/planning/proposals/mandatory/frontend-and-ux/f29c-canvas-insert-palette-plan-20260525.md',
    'scripts/planning-db-import.cjs',
    'scripts/planning-db-import.test.cjs',
    'scripts/planning-db/code-symbol-inventory.cjs',
    'scripts/planning-db/command-query-rail-catalog.cjs',
    'tools/planning-db/migrations/147_web_canvas_legacy_add_node_palette_retirement.sql',
    'tools/planning-db/migrations/148_web_canvas_context_menu_retired_palette_vocabulary.sql',
    'tools/planning-db/migrations/149_web_canvas_legacy_palette_deprecated_paths.sql',
    'tools/planning-db/migrations/150_web_canvas_context_menu_retirement_feature_mechanization.sql'
  ),
  jsonb_build_array(
    'apps/web/src/app/views/canvas/CanvasShell.architecture.test.tsx',
    'apps/web/src/app/views/canvas/CanvasContextMenuView.test.tsx',
    'apps/web/src/app/views/canvas/CanvasViewport.contextMenu.test.tsx',
    'scripts/planning-db-import.test.cjs',
    'pnpm planning:db:integrity:check'
  ),
  jsonb_build_array(
    'pnpm --filter @dvt/web exec vitest run src/app/views/canvas/CanvasStateViews.test.tsx src/app/views/canvas/canvasHostCycleState.test.ts src/app/views/canvas/CanvasCenterSurface.architecture.test.ts src/app/views/canvas/CanvasEmptyAuthoringEntrypoint.architecture.test.ts src/app/views/Canvas.routeStates.first-canvas-policy.test.tsx src/app/views/Canvas.routeStates.first-canvas-catalog.test.tsx src/app/views/Canvas.routeStates.host-cycle-persistence.test.tsx src/app/views/canvas/copy.test.ts',
    'pnpm --filter @dvt/web exec vitest run src/app/views/canvas/CanvasContextMenuView.test.tsx src/app/views/canvas/useCanvasContextMenuPresenter.canvasActions.test.tsx src/app/views/canvas/useCanvasContextMenuPresenter.graphActions.test.tsx src/app/views/canvas/useCanvasContextMenuPresenter.lifecycle.test.tsx src/app/views/canvas/CanvasViewport.contextMenu.test.tsx src/app/views/canvas/CanvasShell.architecture.test.tsx',
    'node tools/ci/run-web-cypress-native.mjs --spec cypress/e2e/canvas/canvas-ready-node-authoring.cy.ts',
    'node --test scripts/planning-db-import.test.cjs',
    'pnpm --filter @dvt/web typecheck',
    'pnpm --filter @dvt/web lint',
    'pnpm governance:refresh',
    'pnpm docs:feature-mechanization:implementation',
    'pnpm verify:prepush'
  ),
  'tools/planning-db/migrations/150_web_canvas_context_menu_retirement_feature_mechanization.sql',
  '1501501501501501501501501501501501501501501501501501501501501501',
  jsonb_build_object(
    'name', 'RetireCanvasFixedAddNodePalette',
    'type', 'command',
    'dddOwner', 'CanvasContextMenu',
    'status', 'implemented'
  ),
  jsonb_build_object(
    'version', 1,
    'featureId', 'UXDB-CANVAS-CONTEXT-MENU-P0-1',
    'mechanizationStatus', 'implemented',
    'noHumanDecisionsRemaining', true,
    'implementationPlan', 'DB-first retirement of fixed Canvas add-node palette in favor of Canvas context-menu creation.',
    'componentGuides', jsonb_build_array(
      'docs/architecture/components/web/graph/canvas-interaction-command-surface-component.md',
      'docs/architecture/components/web/graph/canvas-ready-node-authoring-entrypoint-component.md'
    ),
    'governingSources', jsonb_build_array(
      'AGENTS.md',
      'docs/planning/status/governance-document-rule-inventory.md',
      'docs/guides/ai-work-protocol.md',
      'docs/planning/state/planning-control-tower.md',
      'docs/architecture/command-query-rail-governance.md',
      'docs/architecture/fowler-opportunity-planning-governance.md',
      'buzon/TAREA.TXT'
    ),
    'allowedImplementationSurfaces', jsonb_build_array(
      'apps/web/src/app/plugins/dbt/dbtContributions.ts',
      'apps/web/src/app/plugins/dvt/dvtContributions.ts',
      'apps/web/src/app/plugins/nodeTypeContracts.ts',
      'apps/web/src/app/views/Canvas.routeStates.first-canvas-catalog.test.tsx',
      'apps/web/src/app/views/Canvas.routeStates.first-canvas-policy.test.tsx',
      'apps/web/src/app/views/Canvas.routeStates.host-cycle-persistence.test.tsx',
      'apps/web/src/app/views/Canvas.test.controller.defaults.ts',
      'apps/web/src/app/views/Canvas.test.hostCycleScenario.ts',
      'apps/web/src/app/views/canvas/CanvasAddNodePalette.test.tsx',
      'apps/web/src/app/views/canvas/CanvasAddNodePalette.tsx',
      'apps/web/src/app/views/canvas/CanvasCenterSurface.architecture.test.ts',
      'apps/web/src/app/views/canvas/CanvasEmptyAuthoringEntrypoint.architecture.test.ts',
      'apps/web/src/app/views/canvas/CanvasPlaygroundHost.test.tsx',
      'apps/web/src/app/views/canvas/CanvasPlaygroundTabStrip.test.tsx',
      'apps/web/src/app/views/canvas/CanvasShell.architecture.test.tsx',
      'apps/web/src/app/views/canvas/CanvasStateViews.test.tsx',
      'apps/web/src/app/views/canvas/CanvasStateViews.tsx',
      'apps/web/src/app/views/canvas/canvasCenterSurfaceWorkbench.tsx',
      'apps/web/src/app/views/canvas/canvasCopy.types.ts',
      'apps/web/src/app/views/canvas/canvasCopyCatalog.route.es.ts',
      'apps/web/src/app/views/canvas/canvasCopyCatalog.route.ts',
      'apps/web/src/app/views/canvas/canvasCopyCatalog.toolbar.es.ts',
      'apps/web/src/app/views/canvas/canvasCopyCatalog.toolbar.ts',
      'apps/web/src/app/views/canvas/canvasHostCycleState.test.ts',
      'apps/web/src/app/views/canvas/canvasHostCycleState.ts',
      'apps/web/src/app/views/canvas/canvasKindRegistration.testSupport.ts',
      'apps/web/src/app/views/canvas/canvasOutputTargetTemplateCatalog.ts',
      'apps/web/src/app/views/canvas/canvasPlaygroundTabState.test.ts',
      'apps/web/src/app/views/canvas/canvasPlaygroundTabStripModel.test.ts',
      'apps/web/src/app/views/canvas/canvasTemplatePresentation.test.ts',
      'apps/web/src/app/views/canvas/canvasTransformationTemplateCatalog.ts',
      'apps/web/src/app/views/canvas/copy.test.ts',
      'apps/web/src/app/views/canvas/useCanvasController.test.projectionMocks.ts',
      'docs/architecture/components/web/graph/canvas-interaction-command-surface-component.md',
      'docs/architecture/components/web/graph/canvas-ready-node-authoring-entrypoint-component.md',
      'docs/planning/proposals/mandatory/frontend-and-ux/f29c-canvas-insert-palette-plan-20260525.md',
      'scripts/planning-db-import.cjs',
      'scripts/planning-db-import.test.cjs',
      'scripts/planning-db/code-symbol-inventory.cjs',
      'scripts/planning-db/command-query-rail-catalog.cjs',
      'tools/planning-db/migrations/147_web_canvas_legacy_add_node_palette_retirement.sql',
      'tools/planning-db/migrations/148_web_canvas_context_menu_retired_palette_vocabulary.sql',
      'tools/planning-db/migrations/149_web_canvas_legacy_palette_deprecated_paths.sql',
      'tools/planning-db/migrations/150_web_canvas_context_menu_retirement_feature_mechanization.sql'
    ),
    'forbiddenImplementationSurfaces', jsonb_build_array(
      'apps/web/src/app/views/canvas/CanvasAddNodePalette.tsx',
      'apps/web/src/app/views/canvas/CanvasAddNodePalette.test.tsx',
      'apps/web/src/app/views/canvas/canvasTransformationTemplateCatalog.ts',
      'apps/web/src/app/views/canvas/canvasOutputTargetTemplateCatalog.ts'
    ),
    'commandQueryRails', jsonb_build_array(
      jsonb_build_object(
        'name', 'RetireCanvasFixedAddNodePalette',
        'type', 'command',
        'dddOwner', 'CanvasContextMenu',
        'status', 'implemented'
      )
    ),
    'domainObjects', jsonb_build_array(
      'CanvasContextMenu',
      'CanvasEmptyStateView',
      'GovernanceImportDeleteAwareInventory'
    ),
    'fowlerSignals', jsonb_build_array(
      'responsibility_overload',
      'documentation_drift',
      'test_harness_overload'
    ),
    'architectureGuards', jsonb_build_array(
      'apps/web/src/app/views/canvas/CanvasShell.architecture.test.tsx',
      'apps/web/src/app/views/canvas/CanvasCenterSurface.architecture.test.ts',
      'pnpm planning:db:integrity:check'
    ),
    'cypressFlows', jsonb_build_array(
      'node tools/ci/run-web-cypress-native.mjs --spec cypress/e2e/canvas/canvas-ready-node-authoring.cy.ts'
    ),
    'completionGate', jsonb_build_array(
      'pnpm --filter @dvt/web exec vitest run src/app/views/canvas/CanvasStateViews.test.tsx src/app/views/canvas/canvasHostCycleState.test.ts src/app/views/canvas/CanvasCenterSurface.architecture.test.ts src/app/views/canvas/CanvasEmptyAuthoringEntrypoint.architecture.test.ts src/app/views/Canvas.routeStates.first-canvas-policy.test.tsx src/app/views/Canvas.routeStates.first-canvas-catalog.test.tsx src/app/views/Canvas.routeStates.host-cycle-persistence.test.tsx src/app/views/canvas/copy.test.ts',
      'pnpm --filter @dvt/web exec vitest run src/app/views/canvas/CanvasContextMenuView.test.tsx src/app/views/canvas/useCanvasContextMenuPresenter.canvasActions.test.tsx src/app/views/canvas/useCanvasContextMenuPresenter.graphActions.test.tsx src/app/views/canvas/useCanvasContextMenuPresenter.lifecycle.test.tsx src/app/views/canvas/CanvasViewport.contextMenu.test.tsx src/app/views/canvas/CanvasShell.architecture.test.tsx',
      'node tools/ci/run-web-cypress-native.mjs --spec cypress/e2e/canvas/canvas-ready-node-authoring.cy.ts',
      'node --test scripts/planning-db-import.test.cjs',
      'pnpm governance:refresh',
      'pnpm verify:prepush'
    ),
    'redGreenCycles', jsonb_build_array(
      jsonb_build_object(
        'id', 'retire-fixed-add-node-palette',
        'redTest', 'pnpm --filter @dvt/web exec vitest run src/app/views/canvas/CanvasStateViews.test.tsx',
        'expectedFailure', 'Empty Canvas still mounted fixed first-node/palette insertion chrome.',
        'patchSurfaces', jsonb_build_array(
          'apps/web/src/app/views/canvas/CanvasStateViews.tsx',
          'apps/web/src/app/views/canvas/CanvasStateViews.test.tsx'
        ),
        'greenTest', 'pnpm --filter @dvt/web exec vitest run src/app/views/canvas/CanvasStateViews.test.tsx'
      ),
      jsonb_build_object(
        'id', 'support-delete-aware-governance-import',
        'redTest', 'node --test scripts/planning-db-import.test.cjs',
        'expectedFailure', 'Governance import tried to read deleted tracked files before the commit.',
        'patchSurfaces', jsonb_build_array(
          'scripts/planning-db-import.cjs',
          'scripts/planning-db/code-symbol-inventory.cjs',
          'scripts/planning-db/command-query-rail-catalog.cjs',
          'scripts/planning-db-import.test.cjs'
        ),
        'greenTest', 'node --test scripts/planning-db-import.test.cjs'
      )
    ),
    'symbols', jsonb_build_array(
      jsonb_build_object(
        'name', 'CanvasEmptyStateView',
        'path', 'apps/web/src/app/views/canvas/CanvasStateViews.tsx',
        'dddOwner', 'CanvasContextMenu',
        'cqRails', jsonb_build_array('RetireCanvasFixedAddNodePalette'),
        'fowlerSignals', jsonb_build_array('responsibility_overload'),
        'architectureGuard', 'apps/web/src/app/views/canvas/CanvasCenterSurface.architecture.test.ts',
        'cypressCoverage', 'node tools/ci/run-web-cypress-native.mjs --spec cypress/e2e/canvas/canvas-ready-node-authoring.cy.ts',
        'unitTests', jsonb_build_array('pnpm --filter @dvt/web exec vitest run src/app/views/canvas/CanvasStateViews.test.tsx')
      ),
      jsonb_build_object(
        'name', 'readTrackedDocumentPaths',
        'path', 'scripts/planning-db-import.cjs',
        'dddOwner', 'GovernanceImportDeleteAwareInventory',
        'cqRails', jsonb_build_array('RetireCanvasFixedAddNodePalette'),
        'fowlerSignals', jsonb_build_array('test_harness_overload'),
        'architectureGuard', 'pnpm governance:refresh',
        'cypressCoverage', 'not_applicable:planning_db_import_tool',
        'unitTests', jsonb_build_array('node --test scripts/planning-db-import.test.cjs')
      ),
      jsonb_build_object(
        'name', 'listTrackedCodeFiles',
        'path', 'scripts/planning-db/code-symbol-inventory.cjs',
        'dddOwner', 'GovernanceImportDeleteAwareInventory',
        'cqRails', jsonb_build_array('RetireCanvasFixedAddNodePalette'),
        'fowlerSignals', jsonb_build_array('test_harness_overload'),
        'architectureGuard', 'pnpm governance:refresh',
        'cypressCoverage', 'not_applicable:planning_db_import_tool',
        'unitTests', jsonb_build_array('node --test scripts/planning-db-import.test.cjs')
      ),
      jsonb_build_object(
        'name', 'readTrackedDocumentPaths',
        'path', 'scripts/planning-db/command-query-rail-catalog.cjs',
        'dddOwner', 'GovernanceImportDeleteAwareInventory',
        'cqRails', jsonb_build_array('RetireCanvasFixedAddNodePalette'),
        'fowlerSignals', jsonb_build_array('test_harness_overload'),
        'architectureGuard', 'pnpm governance:refresh',
        'cypressCoverage', 'not_applicable:planning_db_import_tool',
        'unitTests', jsonb_build_array('node --test scripts/planning-db-import.test.cjs')
      )
    )
  ),
  0,
  'codex'
)
on conflict (rail_id) do update set
  feature_id = excluded.feature_id,
  mechanization_status = excluded.mechanization_status,
  rail_name = excluded.rail_name,
  normalized_rail_name = excluded.normalized_rail_name,
  rail_type = excluded.rail_type,
  ddd_owner = excluded.ddd_owner,
  rail_status = excluded.rail_status,
  symbol_refs = excluded.symbol_refs,
  implementation_refs = excluded.implementation_refs,
  documentation_refs = excluded.documentation_refs,
  governing_sources = excluded.governing_sources,
  allowed_implementation_surfaces = excluded.allowed_implementation_surfaces,
  architecture_guards = excluded.architecture_guards,
  completion_gate = excluded.completion_gate,
  source_path = excluded.source_path,
  source_content_sha256 = excluded.source_content_sha256,
  raw_rail = excluded.raw_rail,
  raw_manifest = excluded.raw_manifest,
  revision = planning_query_store.feature_mechanization_local_rails.revision + 1,
  updated_at = now();
