export const codeViewCopy = {
  title: 'Code',
  subtitle: 'Browse workspace files and preview source content read-only.',
  readOnlyTitle: 'Read-only preview',
  readOnlyMessage: 'Browse workspace files here and hand off revision comparison to Diff.',
  readOnlyNote: 'Editing is not available in the Code route.',
  routeLoadingMessage: 'Loading workspace files...',
  routeEmptyTitle: 'No workspace files available',
  routeEmptyMessage: 'This workspace does not expose files to browse yet.',
  routeErrorTitle: 'Workspace files unavailable',
  routeErrorMessage: 'The file explorer could not be loaded right now.',
  previewLoadingMessage: 'Loading file preview...',
  previewEmptyTitle: 'Select a file to preview',
  previewEmptyMessage: 'Choose a file from the explorer to inspect its contents.',
  previewErrorTitle: 'File preview unavailable',
  previewErrorMessage: 'The selected file could not be loaded right now.',
  previewMissingTitle: 'Selected file unavailable',
  previewMissingMessagePrefix: 'The selected file is no longer available in this workspace:',
} as const;
