export const codeViewCopy = {
  title: 'Code',
  subtitle: 'Browse workspace files and edit a local Monaco buffer.',
  localBufferTitle: 'Editable local buffer',
  localBufferMessage: 'Type in Monaco while reviewing workspace files.',
  localBufferNote: 'Changes are local until a governed save command exists.',
  routeLoadingMessage: 'Loading workspace files...',
  routeEmptyTitle: 'No workspace files available',
  routeEmptyMessage: 'This workspace does not expose files to browse yet.',
  routeErrorTitle: 'Workspace files unavailable',
  routeErrorMessage: 'The file explorer could not be loaded right now.',
  previewLoadingMessage: 'Loading file preview...',
  previewEmptyTitle: 'Select a file to preview',
  previewEmptyMessage: 'Choose a file from the explorer to inspect its contents.',
  previewErrorTitle: 'File preview unavailable',
  previewErrorMessage: 'The selected file could not be loaded right now.',
  previewMissingTitle: 'Selected file unavailable',
  previewMissingMessagePrefix: 'The selected file is no longer available in this workspace:',
} as const;
