const assert = require('node:assert/strict');
const test = require('node:test');

const {
  buildRemediationQueueFromDbRows,
  buildRemediationQueue,
  isSpecificRail,
  readRemediationQueueFromDb,
  renderMarkdown,
} = require('./generate-governance-remediation-queue.cjs');

const coverageReport = {
  totals: {
    driftFiles: 2,
    componentsRequiringSubdivision: 2,
  },
};

const fileIndex = {
  files: [
    {
      path: 'packages/@dvt/engine/src/application/RecoverRunApplicationService.ts',
      fileId: 'FILE-ENGINE-RECOVER',
      componentUnit: 'SYS-RUNTIME-ROOT',
      rootUnit: 'SYS-RUNTIME',
      domainUnit: 'SYS-RUNTIME',
      dddOwner: 'AS',
      cqRails: 'runtime commands and queries',
      unitStatus: 'drift',
      isDrift: true,
    },
    {
      path: 'packages/@dvt/engine/src/application/StartRunAdmissionGuard.ts',
      fileId: 'FILE-ENGINE-ADMISSION',
      componentUnit: 'SYS-RUNTIME-ROOT',
      rootUnit: 'SYS-RUNTIME',
      domainUnit: 'SYS-RUNTIME',
      dddOwner: 'AS',
      cqRails: 'runtime commands and queries',
      unitStatus: 'canonical',
      isDrift: false,
    },
  ],
};

const componentIndex = {
  components: [
    {
      id: 'SYS-RUNTIME-ROOT',
      rootUnit: 'SYS-RUNTIME',
      domainUnit: 'SYS-RUNTIME',
      dddOwner: 'AS',
      cqRails: 'runtime commands and queries',
      status: 'drift',
      fileCount: 320,
      childrenRequired: true,
    },
    {
      id: 'SYS-PLANSTORE-POSTGRES',
      rootUnit: 'SYS-PLANSTORE',
      domainUnit: 'SYS-PLANSTORE',
      dddOwner: 'ADP',
      cqRails: 'PS-Q03, PS-C04',
      status: 'review',
      fileCount: 12,
      childrenRequired: false,
    },
  ],
};

const componentFileMap = {
  components: [
    {
      id: 'SYS-RUNTIME-ROOT',
      path: 'docs/planning/status/governance-components/SYS-RUNTIME-ROOT.component-files.yaml',
    },
    {
      id: 'SYS-PLANSTORE-POSTGRES',
      path: 'docs/planning/status/governance-components/SYS-PLANSTORE-POSTGRES.component-files.yaml',
    },
  ],
};

const documentMap = {
  documents: [
    {
      path: 'docs/planning/status/system-operations-inventory-20260501.md',
      classification: 'tracks drift',
      subjectUnit: 'SYS-RUNTIME-ROOT',
      documentOwnerUnit: 'SYS-DOCS-GOVERNANCE-ROOT',
    },
    {
      path: 'docs/guides/testing-and-ci-capabilities.md',
      classification: 'governs unit',
      subjectUnit: 'SYS-CI-GOVERNANCE-ROOT',
      documentOwnerUnit: 'SYS-DOCS-GOVERNANCE-ROOT',
    },
  ],
};

test('buildRemediationQueue groups drift, subdivision, rail and doc tasks', () => {
  const queue = buildRemediationQueue({
    coverageReport,
    fileIndex,
    componentIndex,
    componentFileMap,
    documentMap,
  });

  assert.equal(queue.totals.driftFiles, 2);
  assert.equal(queue.totals.componentsRequiringSubdivision, 2);

  const tasksByType = new Map(queue.tasks.map((task) => [task.type, task]));
  assert.equal(tasksByType.get('drift-removal').priority, 'P0');
  assert.equal(tasksByType.get('drift-removal').componentUnit, 'SYS-RUNTIME-ROOT');
  assert.equal(
    tasksByType.get('drift-removal').componentFileMap,
    'docs/planning/status/governance-components/SYS-RUNTIME-ROOT.component-files.yaml'
  );
  assert.equal(tasksByType.get('drift-removal').fileCount, 1);
  assert.equal(tasksByType.get('cq-rail-gap').priority, 'P1');
  assert.equal(tasksByType.get('component-subdivision').priority, 'P1');
  assert.equal(tasksByType.get('doc-alignment').documentCount, 1);
});

test('isSpecificRail accepts explicit rails and rejects generic rail language', () => {
  assert.equal(isSpecificRail('PS-Q03, PS-C04'), true);
  assert.equal(isSpecificRail('none - repository automation'), true);
  assert.equal(isSpecificRail('runtime commands and queries'), false);
});

test('renderMarkdown declares the generated artifact marker', () => {
  const queue = buildRemediationQueue({
    coverageReport,
    fileIndex,
    componentIndex,
    componentFileMap,
    documentMap,
  });

  assert.match(renderMarkdown(queue), /auto-generated by `pnpm docs:governance:remediation-queue`/);
});

test('buildRemediationQueueFromDbRows preserves DB-owned task payloads', () => {
  const queue = buildRemediationQueueFromDbRows({
    remediationRows: [
      {
        task_id: 'GRQ-DRIFT_REMOVAL-SYS-RUNTIME-ROOT',
        task_type: 'drift-removal',
        priority: 'P0',
        component_unit: 'SYS-RUNTIME-ROOT',
        component_file_map:
          '.generated-docs/planning/status/governance-components/SYS-RUNTIME-ROOT.component-files.yaml',
        root_unit: 'SYS-RUNTIME',
        domain_unit: 'SYS-RUNTIME',
        ddd_owner: 'AS',
        cq_rails: 'runtime commands and queries',
        blocking: 'changed-files gate blocks touched drift files',
        reason: 'Files are marked drift in the governed file index.',
        file_count: 1,
        document_count: 0,
        files: [
          {
            path: 'packages/@dvt/engine/src/application/RecoverRunApplicationService.ts',
            fileId: 'FILE-ENGINE-RECOVER',
            status: 'drift',
          },
        ],
        documents: [],
        expected_validation: ['pnpm docs:governance:remediation-queue:check'],
        raw_task: {
          id: 'GRQ-DRIFT_REMOVAL-SYS-RUNTIME-ROOT',
          type: 'drift-removal',
          priority: 'P0',
          componentUnit: 'SYS-RUNTIME-ROOT',
          componentFileMap:
            '.generated-docs/planning/status/governance-components/SYS-RUNTIME-ROOT.component-files.yaml',
          rootUnit: 'SYS-RUNTIME',
          domainUnit: 'SYS-RUNTIME',
          dddOwner: 'AS',
          cqRails: 'runtime commands and queries',
          blocking: 'changed-files gate blocks touched drift files',
          reason: 'Files are marked drift in the governed file index.',
          fileCount: 1,
          documentCount: 0,
          files: [
            {
              path: 'packages/@dvt/engine/src/application/RecoverRunApplicationService.ts',
              fileId: 'FILE-ENGINE-RECOVER',
              status: 'drift',
            },
          ],
          documents: [],
          expectedValidation: ['pnpm docs:governance:remediation-queue:check'],
        },
      },
    ],
    coverageRows: [
      { coverage_kind: 'total', name: 'driftFiles', count_value: 2 },
      {
        coverage_kind: 'total',
        name: 'componentsRequiringSubdivision',
        count_value: 2,
      },
    ],
  });

  assert.deepEqual(queue.generatedFrom, [
    'planning_query_store.governance_remediation_query',
    'planning_query_store.governance_coverage_query',
  ]);
  assert.equal(queue.totals.tasks, 1);
  assert.equal(queue.totals.p0, 1);
  assert.equal(queue.totals.driftFiles, 2);
  assert.equal(queue.tasks[0].files[0].fileId, 'FILE-ENGINE-RECOVER');
});

test('readRemediationQueueFromDb reads remediation and coverage query views', async () => {
  const queries = [];
  const client = {
    async query(sql) {
      queries.push(sql);

      if (sql.includes('governance_remediation_query')) {
        return {
          rows: [
            {
              task_id: 'GRQ-DRIFT_REMOVAL-SYS-RUNTIME-ROOT',
              task_type: 'drift-removal',
              priority: 'P0',
              component_unit: 'SYS-RUNTIME-ROOT',
              component_file_map:
                '.generated-docs/planning/status/governance-components/SYS-RUNTIME-ROOT.component-files.yaml',
              root_unit: 'SYS-RUNTIME',
              domain_unit: 'SYS-RUNTIME',
              ddd_owner: 'AS',
              cq_rails: 'runtime commands and queries',
              blocking: 'changed-files gate blocks touched drift files',
              reason: 'Files are marked drift in the governed file index.',
              file_count: 1,
              document_count: 0,
              files: [
                {
                  path: 'packages/@dvt/engine/src/application/RecoverRunApplicationService.ts',
                  fileId: 'FILE-ENGINE-RECOVER',
                  status: 'drift',
                },
              ],
              documents: [],
              expected_validation: ['pnpm docs:governance:remediation-queue:check'],
              raw_task: null,
            },
          ],
        };
      }

      if (sql.includes('governance_coverage_query')) {
        return {
          rows: [
            { coverage_kind: 'total', name: 'driftFiles', count_value: 2 },
            {
              coverage_kind: 'total',
              name: 'componentsRequiringSubdivision',
              count_value: 2,
            },
          ],
        };
      }

      throw new Error(`Unexpected SQL: ${sql}`);
    },
  };

  const queue = await readRemediationQueueFromDb(client);
  const capturedSql = queries.join('\n');

  assert.equal(queue.totals.tasks, 1);
  assert.equal(queue.totals.driftFiles, 2);
  assert.equal(queue.tasks[0].id, 'GRQ-DRIFT_REMOVAL-SYS-RUNTIME-ROOT');
  assert.match(capturedSql, /from planning_query_store\.governance_remediation_query/);
  assert.match(capturedSql, /from planning_query_store\.governance_coverage_query/);
  assert.doesNotMatch(capturedSql, /\.generated-docs/);
  assert.doesNotMatch(capturedSql, /system-governance-remediation-queue\.queue\.yaml/);
});
