const assert = require('node:assert/strict');
const test = require('node:test');

const {
  buildRemediationQueue,
  isSpecificRail,
  renderMarkdown,
} = require('./generate-governance-remediation-queue.cjs');

const coverageReport = {
  totals: {
    driftFiles: 2,
    componentsRequiringSubdivision: 2,
  },
};

const fileIndex = {
  files: [
    {
      path: 'packages/@dvt/engine/src/application/RecoverRunApplicationService.ts',
      fileId: 'FILE-ENGINE-RECOVER',
      componentUnit: 'SYS-RUNTIME-ROOT',
      rootUnit: 'SYS-RUNTIME',
      domainUnit: 'SYS-RUNTIME',
      dddOwner: 'AS',
      cqRails: 'runtime commands and queries',
      unitStatus: 'drift',
      isDrift: true,
    },
    {
      path: 'packages/@dvt/engine/src/application/StartRunAdmissionGuard.ts',
      fileId: 'FILE-ENGINE-ADMISSION',
      componentUnit: 'SYS-RUNTIME-ROOT',
      rootUnit: 'SYS-RUNTIME',
      domainUnit: 'SYS-RUNTIME',
      dddOwner: 'AS',
      cqRails: 'runtime commands and queries',
      unitStatus: 'canonical',
      isDrift: false,
    },
  ],
};

const componentIndex = {
  components: [
    {
      id: 'SYS-RUNTIME-ROOT',
      rootUnit: 'SYS-RUNTIME',
      domainUnit: 'SYS-RUNTIME',
      dddOwner: 'AS',
      cqRails: 'runtime commands and queries',
      status: 'drift',
      fileCount: 320,
      childrenRequired: true,
    },
    {
      id: 'SYS-PLANSTORE-POSTGRES',
      rootUnit: 'SYS-PLANSTORE',
      domainUnit: 'SYS-PLANSTORE',
      dddOwner: 'ADP',
      cqRails: 'PS-Q03, PS-C04',
      status: 'review',
      fileCount: 12,
      childrenRequired: false,
    },
  ],
};

const documentMap = {
  documents: [
    {
      path: 'docs/planning/status/system-operations-inventory-20260501.md',
      classification: 'tracks drift',
      subjectUnit: 'SYS-RUNTIME-ROOT',
      documentOwnerUnit: 'SYS-DOCS-GOVERNANCE-ROOT',
    },
    {
      path: 'docs/guides/testing-and-ci-capabilities.md',
      classification: 'governs unit',
      subjectUnit: 'SYS-CI-GOVERNANCE-ROOT',
      documentOwnerUnit: 'SYS-DOCS-GOVERNANCE-ROOT',
    },
  ],
};

test('buildRemediationQueue groups drift, subdivision, rail and doc tasks', () => {
  const queue = buildRemediationQueue({
    coverageReport,
    fileIndex,
    componentIndex,
    documentMap,
  });

  assert.equal(queue.totals.driftFiles, 2);
  assert.equal(queue.totals.componentsRequiringSubdivision, 2);

  const tasksByType = new Map(queue.tasks.map((task) => [task.type, task]));
  assert.equal(tasksByType.get('drift-removal').priority, 'P0');
  assert.equal(tasksByType.get('drift-removal').componentUnit, 'SYS-RUNTIME-ROOT');
  assert.equal(tasksByType.get('drift-removal').fileCount, 1);
  assert.equal(tasksByType.get('cq-rail-gap').priority, 'P1');
  assert.equal(tasksByType.get('component-subdivision').priority, 'P1');
  assert.equal(tasksByType.get('doc-alignment').documentCount, 1);
});

test('isSpecificRail accepts explicit rails and rejects generic rail language', () => {
  assert.equal(isSpecificRail('PS-Q03, PS-C04'), true);
  assert.equal(isSpecificRail('none - repository automation'), true);
  assert.equal(isSpecificRail('runtime commands and queries'), false);
});

test('renderMarkdown declares the generated artifact marker', () => {
  const queue = buildRemediationQueue({
    coverageReport,
    fileIndex,
    componentIndex,
    documentMap,
  });

  assert.match(renderMarkdown(queue), /auto-generated by `pnpm docs:governance:remediation-queue`/);
});
