const test = require('node:test');
const assert = require('node:assert/strict');
const {
  buildCoverageReport,
  countGovernanceDocuments,
  readCoverageReportFromDb,
  renderMarkdown,
} = require('./generate-governance-coverage-report.cjs');

const fileIndex = {
  files: [
    {
      path: 'apps/api/src/main.ts',
      owningUnit: 'SYS-API-ROOT',
      rootUnit: 'SYS-DVT',
      domainUnit: 'SYS-API',
      componentUnit: 'SYS-API-ROOT',
      unitStatus: 'coverage-required',
      governanceState: 'coverage-required',
      canonicalRole: 'none',
      evidenceState: 'coverage-required',
      dddOwner: 'AS',
      isDrift: false,
      isLegacy: false,
      governance: ['docs/api.md'],
    },
    {
      path: 'apps/api/src/legacy/store.ts',
      owningUnit: 'SYS-PLANSTORE-LEGACY',
      rootUnit: 'SYS-DVT',
      domainUnit: 'SYS-API',
      componentUnit: 'SYS-PLANSTORE-LEGACY',
      unitStatus: 'legacy',
      governanceState: 'legacy',
      canonicalRole: 'none',
      evidenceState: 'remediation-required',
      dddOwner: 'ADP',
      isDrift: true,
      isLegacy: true,
      governance: ['docs/planstore.md', 'docs/api.md'],
    },
    {
      path: 'tmp/unowned.txt',
      owningUnit: 'UNOWNED',
      rootUnit: 'UNOWNED',
      domainUnit: 'UNOWNED',
      componentUnit: 'UNOWNED',
      unitStatus: 'unknown',
      governanceState: 'ungoverned',
      canonicalRole: 'none',
      evidenceState: 'remediation-required',
      dddOwner: 'N/A',
      isDrift: false,
      isLegacy: false,
      governance: [],
    },
  ],
};

const componentIndex = {
  components: [
    {
      id: 'SYS-API-ROOT',
      name: 'API root',
      rootUnit: 'SYS-DVT',
      domainUnit: 'SYS-API',
      status: 'coverage-required',
      governanceState: 'coverage-required',
      canonicalRole: 'none',
      evidenceState: 'coverage-required',
      dddOwner: 'AS',
      cqRails: 'API commands and queries',
      fileCount: 1,
      childrenRequired: true,
      isDrift: false,
      isLegacy: false,
      governance: ['docs/api.md'],
    },
    {
      id: 'SYS-PLANSTORE-LEGACY',
      name: 'Plan store legacy',
      rootUnit: 'SYS-DVT',
      domainUnit: 'SYS-API',
      status: 'legacy',
      governanceState: 'legacy',
      canonicalRole: 'none',
      evidenceState: 'remediation-required',
      dddOwner: 'ADP',
      cqRails: 'PS-Q04',
      fileCount: 1,
      childrenRequired: false,
      isDrift: true,
      isLegacy: true,
      governance: ['docs/planstore.md'],
    },
  ],
};

test('buildCoverageReport aggregates governed, drift, legacy, and ungoverned files', () => {
  const report = buildCoverageReport(fileIndex, componentIndex);

  assert.deepEqual(report.totals, {
    files: 3,
    governedFiles: 2,
    ungovernedFiles: 1,
    driftFiles: 1,
    legacyFiles: 1,
    components: 2,
    componentsRequiringSubdivision: 1,
  });
  assert.deepEqual(report.findings.unownedFiles, ['tmp/unowned.txt']);
  assert.deepEqual(report.byGovernanceState, [
    { name: 'coverage-required', count: 1 },
    { name: 'legacy', count: 1 },
    { name: 'ungoverned', count: 1 },
  ]);
  assert.deepEqual(report.byCanonicalRole, [{ name: 'none', count: 3 }]);
  assert.deepEqual(report.byEvidenceState, [
    { name: 'coverage-required', count: 1 },
    { name: 'remediation-required', count: 2 },
  ]);
  assert.deepEqual(report.findings.driftFiles, [
    {
      path: 'apps/api/src/legacy/store.ts',
      owningUnit: 'SYS-PLANSTORE-LEGACY',
      status: 'legacy',
      componentUnit: 'SYS-PLANSTORE-LEGACY',
    },
  ]);
  assert.equal(
    report.ciPosture.enforcedBy.includes('pnpm docs:governance:changed-files:check'),
    true
  );
});

test('countGovernanceDocuments counts shared governance sources', () => {
  assert.deepEqual(countGovernanceDocuments(fileIndex.files), [
    { path: 'docs/api.md', fileCount: 2 },
    { path: 'docs/planstore.md', fileCount: 1 },
  ]);
});

test('renderMarkdown includes generated marker and finding tables', () => {
  const markdown = renderMarkdown(buildCoverageReport(fileIndex, componentIndex));

  assert.match(markdown, /auto-generated by `pnpm docs:governance:coverage-report`/);
  assert.match(markdown, /By Governance State/);
  assert.match(markdown, /By Canonical Role/);
  assert.match(markdown, /By Evidence State/);
  assert.match(markdown, /apps\/api\/src\/legacy\/store\.ts/);
  assert.match(markdown, /SYS-API-ROOT/);
});

test('readCoverageReportFromDb reads governance query views as the report source', async () => {
  const queries = [];
  const client = {
    async query(sql) {
      queries.push(sql);

      if (sql.includes('governance_file_query')) {
        return {
          rows: [
            {
              path: 'apps/api/src/main.ts',
              file_id: 'FILE-API-MAIN',
              owning_unit: 'SYS-API-ROOT',
              root_unit: 'SYS-DVT',
              domain_unit: 'SYS-API',
              component_unit: 'SYS-API-ROOT',
              owner_level: 'component',
              unit_status: 'coverage-required',
              governance_state: 'coverage-required',
              canonical_role: 'none',
              evidence_state: 'coverage-required',
              is_drift: false,
              is_legacy: false,
              ddd_owner: 'AS',
              cq_rails: 'API-Q01',
              governance_refs: ['docs/api.md'],
            },
            {
              path: 'apps/api/src/legacy/store.ts',
              file_id: 'FILE-API-LEGACY',
              owning_unit: 'SYS-PLANSTORE-LEGACY',
              root_unit: 'SYS-DVT',
              domain_unit: 'SYS-API',
              component_unit: 'SYS-PLANSTORE-LEGACY',
              owner_level: 'component',
              unit_status: 'legacy',
              governance_state: 'legacy',
              canonical_role: 'none',
              evidence_state: 'remediation-required',
              is_drift: true,
              is_legacy: true,
              ddd_owner: 'ADP',
              cq_rails: 'PS-Q04',
              governance_refs: ['docs/planstore.md', 'docs/api.md'],
            },
          ],
        };
      }

      if (sql.includes('governance_component_query')) {
        return {
          rows: [
            {
              component_id: 'SYS-API-ROOT',
              name: 'API root',
              root_unit: 'SYS-DVT',
              domain_unit: 'SYS-API',
              status: 'coverage-required',
              governance_state: 'coverage-required',
              canonical_role: 'none',
              evidence_state: 'coverage-required',
              ddd_owner: 'AS',
              cq_rails: 'API-Q01',
              file_count: 1,
              children_required: true,
              is_drift: false,
              is_legacy: false,
              governance_refs: ['docs/api.md'],
            },
            {
              component_id: 'SYS-PLANSTORE-LEGACY',
              name: 'Plan store legacy',
              root_unit: 'SYS-DVT',
              domain_unit: 'SYS-API',
              status: 'legacy',
              governance_state: 'legacy',
              canonical_role: 'none',
              evidence_state: 'remediation-required',
              ddd_owner: 'ADP',
              cq_rails: 'PS-Q04',
              file_count: 1,
              children_required: false,
              is_drift: true,
              is_legacy: true,
              governance_refs: ['docs/planstore.md'],
            },
          ],
        };
      }

      throw new Error(`Unexpected SQL: ${sql}`);
    },
  };

  const report = await readCoverageReportFromDb(client);
  const capturedSql = queries.join('\n');

  assert.equal(report.totals.files, 2);
  assert.equal(report.totals.driftFiles, 1);
  assert.deepEqual(report.governanceDocuments, [
    { path: 'docs/api.md', fileCount: 2 },
    { path: 'docs/planstore.md', fileCount: 1 },
  ]);
  assert.match(capturedSql, /from planning_query_store\.governance_file_query/);
  assert.match(capturedSql, /from planning_query_store\.governance_component_query/);
  assert.doesNotMatch(capturedSql, /\.generated-docs/);
  assert.doesNotMatch(capturedSql, /system-governance-file-index\.files\.yaml/);
});
