const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');

const repoRoot = path.resolve(__dirname, '..');
const generatorPath = path.join(repoRoot, 'scripts', 'generate-code-status.cjs');
const policyPath = path.join(repoRoot, 'docs', 'generated-docs-policy.json');

const {
  renderRepositoryMap,
  resolveWorkspaceArchitecture,
} = require('./generate-code-status.cjs');

test('code status generator renders the generated inventory outside tracked docs', () => {
  const source = fs.readFileSync(generatorPath, 'utf8');

  assert.match(source, /'\.generated-docs'/);
  assert.match(source, /'planning'[\s\S]*'status'[\s\S]*'generated-code-state\.md'/);
  assert.doesNotMatch(
    source,
    /const outputPath = path\.join\(repoRoot, 'docs', 'planning', 'status', 'generated-code-state\.md'\)/
  );
});

test('generated docs policy treats generated code state as an untracked local artifact', () => {
  const policy = JSON.parse(fs.readFileSync(policyPath, 'utf8'));
  const codeStatePolicy = policy.artifactClasses.find(
    (entry) => entry.id === 'local-docs-status-code-state'
  );

  assert.ok(codeStatePolicy);
  assert.deepEqual(codeStatePolicy.artifacts, [
    '.generated-docs/planning/status/generated-code-state.md',
  ]);
  assert.equal(codeStatePolicy.tracking, 'untracked');
});

test('repository map resolves only an exact Planning DB repository path', () => {
  const workspace = { path: 'apps/web' };
  const components = [
    {
      component_id: 'SYS-WEB-ROOT',
      repo_path: 'apps/web',
      status: 'implemented',
    },
    {
      component_id: 'SYS-WEB-NESTED',
      repo_path: 'apps/web/src/app',
      status: 'implemented',
    },
  ];
  const documents = [
    {
      subject_key: 'SYS-WEB-ROOT',
      document_path: 'docs/architecture/components/web/index.md',
      canonicality: 'canonical',
      lifecycle_state: 'current',
      status: 'Active',
    },
  ];

  assert.deepEqual(resolveWorkspaceArchitecture(workspace, components, documents), {
    component: 'SYS-WEB-ROOT',
    componentStatus: 'implemented',
    canonicalDoc:
      '[docs/architecture/components/web/index.md](../architecture/components/web/index.md)',
    gaps: [],
  });
});

test('repository map exposes missing and ambiguous Planning DB identity instead of guessing', () => {
  const workspace = { path: 'packages/@dvt/example' };

  assert.deepEqual(resolveWorkspaceArchitecture(workspace, [], []), {
    component: '-',
    componentStatus: '-',
    canonicalDoc: '-',
    gaps: ['unregistered-component'],
  });

  const ambiguous = resolveWorkspaceArchitecture(
    workspace,
    [
      { component_id: 'COMP-A', repo_path: workspace.path, status: 'implemented' },
      { component_id: 'COMP-B', repo_path: workspace.path, status: 'implemented' },
    ],
    []
  );
  assert.deepEqual(ambiguous, {
    component: 'COMP-A, COMP-B',
    componentStatus: '-',
    canonicalDoc: '-',
    gaps: ['ambiguous-component'],
  });
});

test('repository map output replaces manual responsibility and coverage inventories', () => {
  const output = renderRepositoryMap(
    [
      {
        workspace: '@dvt/example',
        path: 'packages/@dvt/example',
        kind: 'package',
        src: 2,
        tests: 1,
        hasBuild: 'yes',
        hasTest: 'yes',
        hasTypecheck: 'yes',
      },
    ],
    {
      components: [
        {
          component_id: 'COMP-EXAMPLE',
          repo_path: 'packages/@dvt/example',
          status: 'implemented',
        },
      ],
      documents: [],
    },
    '2026-08-02'
  );

  assert.match(output, /architecture\.component_query/);
  assert.match(output, /missing-doc-entry/);
  assert.match(
    output,
    /This page is auto-generated by `pnpm docs:status:generate`\. Do not edit manually\./
  );
  assert.doesNotMatch(output, /## Coverage Classes/);
  assert.doesNotMatch(output, /Responsibility/);
});
