const test = require('node:test');
const assert = require('node:assert/strict');
const {
  buildCoverageReport,
  countGovernanceDocuments,
  renderMarkdown,
} = require('./generate-governance-coverage-report.cjs');

const fileIndex = {
  files: [
    {
      path: 'apps/api/src/main.ts',
      owningUnit: 'SYS-API-ROOT',
      rootUnit: 'SYS-DVT',
      domainUnit: 'SYS-API',
      componentUnit: 'SYS-API-ROOT',
      unitStatus: 'coverage-required',
      dddOwner: 'AS',
      isDrift: false,
      isLegacy: false,
      governance: ['docs/api.md'],
    },
    {
      path: 'apps/api/src/legacy/store.ts',
      owningUnit: 'SYS-PLANSTORE-LEGACY',
      rootUnit: 'SYS-DVT',
      domainUnit: 'SYS-API',
      componentUnit: 'SYS-PLANSTORE-LEGACY',
      unitStatus: 'legacy',
      dddOwner: 'ADP',
      isDrift: true,
      isLegacy: true,
      governance: ['docs/planstore.md', 'docs/api.md'],
    },
    {
      path: 'tmp/unowned.txt',
      owningUnit: 'UNOWNED',
      rootUnit: 'UNOWNED',
      domainUnit: 'UNOWNED',
      componentUnit: 'UNOWNED',
      unitStatus: 'unknown',
      dddOwner: 'N/A',
      isDrift: false,
      isLegacy: false,
      governance: [],
    },
  ],
};

const componentIndex = {
  components: [
    {
      id: 'SYS-API-ROOT',
      name: 'API root',
      rootUnit: 'SYS-DVT',
      domainUnit: 'SYS-API',
      status: 'coverage-required',
      dddOwner: 'AS',
      cqRails: 'API commands and queries',
      fileCount: 1,
      childrenRequired: true,
      isDrift: false,
      isLegacy: false,
      governance: ['docs/api.md'],
    },
    {
      id: 'SYS-PLANSTORE-LEGACY',
      name: 'Plan store legacy',
      rootUnit: 'SYS-DVT',
      domainUnit: 'SYS-API',
      status: 'legacy',
      dddOwner: 'ADP',
      cqRails: 'PS-Q04',
      fileCount: 1,
      childrenRequired: false,
      isDrift: true,
      isLegacy: true,
      governance: ['docs/planstore.md'],
    },
  ],
};

test('buildCoverageReport aggregates governed, drift, legacy, and ungoverned files', () => {
  const report = buildCoverageReport(fileIndex, componentIndex);

  assert.deepEqual(report.totals, {
    files: 3,
    governedFiles: 2,
    ungovernedFiles: 1,
    driftFiles: 1,
    legacyFiles: 1,
    components: 2,
    componentsRequiringSubdivision: 1,
  });
  assert.deepEqual(report.findings.unownedFiles, ['tmp/unowned.txt']);
  assert.deepEqual(report.findings.driftFiles, [
    {
      path: 'apps/api/src/legacy/store.ts',
      owningUnit: 'SYS-PLANSTORE-LEGACY',
      status: 'legacy',
      componentUnit: 'SYS-PLANSTORE-LEGACY',
    },
  ]);
  assert.equal(
    report.ciPosture.enforcedBy.includes('pnpm docs:governance:changed-files:check'),
    true
  );
});

test('countGovernanceDocuments counts shared governance sources', () => {
  assert.deepEqual(countGovernanceDocuments(fileIndex.files), [
    { path: 'docs/api.md', fileCount: 2 },
    { path: 'docs/planstore.md', fileCount: 1 },
  ]);
});

test('renderMarkdown includes generated marker and finding tables', () => {
  const markdown = renderMarkdown(buildCoverageReport(fileIndex, componentIndex));

  assert.match(markdown, /auto-generated by `pnpm docs:governance:coverage-report`/);
  assert.match(markdown, /apps\/api\/src\/legacy\/store\.ts/);
  assert.match(markdown, /SYS-API-ROOT/);
});
