/**
 * Owned concern: validate that autogenerated documentation page extraction
 * is governed by a canonical component contract instead of ad hoc generated-file churn.
 */
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';

const requiredFiles = [
  'docs/planning/proposals/mandatory/governance-and-docs/autogenerated-pages-canon-plan-20260524.md',
  'docs/architecture/components/ci-governance/autogenerated-pages-canon-component.md',
  'docs/architecture/components/ci-governance/autogenerated-pages-canon-user-stories.md',
  'docs/planning/domains/documentation-governance.md',
  'docs/runbooks/planning-generated-artifacts-operations-20260403.md',
  'docs/planning/proposals/mandatory/governance-and-docs/autogenerated-pages-extraction-plan-20260403.md',
  'buzon/20260524-codex-fowler-autogenerated-pages-canon.md',
];

const requiredRails = [
  'ClassifyGeneratedDocsSurface',
  'ExtractGeneratedDocsSurface',
  'ValidateGeneratedDocsArtifact',
];

function readRepoFile(path) {
  return readFileSync(new URL(`../../${path}`, import.meta.url), 'utf8');
}

function assertContains(path, expected) {
  assert.match(
    readRepoFile(path),
    typeof expected === 'string' ? new RegExp(escapeRegExp(expected)) : expected,
    `${path} must contain ${expected.toString()}`
  );
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

test('autogenerated pages canonization preserves generated-surface ownership and extraction rails', () => {
  for (const path of requiredFiles) {
    assert.doesNotThrow(() => readRepoFile(path), `${path} must exist`);
  }

  for (const path of requiredFiles) {
    for (const rail of requiredRails) {
      assertContains(path, rail);
    }
  }

  assertContains(
    'docs/planning/domains/documentation-governance.md',
    'Autogenerated Pages Canon Plan 2026-05-24'
  );
  assertContains('docs/planning/domains/documentation-governance.md', 'GD-MAND-AUTOGEN-PAGES');
  assertContains(
    'docs/runbooks/planning-generated-artifacts-operations-20260403.md',
    'Generated Surface Registry'
  );
  assertContains('docs/runbooks/planning-generated-artifacts-operations-20260403.md', 'must-track');
  assertContains(
    'docs/runbooks/planning-generated-artifacts-operations-20260403.md',
    'candidate-for-extraction'
  );

  const componentGuide = readRepoFile(
    'docs/architecture/components/ci-governance/autogenerated-pages-canon-component.md'
  );
  for (const requiredHeading of [
    '## Public API',
    '## Invariants',
    '## Transitions',
    '## Consumers',
    '## Command And Query Rail',
    '## Semantic Fitness Function',
  ]) {
    assert.match(componentGuide, new RegExp(escapeRegExp(requiredHeading)));
  }

  const userStories = readRepoFile(
    'docs/architecture/components/ci-governance/autogenerated-pages-canon-user-stories.md'
  );
  for (const persona of [
    'Documentation maintainer',
    'Governance operator',
    'Architecture reviewer',
    'Contributor',
  ]) {
    assert.match(userStories, new RegExp(escapeRegExp(persona)));
  }

  const analysis = readRepoFile('buzon/20260524-codex-fowler-autogenerated-pages-canon.md');
  for (const section of [
    '## Fowler Analysis',
    '## Mature-System Comparison',
    '## Antipatterns',
    '## Drift',
    '## Applied Pattern',
  ]) {
    assert.match(analysis, new RegExp(escapeRegExp(section)));
  }
});
