/**
 * Owned concern: validate that autogenerated documentation page extraction
 * is governed by a canonical component contract instead of ad hoc generated-file churn.
 */
import assert from 'node:assert/strict';
import { test } from 'node:test';

import {
  assertCanonPlan,
  assertContains,
  assertFilesExist,
  escapeRegExp,
  readRepoFile,
} from './canonization-guard.mjs';

const requiredFiles = [
  'docs/planning/proposals/mandatory/governance-and-docs/autogenerated-pages-canon-plan-20260524.md',
  'docs/architecture/components/ci-governance/autogenerated-pages-canon-component.md',
  'docs/architecture/components/ci-governance/autogenerated-pages-canon-user-stories.md',
  'docs/planning/domains/documentation-governance.md',
  'docs/planning/proposals/mandatory/governance-and-docs/autogenerated-pages-extraction-plan-20260403.md',
];

const requiredRails = [
  'ClassifyGeneratedDocsSurface',
  'ExtractGeneratedDocsSurface',
  'ValidateGeneratedDocsArtifact',
];

test('autogenerated pages canonization preserves generated-surface ownership and extraction rails', () => {
  assertFilesExist(requiredFiles);
  assertCanonPlan(
    'docs/planning/proposals/mandatory/governance-and-docs/autogenerated-pages-canon-plan-20260524.md'
  );

  for (const path of requiredFiles) {
    for (const rail of requiredRails) {
      assertContains(path, rail);
    }
  }

  assertContains(
    'docs/planning/domains/documentation-governance.md',
    'Autogenerated Pages Canon Plan 2026-05-24'
  );
  assertContains('docs/planning/domains/documentation-governance.md', 'GD-MAND-AUTOGEN-PAGES');

  const componentGuide = readRepoFile(
    'docs/architecture/components/ci-governance/autogenerated-pages-canon-component.md'
  );
  for (const requiredHeading of [
    '## Public API',
    '## Invariants',
    '## Transitions',
    '## Consumers',
    '## Command And Query Rail',
    '## Semantic Fitness Function',
  ]) {
    assert.match(componentGuide, new RegExp(escapeRegExp(requiredHeading)));
  }

  const userStories = readRepoFile(
    'docs/architecture/components/ci-governance/autogenerated-pages-canon-user-stories.md'
  );
  for (const persona of [
    'Documentation maintainer',
    'Governance operator',
    'Architecture reviewer',
    'Contributor',
  ]) {
    assert.match(userStories, new RegExp(escapeRegExp(persona)));
  }
});
