/** Owned concern: localized Source Columns presentation copy. */
export const sourceColumnsCopy = {
  en: {
    search: 'Search columns...',
    columns: 'Columns',
    filter: 'Filter columns',
    all: 'All columns',
    key: 'Key columns',
    notNull: 'Not null',
    nullable: 'Nullable',
    noColumns: 'No columns are available for this Source.',
    noMatches: 'No columns match the current search or filter.',
    unavailable: 'This column is no longer available in the Source.',
    unknown: 'Not available',
    exactType: 'Physical type',
    nullability: 'Nullability',
    constraints: 'Constraint',
    primaryKey: 'Primary key',
    unique: 'Unique',
    none: '—',
    listLabel: 'Source columns',
    reorderHint: 'Drag or press Alt+Up/Down to reorder.',
    transferHint: 'Drag this column onto a Model to add it to Input.',
    reordered: 'Column reordered',
    previous: 'Previous',
    next: 'Next',
    back: 'Back to columns',
  },
  es: {
    search: 'Buscar columnas...',
    columns: 'Columnas',
    filter: 'Filtrar columnas',
    all: 'Todas las columnas',
    key: 'Columnas clave',
    notNull: 'No nulo',
    nullable: 'Admite nulos',
    noColumns: 'No hay columnas disponibles para este origen.',
    noMatches: 'Ninguna columna coincide con la búsqueda o el filtro.',
    unavailable: 'Esta columna ya no está disponible en el origen.',
    unknown: 'No disponible',
    exactType: 'Tipo físico',
    nullability: 'Nulabilidad',
    constraints: 'Restricción',
    primaryKey: 'Clave primaria',
    unique: 'Única',
    none: '—',
    listLabel: 'Columnas del origen',
    reorderHint: 'Arrastra o pulsa Alt+Arriba/Abajo para reordenar.',
    transferHint: 'Arrastra esta columna a un modelo para añadirla a Input.',
    reordered: 'Columna reordenada',
    previous: 'Anterior',
    next: 'Siguiente',
    back: 'Volver a columnas',
  },
} as const;

export type SourceColumnsCopy = (typeof sourceColumnsCopy)['en' | 'es'];
