export const sourceRelationshipsCopyEn = {
  canvasConnections: 'Canvas connections',
  total: 'total',
  inputs: 'Inputs',
  outputs: 'Outputs',
  noInputs: 'No upstream Canvas connections',
  noOutputs: 'No downstream Canvas connections',
  noConnections: 'No Canvas connections are recorded for this Source.',
  selectedInput: 'selected input',
  selectedOutput: 'selected output',
  currentSource: 'Current Source',
  connectedNode: 'Connected node',
  direction: 'Direction',
  incoming: 'Incoming',
  outgoing: 'Outgoing',
  from: 'From',
  to: 'To',
  relation: 'Relation',
  listLabel: 'Canvas relationships',
  reorder: 'Reorder output',
  reorderHint: 'Drag or press Alt+Up/Down to reorder outputs.',
  reordered: 'Output reordered',
};
