import type { CanvasViewCopy } from './canvasCopy.types';

export const canvasViewAuthoringCopyEs = {
  connectionIncompleteMessage: 'La conexión está incompleta.',
  nodeNotFoundInGraphMessage: 'No se ha encontrado el nodo en el grafo.',
  nodeAlreadyOnCanvasMessage: 'El nodo ya está en el canvas',
  nodeKindUnavailableForCanvasMessage:
    'Este tipo de nodo no está disponible para el canvas activo.',
  nodeDropPayloadInvalidMessage:
    'No se ha podido leer el nodo arrastrado. El canvas no se ha modificado.',
  transformationConnectionOrderMessage:
    'Las aristas del Execution Preview deben seguir source -> sql_transform -> sink.',
  transformationConnectionEdgeCountMessage:
    'El Execution Preview requiere exactamente 2 aristas: source -> sql_transform y sql_transform -> sink.',
  transformationConnectionDuplicateMessage:
    'La dependencia ya existe en este borrador de transformación.',
  transformationRequiresThreeNodesMessage:
    'El Execution Preview requiere nodos source, sql_transform y sink.',
  transformationAmbiguousExecutablePathMessage:
    'El Execution Preview requiere seleccionar una única ruta source -> sql_transform -> sink.',
  transformationRequiresExecutablePathMessage:
    'El Execution Preview requiere una ruta conectada source -> sql_transform -> sink.',
  transformationUnsupportedRolesMessage:
    'El Execution Preview solo admite nodos input, transform y output en esta vertical.',
  transformationRequiresOneOfEachRoleMessage:
    'El Execution Preview requiere un source, un sql_transform y un sink.',
  transformationDraftValidMessage: 'El borrador de transformación es válido para la vista previa.',
  connectionSelfNotAllowedMessage: 'No se permiten las autoconexiones.',
  connectionAlreadyExistsMessage: 'La conexión ya existe.',
  connectionCycleDetectedMessage: 'La conexión crearía un ciclo en el DAG.',
  connectionPluginRuleBlockedFallbackMessage:
    'La conexión no está permitida por las reglas del plugin.',
  connectionCrossPluginBridgeMissingPrefix:
    'No existe un puente de puertos de datos compatible entre',
  limitedAccessMessagePrefix: 'El alcance actual desactiva ',
  limitedAccessSingularMessageSuffix: '.',
  limitedAccessPluralMessageSuffix: '.',
  capabilityPlanPreview: 'el preview del plan',
  capabilityRunStart: 'el arranque de runs',
  capabilityGraphEdits: 'editar el grafo',
  conjunctionAnd: 'y',
  serialConjunctionAnd: 'y',
  nodeAddedPrefix: 'Se ha añadido',
  nodeAddedSuffix: 'al canvas',
  nodeRemovedPrefix: 'Se ha eliminado',
  nodeRemovedSuffix: '',
  inspectorEditablePropertiesTitle: 'Propiedades editables',
  inspectorEditablePropertiesDescription:
    'Nombre, etiquetas y descripción guardados con este canvas.',
  nodePresentationColumnsLabel: 'Columnas',
  nodePresentationDeclaredColumnsDetailTemplate: '{count} columnas declaradas por este nodo.',
  nodePresentationInheritedColumnsDetailTemplate:
    '{count} columnas heredadas de las entradas conectadas; ninguna declarada por este nodo.',
  nodePresentationNoColumnsDetail:
    'No hay columnas declaradas ni heredadas disponibles para este nodo.',
  nodePresentationCodeLabel: 'Código',
  nodePresentationWorkspaceCodeDetailTemplate:
    'El código está en el archivo {path} del workspace. Abre Código para inspeccionarlo o editarlo.',
  nodePresentationGeneratedCodeDetailTemplate:
    'Artefacto DBT generado en {path}. Edita Código para convertirlo en código escrito.',
  nodePresentationCodeUnavailableMessage:
    'No hay código inline ni archivo del workspace registrado para este nodo.',
  nodePresentationActionsLabel: 'Más acciones del nodo',
  nodePresentationReadyStatusLabel: 'Listo',
  nodePresentationDraftStatusLabel: 'Borrador',
  nodePresentationAuthoringTagLabel: 'En edición',
  nodePresentationSourceKindLabel: 'Origen',
  nodePresentationModelKindLabel: 'Modelo',
  nodePresentationTestKindLabel: 'Prueba',
  canvasNodeAccessibleLabelTemplate: '{name}, {kind}',
  canvasEdgeAccessibleLabelTemplate: 'Conexión de {source} a {target}',
  reactFlowNodeDescription:
    'Pulsa Intro o Espacio para seleccionar un nodo. Usa las flechas para moverlo.',
  reactFlowNodeKeyboardDisabledDescription: 'Este nodo no se puede mover con el teclado.',
  reactFlowNodeMovedTemplate: 'Movido hacia {direction}. Posición: {x}, {y}.',
  reactFlowEdgeDescription: 'Pulsa Suprimir para eliminar esta conexión.',
  reactFlowControlsLabel: 'Controles del lienzo',
  reactFlowZoomInLabel: 'Acercar',
  reactFlowZoomOutLabel: 'Alejar',
  reactFlowFitViewLabel: 'Ajustar vista',
  reactFlowInteractiveLabel: 'Alternar interacción con el grafo',
  reactFlowMinimapLabel: 'Minimapa del lienzo',
  reactFlowHandleLabel: 'Puerto de conexión',
  nodeWorkbenchCloseLabel: 'Cerrar',
  nodeWorkbenchMoveLabel: 'Mover banco de trabajo del nodo',
  nodeWorkbenchMoreLabel: 'Más',
  nodeWorkbenchEditCodeFileLabel: 'Editar archivo SQL',
  nodeWorkbenchEditCodeFileDescription: 'Edita este archivo SQL en el editor contextual.',
  sqlContextWorkbenchNodeTitle: 'Código del nodo',
  sqlContextWorkbenchProjectTitle: 'Código del proyecto',
  sqlContextWorkbenchProjectDescription:
    'Archivos del workspace en el alcance del proyecto activo.',
  sqlContextWorkbenchMoveLabel: 'Mover banco de trabajo de código',
  sqlContextWorkbenchLoadingMessage: 'Cargando código...',
  inspectorNodeNameLabel: 'Nombre',
  inspectorNodeTagsLabel: 'Etiquetas',
  inspectorNodeTagsPlaceholder: 'finanzas, crítico',
  inspectorNodeDescriptionLabel: 'Descripción',
  inspectorNodeReadOnlyMessage:
    'Los detalles del nodo son de solo lectura para este estado del workspace.',
  inspectorCancelLabel: 'Cancelar',
  inspectorApplyLabel: 'Aplicar',
  inspectorDbtCardTitle: 'Ficha dbt',
  inspectorDbtPackageLabel: 'Paquete',
  inspectorDbtSourceLabel: 'Origen',
  inspectorDbtSchemaLabel: 'Esquema',
  inspectorDbtTableLabel: 'Tabla',
  inspectorDbtMaterializedLabel: 'Materialización',
  inspectorDbtOriginLabel: 'Entrada',
  inspectorDbtOriginPlaceholder: 'Selecciona un origen conectado',
  inspectorDbtModelSqlLabel: 'SQL del modelo',
  inspectorDbtModelSqlGeneratedDetailTemplate:
    'Artefacto DBT generado: {path}. Edítalo para asumir su autoría.',
  inspectorDbtModelSqlAuthoredDetailTemplate: 'SQL DBT escrita: {path}.',
  inspectorDbtNoConnectedOriginsMessage: 'No hay orígenes dbt conectados.',
  inspectorDbtModelSqlDescription: 'Define el SQL que ejecuta este nodo.',
  inspectorDbtOriginKindSourceLabel: 'source',
  inspectorDbtOriginKindModelLabel: 'modelo',
  inspectorDbtMaterializedViewLabel: 'vista',
  inspectorDbtMaterializedTableLabel: 'tabla',
  inspectorDbtMaterializedIncrementalLabel: 'incremental',
  inspectorDbtMaterializedEphemeralLabel: 'efímero',
  inspectorDbtTestTitle: 'Validación DBT',
  inspectorDbtTestTypeLabel: 'Regla de validación',
  inspectorDbtTestTargetLabel: 'Modelo conectado',
  inspectorDbtTestColumnLabel: 'Columna validada',
  inspectorDbtTestSeverityLabel: 'Severidad',
  inspectorDbtTestNotNullLabel: 'Valor obligatorio (no nulo)',
  inspectorDbtTestUniqueLabel: 'Valor único',
  inspectorDbtTestSeverityErrorLabel: 'Bloquear ejecución',
  inspectorDbtTestSeverityWarnLabel: 'Informar advertencia',
  inspectorDbtTestNoConnectedTargetMessage:
    'Conecta esta validación a un modelo DBT antes de configurarla.',
  inspectorDvtSourceTitle: 'Source DVT',
  inspectorDvtSqlTransformTitle: 'Transformación SQL DVT',
  inspectorDvtSinkTitle: 'Sink DVT',
  inspectorDvtDatabaseLabel: 'Base de datos',
  inspectorDvtSchemaLabel: 'Esquema',
  inspectorDvtTableLabel: 'Tabla',
  inspectorDvtAliasLabel: 'Alias',
  inspectorDvtSqlLabel: 'SQL',
  inspectorDvtMaterializationLabel: 'Materialización',
  inspectorDvtWriteModeLabel: 'Modo de escritura',
  inspectorDvtSourceTargetLabel: 'Destino del origen',
  inspectorDvtSqlBodyLabel: 'Cuerpo SQL',
  inspectorDvtSqlLineSingularLabel: 'línea',
  inspectorDvtSqlLinePluralLabel: 'líneas',
  inspectorDvtDestinationTargetLabel: 'Destino de salida',
  inspectorDvtPartitionStrategyLabel: 'Estrategia de partición',
  inspectorDvtMaterializationTableLabel: 'tabla',
  inspectorDvtMaterializationViewLabel: 'vista',
  inspectorDvtWriteModeReplaceLabel: 'reemplazar',
  inspectorDvtWriteModeAppendLabel: 'añadir',
  dvtFlowGuideTitle: 'Flujo DVT profesional',
  dvtFlowGuideReadyLabel: 'Listo para preview',
  dvtFlowGuideNeedsWorkLabel: 'Requiere trabajo',
  dvtFlowGuideRowsUnknownLabel: 'Filas desconocidas',
  dvtFlowGuideRowLabel: 'fila',
  dvtFlowGuideRowsLabel: 'filas',
  dvtFlowGuideColumnLabel: 'columna',
  dvtFlowGuideColumnsLabel: 'columnas',
  dvtFlowGuideNullableLabel: 'nullable',
  dvtFlowGuideRequiredLabel: 'requerida',
  dvtFlowGuideSourceMissingMessage: 'Falta el origen',
  dvtFlowGuideTransformMissingMessage: 'Falta la transformación',
  dvtFlowGuideSqlMissingMessage: 'Falta la SQL',
  dvtFlowGuideDestinationMissingMessage: 'Falta el destino',
  dvtFlowGuideColumnsMissingMessage: 'Metadatos de columnas no disponibles',
  dbtFlowGuideTitle: 'Flujo dbt profesional',
  dbtFlowGuideReadyLabel: 'Listo para preview',
  dbtFlowGuideNeedsWorkLabel: 'Requiere trabajo',
  dbtFlowGuideSummary:
    'Revisa los metadatos del source, el SQL del modelo y la validación dbt antes de planificar.',
  dbtFlowGuideSourceTitle: 'source dbt',
  dbtFlowGuideModelTitle: 'modelo dbt',
  dbtFlowGuideTestTitle: 'validación dbt',
  dbtFlowGuideRowsUnknownLabel: 'Filas desconocidas',
  dbtFlowGuideRowLabel: 'fila',
  dbtFlowGuideRowsLabel: 'filas',
  dbtFlowGuideColumnLabel: 'columna',
  dbtFlowGuideColumnsLabel: 'columnas',
  dbtFlowGuideNullableLabel: 'nullable',
  dbtFlowGuideRequiredLabel: 'requerida',
  dbtFlowGuideSourceMissingMessage: 'Falta el source',
  dbtFlowGuideModelMissingMessage: 'Falta el modelo',
  dbtFlowGuideSqlMissingMessage: 'Falta la SQL',
  dbtFlowGuideTestMissingMessage: 'Falta la validación',
  dbtFlowGuideTestSeverityUnknownLabel: 'severidad desconocida',
  dbtFlowGuideColumnsMissingMessage: 'Metadatos de columnas no disponibles',
  inspectorErrorNodeNameRequired: 'El nombre del nodo es obligatorio.',
  inspectorErrorDbtPackageRequired: 'El paquete es obligatorio.',
  inspectorErrorDbtSourceRequired: 'El origen es obligatorio.',
  inspectorErrorDbtSchemaRequired: 'El esquema es obligatorio.',
  inspectorErrorDbtTableRequired: 'La tabla es obligatoria.',
  inspectorErrorDbtMaterializationInvalid:
    'La materialización debe ser vista, tabla, incremental o efímera.',
  inspectorErrorDbtTestTypeInvalid: 'Elige una regla de validación DBT admitida.',
  inspectorErrorDbtTestTargetRequired: 'Conecta y selecciona el modelo DBT que valida este test.',
  inspectorErrorDbtTestColumnInvalid: 'Introduce un identificador de columna válido.',
  inspectorErrorDbtTestSeverityInvalid:
    'La severidad debe bloquear la ejecución o informar una advertencia.',
  inspectorErrorDvtSchemaRequired: 'El esquema es obligatorio.',
  inspectorErrorDvtTableRequired: 'La tabla es obligatoria.',
  inspectorErrorDvtAliasRequired: 'El alias es obligatorio.',
  inspectorErrorDvtMaterializationInvalid: 'La materialización debe ser tabla o vista.',
  inspectorErrorDvtWriteModeInvalid: 'El modo de escritura debe ser reemplazar o añadir.',
  inspectorObjectFileTitle: 'Carga de fichero de objetos',
  inspectorObjectFileDescription:
    'Carga un objeto CSV o JSON Lines inmutable en un staging PostgreSQL gobernado.',
  inspectorObjectFileStorageUriLabel: 'URI de almacenamiento direccionada por contenido',
  inspectorObjectFileSha256Label: 'Hash SHA-256',
  inspectorObjectFileSizeBytesLabel: 'Tamaño del objeto (bytes)',
  inspectorObjectFileMaxBytesLabel: 'Tamaño máximo admitido (bytes)',
  inspectorObjectFileFormatLabel: 'Formato',
  inspectorObjectFileCsvLabel: 'CSV con cabecera',
  inspectorObjectFileJsonLinesLabel: 'JSON Lines',
  inspectorObjectFileSourceCredentialLabel: 'Referencia de credencial del almacén de objetos',
  inspectorObjectFileTargetTitle: 'Destino PostgreSQL',
  inspectorObjectFileTargetSummary: 'esquema staging · modo replace',
  inspectorObjectFileTargetRelationLabel: 'Relación de staging',
  inspectorObjectFileTargetCredentialLabel: 'Referencia de credencial PostgreSQL',
  inspectorObjectFileColumnsTitle: 'Mapeo de columnas',
  inspectorObjectFileAddColumnLabel: 'Añadir mapeo de columna',
  inspectorObjectFileRemoveColumnLabel: 'Eliminar mapeo de columna',
  inspectorObjectFileSourceFieldLabel: 'Campo origen',
  inspectorObjectFileTargetColumnLabel: 'Columna destino',
  inspectorObjectFileDataTypeLabel: 'Tipo PostgreSQL',
  inspectorObjectFileNullableLabel: 'Permite nulos',
  inspectorErrorObjectFileStorageUriInvalid:
    'Usa s3://<bucket>/tenants/<tenant>/<sha256> para el objeto inmutable.',
  inspectorErrorObjectFileSha256Invalid:
    'El SHA-256 debe contener exactamente 64 caracteres hexadecimales.',
  inspectorErrorObjectFileSizeInvalid: 'El tamaño debe ser un número de bytes positivo y admitido.',
  inspectorErrorObjectFileMaxBytesInvalid:
    'El máximo debe ser positivo, acotado y no inferior al tamaño del objeto.',
  inspectorErrorObjectFileSourceCredentialInvalid:
    'Usa una referencia de credencial opaca object-store:<id>.',
  inspectorErrorObjectFileTargetRelationInvalid:
    'La relación debe ser un identificador PostgreSQL válido en minúsculas.',
  inspectorErrorObjectFileTargetCredentialInvalid:
    'Usa una referencia de credencial opaca postgres:<id>.',
  inspectorErrorObjectFileColumnMappingInvalid:
    'Añade al menos un mapeo origen-destino válido y sin duplicados.',
} satisfies Partial<CanvasViewCopy>;
