/** Owned concern: declare locale-neutral Inspector authoring validation error codes. */
export type CanvasInspectorNodeDraftErrorCode =
  | 'node_name_required'
  | 'dbt_package_required'
  | 'dbt_source_required'
  | 'dbt_schema_required'
  | 'dbt_table_required'
  | 'dbt_materialization_invalid'
  | 'dbt_test_type_invalid'
  | 'dbt_test_target_required'
  | 'dbt_test_column_invalid'
  | 'dbt_test_severity_invalid'
  | 'dvt_schema_required'
  | 'dvt_table_required'
  | 'dvt_alias_required'
  | 'dvt_connection_required'
  | 'dvt_materialization_invalid'
  | 'dvt_write_mode_invalid'
  | 'object_file_storage_uri_invalid'
  | 'object_file_sha256_invalid'
  | 'object_file_size_invalid'
  | 'object_file_max_bytes_invalid'
  | 'object_file_source_credential_ref_invalid'
  | 'object_file_target_relation_invalid'
  | 'object_file_target_credential_ref_invalid'
  | 'object_file_column_mapping_invalid';
