import type { CanvasViewCopy } from './canvasCopy.types';

export const canvasViewAuthoringCopyEs = {
  connectionIncompleteMessage: 'La conexion esta incompleta.',
  nodeNotFoundInGraphMessage: 'No se ha encontrado el nodo en el grafo.',
  nodeAlreadyOnCanvasMessage: 'El nodo ya esta en el canvas',
  nodeKindUnavailableForCanvasMessage:
    'Este tipo de nodo no esta disponible para el canvas activo.',
  nodeDropPayloadInvalidMessage:
    'No se ha podido leer el nodo arrastrado. El canvas no se ha modificado.',
  transformationConnectionOrderMessage:
    'Las aristas del Execution Preview deben seguir source -> sql_transform -> sink.',
  transformationConnectionEdgeCountMessage:
    'El Execution Preview requiere exactamente 2 aristas: source -> sql_transform y sql_transform -> sink.',
  transformationConnectionDuplicateMessage:
    'La dependencia ya existe en este draft de transformacion.',
  transformationRequiresThreeNodesMessage:
    'El Execution Preview requiere nodos source, sql_transform y sink.',
  transformationAmbiguousExecutablePathMessage:
    'El Execution Preview requiere seleccionar un unico path source -> sql_transform -> sink.',
  transformationRequiresExecutablePathMessage:
    'El Execution Preview requiere un path conectado source -> sql_transform -> sink.',
  transformationUnsupportedRolesMessage:
    'El Execution Preview solo admite nodos input, transform y output en esta vertical.',
  transformationRequiresOneOfEachRoleMessage:
    'El Execution Preview requiere un source, un sql_transform y un sink.',
  transformationDraftValidMessage: 'El draft de transformacion es valido para preview.',
  connectionSelfNotAllowedMessage: 'No se permiten las autoconexiones.',
  connectionAlreadyExistsMessage: 'La conexion ya existe.',
  connectionCycleDetectedMessage: 'La conexion crearia un ciclo en el DAG.',
  connectionPluginRuleBlockedFallbackMessage:
    'La conexion no esta permitida por las reglas del plugin.',
  connectionCrossPluginBridgeMissingPrefix:
    'No existe un puente de puertos de datos compatible entre',
  limitedAccessMessagePrefix: 'El alcance actual desactiva ',
  limitedAccessSingularMessageSuffix: '.',
  limitedAccessPluralMessageSuffix: '.',
  capabilityPlanPreview: 'el preview del plan',
  capabilityRunStart: 'el arranque de runs',
  capabilityGraphEdits: 'editar el grafo',
  conjunctionAnd: 'y',
  serialConjunctionAnd: 'y',
  nodeAddedPrefix: 'Se ha anadido',
  nodeAddedSuffix: 'al canvas',
  nodeRemovedPrefix: 'Se ha eliminado',
  nodeRemovedSuffix: '',
  inspectorEditablePropertiesTitle: 'Propiedades editables',
  inspectorEditablePropertiesDescription: 'Nombre, tags y descripcion guardados con este canvas.',
  nodePresentationColumnsLabel: 'Columnas',
  nodePresentationDeclaredColumnsDetailTemplate: '{count} columnas declaradas por este nodo.',
  nodePresentationInheritedColumnsDetailTemplate:
    '{count} columnas heredadas de las entradas conectadas; ninguna declarada por este nodo.',
  nodePresentationNoColumnsDetail:
    'No hay columnas declaradas ni heredadas disponibles para este nodo.',
  nodePresentationCodeLabel: 'Código',
  nodePresentationWorkspaceCodeDetailTemplate:
    'El código está en el archivo {path} del workspace. Abre Código para inspeccionarlo o editarlo.',
  nodePresentationGeneratedCodeDetailTemplate:
    'Artefacto DBT generado en {path}. Edita Código para convertirlo en código escrito.',
  nodePresentationCodeUnavailableMessage:
    'No hay código inline ni archivo del workspace registrado para este nodo.',
  nodeWorkbenchCloseLabel: 'Cerrar',
  nodeWorkbenchMoveLabel: 'Mover banco de trabajo del nodo',
  nodeWorkbenchMoreLabel: 'Más',
  sqlContextWorkbenchNodeTitle: 'Código del nodo',
  sqlContextWorkbenchProjectTitle: 'Código del proyecto',
  sqlContextWorkbenchProjectDescription:
    'Archivos del workspace en el alcance del proyecto activo.',
  sqlContextWorkbenchMoveLabel: 'Mover banco de trabajo de código',
  sqlContextWorkbenchLoadingMessage: 'Cargando código...',
  inspectorNodeNameLabel: 'Nombre',
  inspectorNodeTagsLabel: 'Tags',
  inspectorNodeTagsPlaceholder: 'finanzas, critico',
  inspectorNodeDescriptionLabel: 'Descripcion',
  inspectorNodeReadOnlyMessage:
    'Los detalles del nodo son de solo lectura para este estado del workspace.',
  inspectorCancelLabel: 'Cancelar',
  inspectorApplyLabel: 'Aplicar',
  inspectorDbtCardTitle: 'Ficha dbt',
  inspectorDbtPackageLabel: 'Paquete',
  inspectorDbtSourceLabel: 'Origen',
  inspectorDbtSchemaLabel: 'Esquema',
  inspectorDbtTableLabel: 'Tabla',
  inspectorDbtMaterializedLabel: 'Materializacion',
  inspectorDbtOriginLabel: 'Entrada',
  inspectorDbtOriginPlaceholder: 'Selecciona un origen conectado',
  inspectorDbtModelSqlLabel: 'SQL del modelo',
  inspectorDbtModelSqlGeneratedDetailTemplate:
    'Artefacto DBT generado: {path}. Editalo para asumir su autoria.',
  inspectorDbtModelSqlAuthoredDetailTemplate: 'SQL DBT escrita: {path}.',
  inspectorDbtNoConnectedOriginsMessage: 'No hay origenes dbt conectados.',
  inspectorDbtModelSqlUnavailableMessage:
    'Conecta este modelo a un source o modelo DBT antes de generar un artefacto ejecutable.',
  inspectorDbtOriginKindSourceLabel: 'source',
  inspectorDbtOriginKindModelLabel: 'modelo',
  inspectorDbtMaterializedViewLabel: 'vista',
  inspectorDbtMaterializedTableLabel: 'tabla',
  inspectorDbtMaterializedIncrementalLabel: 'incremental',
  inspectorDbtMaterializedEphemeralLabel: 'efimero',
  inspectorDbtTestTitle: 'Validacion DBT',
  inspectorDbtTestTypeLabel: 'Regla de validacion',
  inspectorDbtTestTargetLabel: 'Modelo conectado',
  inspectorDbtTestColumnLabel: 'Columna validada',
  inspectorDbtTestSeverityLabel: 'Severidad',
  inspectorDbtTestNotNullLabel: 'Valor obligatorio (no nulo)',
  inspectorDbtTestUniqueLabel: 'Valor unico',
  inspectorDbtTestSeverityErrorLabel: 'Bloquear ejecucion',
  inspectorDbtTestSeverityWarnLabel: 'Informar advertencia',
  inspectorDbtTestNoConnectedTargetMessage:
    'Conecta esta validacion a un modelo DBT antes de configurarla.',
  inspectorDvtSourceTitle: 'Source DVT',
  inspectorDvtSqlTransformTitle: 'Transformacion SQL DVT',
  inspectorDvtSinkTitle: 'Sink DVT',
  inspectorDvtDatabaseLabel: 'Base de datos',
  inspectorDvtSchemaLabel: 'Esquema',
  inspectorDvtTableLabel: 'Tabla',
  inspectorDvtAliasLabel: 'Alias',
  inspectorDvtSqlLabel: 'SQL',
  inspectorDvtMaterializationLabel: 'Materializacion',
  inspectorDvtWriteModeLabel: 'Modo de escritura',
  inspectorDvtSourceTargetLabel: 'Destino del origen',
  inspectorDvtSqlBodyLabel: 'Cuerpo SQL',
  inspectorDvtSqlLineSingularLabel: 'linea',
  inspectorDvtSqlLinePluralLabel: 'lineas',
  inspectorDvtDestinationTargetLabel: 'Destino de salida',
  inspectorDvtPartitionStrategyLabel: 'Estrategia de particion',
  inspectorDvtMaterializationTableLabel: 'tabla',
  inspectorDvtMaterializationViewLabel: 'vista',
  inspectorDvtWriteModeReplaceLabel: 'reemplazar',
  inspectorDvtWriteModeAppendLabel: 'anadir',
  dvtFlowGuideTitle: 'Flujo DVT profesional',
  dvtFlowGuideReadyLabel: 'Listo para preview',
  dvtFlowGuideNeedsWorkLabel: 'Requiere trabajo',
  dvtFlowGuideRowsUnknownLabel: 'Filas desconocidas',
  dvtFlowGuideRowLabel: 'fila',
  dvtFlowGuideRowsLabel: 'filas',
  dvtFlowGuideColumnLabel: 'columna',
  dvtFlowGuideColumnsLabel: 'columnas',
  dvtFlowGuideNullableLabel: 'nullable',
  dvtFlowGuideRequiredLabel: 'requerida',
  dvtFlowGuideSourceMissingMessage: 'Falta el origen',
  dvtFlowGuideTransformMissingMessage: 'Falta la transformacion',
  dvtFlowGuideSqlMissingMessage: 'Falta la SQL',
  dvtFlowGuideDestinationMissingMessage: 'Falta el destino',
  dvtFlowGuideColumnsMissingMessage: 'Metadata de columnas no disponible',
  dbtFlowGuideTitle: 'Flujo dbt profesional',
  dbtFlowGuideReadyLabel: 'Listo para preview',
  dbtFlowGuideNeedsWorkLabel: 'Requiere trabajo',
  dbtFlowGuideSummary:
    'Revisa metadata del source, SQL del modelo y validacion dbt antes de planificar.',
  dbtFlowGuideSourceTitle: 'source dbt',
  dbtFlowGuideModelTitle: 'modelo dbt',
  dbtFlowGuideTestTitle: 'validacion dbt',
  dbtFlowGuideRowsUnknownLabel: 'Filas desconocidas',
  dbtFlowGuideRowLabel: 'fila',
  dbtFlowGuideRowsLabel: 'filas',
  dbtFlowGuideColumnLabel: 'columna',
  dbtFlowGuideColumnsLabel: 'columnas',
  dbtFlowGuideNullableLabel: 'nullable',
  dbtFlowGuideRequiredLabel: 'requerida',
  dbtFlowGuideSourceMissingMessage: 'Falta el source',
  dbtFlowGuideModelMissingMessage: 'Falta el modelo',
  dbtFlowGuideSqlMissingMessage: 'Falta la SQL',
  dbtFlowGuideTestMissingMessage: 'Falta la validacion',
  dbtFlowGuideTestSeverityUnknownLabel: 'severidad desconocida',
  dbtFlowGuideColumnsMissingMessage: 'Metadata de columnas no disponible',
  inspectorErrorNodeNameRequired: 'El nombre del nodo es obligatorio.',
  inspectorErrorDbtPackageRequired: 'El paquete es obligatorio.',
  inspectorErrorDbtSourceRequired: 'El origen es obligatorio.',
  inspectorErrorDbtSchemaRequired: 'El esquema es obligatorio.',
  inspectorErrorDbtTableRequired: 'La tabla es obligatoria.',
  inspectorErrorDbtMaterializationInvalid:
    'La materializacion debe ser vista, tabla, incremental o efimera.',
  inspectorErrorDbtTestTypeInvalid: 'Elige una regla de validacion DBT admitida.',
  inspectorErrorDbtTestTargetRequired: 'Conecta y selecciona el modelo DBT que valida este test.',
  inspectorErrorDbtTestColumnInvalid: 'Introduce un identificador de columna valido.',
  inspectorErrorDbtTestSeverityInvalid:
    'La severidad debe bloquear la ejecucion o informar una advertencia.',
  inspectorErrorDvtSchemaRequired: 'El esquema es obligatorio.',
  inspectorErrorDvtTableRequired: 'La tabla es obligatoria.',
  inspectorErrorDvtAliasRequired: 'El alias es obligatorio.',
  inspectorErrorDvtMaterializationInvalid: 'La materializacion debe ser tabla o vista.',
  inspectorErrorDvtWriteModeInvalid: 'El modo de escritura debe ser reemplazar o anadir.',
  inspectorObjectFileTitle: 'Carga de fichero de objetos',
  inspectorObjectFileDescription:
    'Carga un objeto CSV o JSON Lines inmutable en un staging PostgreSQL gobernado.',
  inspectorObjectFileStorageUriLabel: 'URI de almacenamiento direccionada por contenido',
  inspectorObjectFileSha256Label: 'Hash SHA-256',
  inspectorObjectFileSizeBytesLabel: 'Tamano del objeto (bytes)',
  inspectorObjectFileMaxBytesLabel: 'Tamano maximo admitido (bytes)',
  inspectorObjectFileFormatLabel: 'Formato',
  inspectorObjectFileCsvLabel: 'CSV con cabecera',
  inspectorObjectFileJsonLinesLabel: 'JSON Lines',
  inspectorObjectFileSourceCredentialLabel: 'Referencia de credencial del almacen de objetos',
  inspectorObjectFileTargetTitle: 'Destino PostgreSQL',
  inspectorObjectFileTargetSummary: 'esquema staging · modo replace',
  inspectorObjectFileTargetRelationLabel: 'Relacion de staging',
  inspectorObjectFileTargetCredentialLabel: 'Referencia de credencial PostgreSQL',
  inspectorObjectFileColumnsTitle: 'Mapeo de columnas',
  inspectorObjectFileAddColumnLabel: 'Anadir mapeo de columna',
  inspectorObjectFileRemoveColumnLabel: 'Eliminar mapeo de columna',
  inspectorObjectFileSourceFieldLabel: 'Campo origen',
  inspectorObjectFileTargetColumnLabel: 'Columna destino',
  inspectorObjectFileDataTypeLabel: 'Tipo PostgreSQL',
  inspectorObjectFileNullableLabel: 'Permite nulos',
  inspectorErrorObjectFileStorageUriInvalid:
    'Usa s3://<bucket>/tenants/<tenant>/<sha256> para el objeto inmutable.',
  inspectorErrorObjectFileSha256Invalid:
    'El SHA-256 debe contener exactamente 64 caracteres hexadecimales.',
  inspectorErrorObjectFileSizeInvalid: 'El tamano debe ser un numero de bytes positivo y admitido.',
  inspectorErrorObjectFileMaxBytesInvalid:
    'El maximo debe ser positivo, acotado y no inferior al tamano del objeto.',
  inspectorErrorObjectFileSourceCredentialInvalid:
    'Usa una referencia de credencial opaca object-store:<id>.',
  inspectorErrorObjectFileTargetRelationInvalid:
    'La relacion debe ser un identificador PostgreSQL valido en minusculas.',
  inspectorErrorObjectFileTargetCredentialInvalid:
    'Usa una referencia de credencial opaca postgres:<id>.',
  inspectorErrorObjectFileColumnMappingInvalid:
    'Anade al menos un mapeo origen-destino valido y sin duplicados.',
} satisfies Partial<CanvasViewCopy>;
