import type { CanvasViewCopy } from './canvasCopy.types';

export const canvasViewAuthoringCopyEs = {
  columnMappingAddedMessage: 'Asignación de columna añadida.',
  columnMappingRemovedMessage: 'Asignación de columna eliminada.',
  columnMappingSourceSelectedTemplate:
    'Se ha seleccionado {column}. Elige una columna de destino en el Modelo.',
  columnMappingAutomapSummaryTemplate: 'Se han asignado {count} columnas compatibles.',
  columnMappingRequiresDependencyMessage:
    'Conecta el Origen con este Modelo antes de asignar columnas.',
  columnMappingSqlAuthorityMessage:
    'Este Modelo contiene SQL escrita. Conviértelo a edición visual antes de asignar columnas.',
  columnMappingComplexExpressionMessage:
    'Edita esta columna calculada en Propiedades del Modelo en lugar de sustituir aquí sus entradas.',
  columnMappingUnavailableMessage:
    'Esta asignación de columna no está disponible para los nodos seleccionados.',
  columnMappingNoCompatibleColumnsMessage:
    'No se encontraron columnas únicas con el mismo nombre y tipos conocidos compatibles.',
  connectionIncompleteMessage: 'La conexión está incompleta.',
  nodeNotFoundInGraphMessage: 'No se ha encontrado el nodo en el grafo.',
  nodeAlreadyOnCanvasMessage: 'El nodo ya está en el canvas',
  nodeKindUnavailableForCanvasMessage:
    'Este tipo de nodo no está disponible para el canvas activo.',
  nodeDropPayloadInvalidMessage:
    'No se ha podido leer el nodo arrastrado. El canvas no se ha modificado.',
  transformationConnectionOrderMessage:
    'Las aristas del Execution Preview deben seguir source -> sql_transform -> sink.',
  transformationConnectionEdgeCountMessage:
    'El Execution Preview requiere exactamente 2 aristas: source -> sql_transform y sql_transform -> sink.',
  transformationConnectionDuplicateMessage:
    'La dependencia ya existe en este borrador de transformación.',
  transformationRequiresThreeNodesMessage:
    'El Execution Preview requiere nodos source, sql_transform y sink.',
  transformationAmbiguousExecutablePathMessage:
    'El Execution Preview requiere seleccionar una única ruta source -> sql_transform -> sink.',
  transformationRequiresExecutablePathMessage:
    'El Execution Preview requiere una ruta conectada source -> sql_transform -> sink.',
  transformationRequiresPostgresConnectionMessage:
    'Selecciona una conexión PostgreSQL gobernada en el origen antes de generar la vista previa.',
  transformationUnsupportedRolesMessage:
    'El Execution Preview solo admite nodos input, transform y output en esta vertical.',
  transformationRequiresOneOfEachRoleMessage:
    'El Execution Preview requiere un source, un sql_transform y un sink.',
  transformationDraftValidMessage: 'El borrador de transformación es válido para la vista previa.',
  connectionSelfNotAllowedMessage: 'No se permiten las autoconexiones.',
  connectionAlreadyExistsMessage: 'La conexión ya existe.',
  connectionCycleDetectedMessage: 'La conexión crearía un ciclo en el DAG.',
  connectionPluginPolicyUnavailableTemplate:
    'La política de conexiones no está disponible para el plugin {plugin}.',
  connectionPluginRuleBlockedFallbackMessage:
    'La conexión no está permitida por las reglas del plugin.',
  connectionCrossPluginBridgeMissingPrefix:
    'No existe un puente de puertos de datos compatible entre',
  limitedAccessMessagePrefix: 'El alcance actual desactiva ',
  limitedAccessSingularMessageSuffix: '.',
  limitedAccessPluralMessageSuffix: '.',
  capabilityPlanPreview: 'el preview del plan',
  capabilityRunStart: 'el arranque de runs',
  capabilityGraphEdits: 'editar el grafo',
  conjunctionAnd: 'y',
  serialConjunctionAnd: 'y',
  nodeAddedPrefix: 'Se ha añadido',
  nodeAddedSuffix: 'al canvas',
  nodeRemovedPrefix: 'Se ha eliminado',
  nodeRemovedSuffix: '',
  inspectorEditablePropertiesTitle: 'Propiedades editables',
  inspectorEditablePropertiesDescription:
    'Nombre, etiquetas y descripción guardados con este canvas.',
  nodePresentationColumnsLabel: 'Columnas',
  nodePresentationDeclaredColumnsDetailTemplate: '{count} columnas declaradas por este nodo.',
  nodePresentationInheritedColumnsDetailTemplate:
    '{count} columnas heredadas de las entradas conectadas; ninguna declarada por este nodo.',
  nodePresentationMixedColumnsDetailTemplate:
    'Columnas asignadas: {declared}. Columnas de entrada disponibles: {available}.',
  nodePresentationNoColumnsDetail:
    'No hay columnas declaradas ni heredadas disponibles para este nodo.',
  nodePresentationCodeLabel: 'Código',
  nodePresentationWorkspaceCodeDetailTemplate:
    'El código está en el archivo {path} del workspace. Abre Código para inspeccionarlo o editarlo.',
  nodePresentationGeneratedCodeDetailTemplate:
    'Artefacto DBT generado en {path}. Edita Código para convertirlo en código escrito.',
  nodePresentationCodeUnavailableMessage:
    'No hay código inline ni archivo del workspace registrado para este nodo.',
  nodePresentationActionsLabel: 'Más acciones del nodo',
  nodePresentationReadyStatusLabel: 'Listo',
  nodePresentationDraftStatusLabel: 'Borrador',
  nodePresentationAuthoringTagLabel: 'En edición',
  nodePresentationSourceKindLabel: 'Origen',
  nodePresentationModelKindLabel: 'Modelo',
  nodePresentationTestKindLabel: 'Prueba',
  canvasNodeAccessibleLabelTemplate: '{name}, {kind}',
  canvasEdgeAccessibleLabelTemplate: 'Conexión de {source} a {target}',
  reactFlowNodeDescription:
    'Pulsa Intro o Espacio para seleccionar un nodo. Usa las flechas para moverlo.',
  reactFlowNodeKeyboardDisabledDescription: 'Este nodo no se puede mover con el teclado.',
  reactFlowNodeMovedTemplate: 'Movido hacia {direction}. Posición: {x}, {y}.',
  reactFlowEdgeDescription: 'Pulsa Suprimir para eliminar esta conexión.',
  reactFlowControlsLabel: 'Controles del lienzo',
  reactFlowZoomInLabel: 'Acercar',
  reactFlowZoomOutLabel: 'Alejar',
  reactFlowFitViewLabel: 'Ajustar vista',
  reactFlowInteractiveLabel: 'Alternar interacción con el grafo',
  reactFlowMinimapLabel: 'Minimapa del lienzo',
  reactFlowHandleLabel: 'Puerto de conexión',
  nodeWorkbenchCloseLabel: 'Cerrar',
  nodeWorkbenchMoveLabel: 'Mover banco de trabajo del nodo',
  nodeWorkbenchMoreLabel: 'Más',
  sqlContextWorkbenchProjectTitle: 'Código del proyecto',
  sqlContextWorkbenchProjectDescription:
    'Archivos del workspace en el alcance del proyecto activo.',
  sqlContextWorkbenchMoveLabel: 'Mover banco de trabajo de código',
  sqlContextWorkbenchLoadingMessage: 'Cargando código...',
  inspectorNodeNameLabel: 'Nombre',
  inspectorNodeTagsLabel: 'Etiquetas',
  inspectorNodeTagsPlaceholder: 'finanzas, crítico',
  inspectorNodeDescriptionLabel: 'Descripción',
  inspectorNodeReadOnlyMessage:
    'Los detalles del nodo son de solo lectura para este estado del workspace.',
  inspectorCancelLabel: 'Cancelar',
  inspectorApplyLabel: 'Aplicar',
  inspectorVisualTransformConvertToSqlLabel: 'Convertir a SQL',
  inspectorVisualTransformConvertToSqlTitle: '¿Convertir esta transformación visual a SQL?',
  inspectorVisualTransformConvertToSqlDescription:
    'Esto sustituye la receta visual como autoridad de edición. Volver de SQL a Visual no es automático.',
  inspectorDbtCardTitle: 'Ficha dbt',
  inspectorDbtPackageLabel: 'Paquete',
  inspectorDbtSourceLabel: 'Origen',
  inspectorDbtSchemaLabel: 'Esquema',
  inspectorDbtTableLabel: 'Tabla',
  inspectorDbtMaterializedLabel: 'Materialización',
  inspectorDbtOriginLabel: 'Entrada',
  inspectorDbtOriginPlaceholder: 'Selecciona un origen conectado',
  inspectorDbtModelSqlLabel: 'SQL del modelo',
  inspectorDbtModelSqlGeneratedDetailTemplate:
    'Artefacto DBT generado: {path}. Edítalo para asumir su autoría.',
  inspectorDbtModelSqlAuthoredDetailTemplate: 'SQL DBT escrita: {path}.',
  inspectorDbtNoConnectedOriginsMessage: 'No hay orígenes dbt conectados.',
  inspectorDbtOriginKindSourceLabel: 'source',
  inspectorDbtOriginKindModelLabel: 'modelo',
  inspectorDbtMaterializedViewLabel: 'vista',
  inspectorDbtMaterializedTableLabel: 'tabla',
  inspectorDbtMaterializedIncrementalLabel: 'incremental',
  inspectorDbtMaterializedEphemeralLabel: 'efímero',
  inspectorDbtTestTitle: 'Validación DBT',
  inspectorDbtTestTypeLabel: 'Regla de validación',
  inspectorDbtTestTargetLabel: 'Modelo conectado',
  inspectorDbtTestColumnLabel: 'Columna validada',
  inspectorDbtTestSeverityLabel: 'Severidad',
  inspectorDbtTestNotNullLabel: 'Valor obligatorio (no nulo)',
  inspectorDbtTestUniqueLabel: 'Valor único',
  inspectorDbtTestSeverityErrorLabel: 'Bloquear ejecución',
  inspectorDbtTestSeverityWarnLabel: 'Informar advertencia',
  inspectorDbtTestNoConnectedTargetMessage:
    'Conecta esta validación a un modelo DBT antes de configurarla.',
  inspectorDvtSourceTitle: 'Origen DVT',
  inspectorDvtConnectionLabel: 'Conexión',
  inspectorDvtConnectionPlaceholder: 'Selecciona una conexión gobernada',
  inspectorDvtConnectionLoadingLabel: 'Cargando conexiones…',
  inspectorDvtConnectionLoadFailedMessage: 'No se pudieron cargar las conexiones.',
  inspectorDvtConnectionTestLabel: 'Probar conexión',
  inspectorDvtConnectionTestPassedMessage: 'Conexión disponible.',
  inspectorDvtConnectionTestFailedMessage: 'Conexión no disponible.',
  inspectorDvtInheritedConnectionLabel: 'Conexión heredada',
  inspectorDvtSqlTransformTitle: 'Transformación SQL DVT',
  inspectorDvtSinkTitle: 'Salida DVT',
  inspectorDvtDatabaseLabel: 'Base de datos',
  inspectorDvtSchemaLabel: 'Esquema',
  inspectorDvtTableLabel: 'Tabla',
  inspectorDvtAliasLabel: 'Alias',
  inspectorDvtSqlLabel: 'SQL',
  inspectorDvtMaterializationLabel: 'Materialización',
  inspectorDvtWriteModeLabel: 'Modo de escritura',
  inspectorDvtSourceTargetLabel: 'Destino del origen',
  inspectorDvtSqlBodyLabel: 'Cuerpo SQL',
  inspectorDvtSqlLineSingularLabel: 'línea',
  inspectorDvtSqlLinePluralLabel: 'líneas',
  inspectorDvtSqlValidationCheckingLabel: 'Comprobando SQL…',
  inspectorDvtSqlValidationValidLabel: 'SQL listo para Vista previa.',
  inspectorDvtSqlValidationUnavailableLabel:
    'No se pudo comprobar el SQL con la conexión gobernada.',
  inspectorDvtSqlRequiredMessage: 'Introduce una consulta SQL.',
  inspectorDvtSqlSyntaxErrorMessage: 'Corrige la sintaxis PostgreSQL.',
  inspectorDvtSqlMultipleStatementsMessage: 'Usa una sola sentencia SQL.',
  inspectorDvtSqlUnsupportedStatementMessage: 'Usa una sentencia SELECT.',
  inspectorDvtSqlUndefinedTableMessage: 'PostgreSQL no encuentra esta tabla.',
  inspectorDvtSqlUndefinedColumnMessage: 'PostgreSQL no encuentra esta columna.',
  inspectorDvtSqlPostgresErrorMessage: 'PostgreSQL ha rechazado esta consulta.',
  inspectorDvtVisualRecipeTitle: 'Receta visual',
  inspectorDvtVisualOutputLabel: 'Salida',
  inspectorDvtVisualOutputNameLabel: 'Nombre de salida',
  inspectorDvtVisualInputsLabel: 'Columnas de entrada',
  inspectorDvtVisualOperationsLabel: 'Operaciones',
  inspectorDvtVisualOperationLabel: 'Operación',
  inspectorDvtVisualAddOutputLabel: 'Añadir salida',
  inspectorDvtVisualExcludeOutputLabel: 'Excluir salida',
  inspectorDvtVisualAddOperationLabel: 'Añadir operación',
  inspectorDvtVisualRemoveOperationLabel: 'Eliminar operación',
  inspectorDvtVisualMoveOperationUpLabel: 'Subir operación',
  inspectorDvtVisualMoveOperationDownLabel: 'Bajar operación',
  inspectorDvtVisualPassthroughLabel: 'Directa',
  inspectorDvtVisualConstantLabel: 'Constante',
  inspectorDvtVisualCastTypeLabel: 'Tipo de conversión',
  inspectorDvtVisualArgumentLabel: 'Argumento',
  inspectorDvtVisualFiltersLabel: 'Filtros',
  inspectorDvtVisualAddFilterLabel: 'Añadir filtro',
  inspectorDvtVisualRemoveFilterLabel: 'Eliminar filtro',
  inspectorDvtVisualFilterColumnLabel: 'Columna del filtro',
  inspectorDvtVisualFilterOperatorLabel: 'Operador del filtro',
  inspectorDvtVisualFilterValueLabel: 'Valor del filtro',
  inspectorDvtDestinationTargetLabel: 'Destino de salida',
  inspectorDvtPartitionStrategyLabel: 'Estrategia de partición',
  inspectorDvtMaterializationTableLabel: 'tabla',
  inspectorDvtMaterializationViewLabel: 'vista',
  inspectorDvtWriteModeReplaceLabel: 'reemplazar',
  inspectorDvtWriteModeAppendLabel: 'añadir',
  dvtFlowGuideTitle: 'Flujo DVT profesional',
  dvtFlowGuideReadyLabel: 'Listo para preview',
  dvtFlowGuideNeedsWorkLabel: 'Requiere trabajo',
  dvtFlowGuideRowsUnknownLabel: 'Filas desconocidas',
  dvtFlowGuideRowLabel: 'fila',
  dvtFlowGuideRowsLabel: 'filas',
  dvtFlowGuideColumnLabel: 'columna',
  dvtFlowGuideColumnsLabel: 'columnas',
  dvtFlowGuideNullableLabel: 'nullable',
  dvtFlowGuideRequiredLabel: 'requerida',
  dvtFlowGuideSourceMissingMessage: 'Falta el origen',
  dvtFlowGuideTransformMissingMessage: 'Falta la transformación',
  dvtFlowGuideSqlMissingMessage: 'Falta la SQL',
  dvtFlowGuideDestinationMissingMessage: 'Falta el destino',
  dvtFlowGuideColumnsMissingMessage: 'Metadatos de columnas no disponibles',
  dbtFlowGuideTitle: 'Flujo dbt profesional',
  dbtFlowGuideReadyLabel: 'Listo para preview',
  dbtFlowGuideNeedsWorkLabel: 'Requiere trabajo',
  dbtFlowGuideSummary:
    'Revisa los metadatos del source, el SQL del modelo y la validación dbt antes de planificar.',
  dbtFlowGuideSourceTitle: 'source dbt',
  dbtFlowGuideModelTitle: 'modelo dbt',
  dbtFlowGuideTestTitle: 'validación dbt',
  dbtFlowGuideRowsUnknownLabel: 'Filas desconocidas',
  dbtFlowGuideRowLabel: 'fila',
  dbtFlowGuideRowsLabel: 'filas',
  dbtFlowGuideColumnLabel: 'columna',
  dbtFlowGuideColumnsLabel: 'columnas',
  dbtFlowGuideNullableLabel: 'nullable',
  dbtFlowGuideRequiredLabel: 'requerida',
  dbtFlowGuideSourceMissingMessage: 'Falta el source',
  dbtFlowGuideModelMissingMessage: 'Falta el modelo',
  dbtFlowGuideSqlMissingMessage: 'Falta la SQL',
  dbtFlowGuideTestMissingMessage: 'Falta la validación',
  dbtFlowGuideTestSeverityUnknownLabel: 'severidad desconocida',
  dbtFlowGuideColumnsMissingMessage: 'Metadatos de columnas no disponibles',
  inspectorErrorNodeNameRequired: 'El nombre del nodo es obligatorio.',
  inspectorErrorDbtPackageRequired: 'El paquete es obligatorio.',
  inspectorErrorDbtSourceRequired: 'El origen es obligatorio.',
  inspectorErrorDbtSchemaRequired: 'El esquema es obligatorio.',
  inspectorErrorDbtTableRequired: 'La tabla es obligatoria.',
  inspectorErrorDbtMaterializationInvalid:
    'La materialización debe ser vista, tabla, incremental o efímera.',
  inspectorErrorDbtTestTypeInvalid: 'Elige una regla de validación DBT admitida.',
  inspectorErrorDbtTestTargetRequired: 'Conecta y selecciona el modelo DBT que valida este test.',
  inspectorErrorDbtTestColumnInvalid: 'Introduce un identificador de columna válido.',
  inspectorErrorDbtTestSeverityInvalid:
    'La severidad debe bloquear la ejecución o informar una advertencia.',
  inspectorErrorDvtSchemaRequired: 'El esquema es obligatorio.',
  inspectorErrorDvtTableRequired: 'La tabla es obligatoria.',
  inspectorErrorDvtAliasRequired: 'El alias es obligatorio.',
  inspectorErrorDvtConnectionRequired: 'Selecciona una conexión PostgreSQL.',
  inspectorErrorDvtVisualRecipeInvalid:
    'Completa todas las salidas visuales antes de aplicar la receta.',
  inspectorErrorDvtMaterializationInvalid: 'La materialización debe ser tabla o vista.',
  inspectorErrorDvtWriteModeInvalid: 'El modo de escritura debe ser reemplazar o añadir.',
  inspectorHttpJsonTitle: 'Adquisición HTTP JSON',
  inspectorHttpJsonDescription:
    'Obtén JSON o JSON Lines inmutable mediante referencias opacas de endpoint y credenciales.',
  inspectorHttpJsonEndpointRefLabel: 'Referencia de endpoint',
  inspectorHttpJsonAuthCredentialRefLabel: 'Referencia de autenticación (opcional)',
  inspectorHttpJsonFormatLabel: 'Formato',
  inspectorHttpJsonExpectedSha256Label: 'SHA-256 esperado',
  inspectorHttpJsonExpectedSizeBytesLabel: 'Tamaño esperado (bytes)',
  inspectorHttpJsonMaxBytesLabel: 'Tamaño máximo admitido (bytes)',
  inspectorHttpJsonStorageUriLabel: 'URI S3 direccionada por contenido',
  inspectorHttpJsonArtifactCredentialRefLabel: 'Referencia de credencial del almacén de objetos',
  inspectorHttpJsonConnectTimeoutLabel: 'Tiempo de conexión (ms)',
  inspectorHttpJsonRequestTimeoutLabel: 'Tiempo total de solicitud (ms)',
  inspectorHttpJsonMaxRedirectsLabel: 'Máximo de redirecciones',
  inspectorErrorHttpJsonEndpointRefInvalid: 'Usa una referencia opaca http-endpoint:<id>.',
  inspectorErrorHttpJsonAuthCredentialRefInvalid:
    'Usa una referencia opaca http-auth:<id> o deja el campo vacío.',
  inspectorErrorHttpJsonSha256Invalid:
    'El SHA-256 debe contener exactamente 64 caracteres hexadecimales.',
  inspectorErrorHttpJsonSizeInvalid:
    'El tamaño esperado debe ser un número entero positivo, no superar 50000000 bytes y no superar el tamaño máximo.',
  inspectorErrorHttpJsonMaxBytesInvalid:
    'El tamaño máximo debe ser un número entero positivo, no superar 50000000 bytes y no ser inferior al tamaño esperado.',
  inspectorErrorHttpJsonStorageUriInvalid:
    'Usa s3://<bucket>/tenants/<tenant>/<sha256> para el artefacto inmutable.',
  inspectorErrorHttpJsonArtifactCredentialRefInvalid:
    'Usa una referencia de credencial opaca object-store:<id>.',
  inspectorErrorHttpJsonConnectTimeoutInvalid:
    'El tiempo de conexión debe ser un número entero entre 100 y 30000 ms y no superar el tiempo total.',
  inspectorErrorHttpJsonRequestTimeoutInvalid:
    'El tiempo total debe ser un número entero entre 100 y 60000 ms.',
  inspectorErrorHttpJsonRedirectLimitInvalid:
    'El máximo de redirecciones debe ser un entero entre 0 y 5.',
  inspectorObjectFileTitle: 'Carga de fichero de objetos',
  inspectorObjectFileDescription:
    'Carga un objeto CSV o JSON Lines inmutable en un staging PostgreSQL gobernado.',
  inspectorObjectFileStorageUriLabel: 'URI de almacenamiento direccionada por contenido',
  inspectorObjectFileSha256Label: 'Hash SHA-256',
  inspectorObjectFileSizeBytesLabel: 'Tamaño del objeto (bytes)',
  inspectorObjectFileMaxBytesLabel: 'Tamaño máximo admitido (bytes)',
  inspectorObjectFileFormatLabel: 'Formato',
  inspectorObjectFileCsvLabel: 'CSV con cabecera',
  inspectorObjectFileJsonLinesLabel: 'JSON Lines',
  inspectorObjectFileSourceCredentialLabel: 'Referencia de credencial del almacén de objetos',
  inspectorObjectFileTargetTitle: 'Destino PostgreSQL',
  inspectorObjectFileTargetSummary: 'esquema staging · modo replace',
  inspectorObjectFileTargetRelationLabel: 'Relación de staging',
  inspectorObjectFileTargetCredentialLabel: 'Referencia de credencial PostgreSQL',
  inspectorObjectFileColumnsTitle: 'Mapeo de columnas',
  inspectorObjectFileAddColumnLabel: 'Añadir mapeo de columna',
  inspectorObjectFileRemoveColumnLabel: 'Eliminar mapeo de columna',
  inspectorObjectFileSourceFieldLabel: 'Campo origen',
  inspectorObjectFileTargetColumnLabel: 'Columna destino',
  inspectorObjectFileDataTypeLabel: 'Tipo PostgreSQL',
  inspectorObjectFileNullableLabel: 'Permite nulos',
  inspectorErrorObjectFileStorageUriInvalid:
    'Usa s3://<bucket>/tenants/<tenant>/<sha256> para el objeto inmutable.',
  inspectorErrorObjectFileSha256Invalid:
    'El SHA-256 debe contener exactamente 64 caracteres hexadecimales.',
  inspectorErrorObjectFileSizeInvalid:
    'El tamaño del objeto debe ser un número entero positivo, no superar 50000000 bytes y no superar el tamaño máximo.',
  inspectorErrorObjectFileMaxBytesInvalid:
    'El tamaño máximo debe ser un número entero positivo, no superar 50000000 bytes y ser al menos el tamaño del objeto.',
  inspectorErrorObjectFileSourceCredentialInvalid:
    'Usa una referencia de credencial opaca object-store:<id>.',
  inspectorErrorObjectFileTargetRelationInvalid:
    'La relación debe ser un identificador PostgreSQL válido en minúsculas.',
  inspectorErrorObjectFileTargetCredentialInvalid:
    'Usa una referencia de credencial opaca postgres:<id>.',
  inspectorErrorObjectFileColumnMappingInvalid:
    'Añade al menos un mapeo origen-destino válido y sin duplicados.',
} satisfies Partial<CanvasViewCopy>;
