/** Owned concern: provide concise localized copy for the Model editor, not semantic policy. */
const en = {
  back: 'Back to Canvas',
  editor: 'Semantic editor',
  sql: 'SQL',
  data: 'Data',
  expressionTree: 'Tree',
  properties: 'Properties',
  output: 'Output',
  reorderOutput: 'Reorder output field',
  reorderOutputHint: 'Drag or press Alt+Up/Down to reorder output fields.',
  inspectionOnly: 'Read-only inspection.',
  operationData: 'Data · operation',
  selectOperation: 'Open an operation to preview its output.',
  viewData: 'View data',
  execute: 'Run',
  openEditor: 'Double-click to open the semantic editor',
  openEditorAction: 'Open semantic editor',
  model: 'Relational transformation',
  applied: 'Applied version',
  draft: 'Unapplied changes',
  preview: 'Preview data',
  refresh: 'Refresh preview',
  previewHint: 'Explore the applied model without publishing a result.',
  previewEmpty: 'Run a preview to explore this model’s rows.',
  operationPreviewRecords: '{count}/{limit} records',
  operationPreviewEmpty: 'Preview the output of this operation.',
  operationPreviewUnapplied:
    'Save the condition and apply the composition to preview this revision.',
  operationPreviewFailed:
    'Preview unavailable for this operation. Check its inputs and the supported PostgreSQL profile.',
  empty: 'The query returned no rows.',
  loading: 'Loading preview…',
  unavailable: 'Data preview is not available in this workspace.',
  failed: 'The preview could not be loaded. Check the model inputs and try again.',
  saveFailed: 'The applied changes could not be saved. Preview has not run.',
  applyRejected: 'The model rejected these changes. Review the operation and try again.',
  applyNodeUnavailable: 'This model is no longer available. Your local changes were preserved.',
  stale: 'Out of date',
  staleHint: 'The model has changed. Refresh to see the applied version.',
  revision: 'Revision',
  rows: 'rows',
  sqlHint: 'Read-only SQL generated from the applied model.',
  sqlError: 'SQL is not available for this composition. Check its inputs and supported operations.',
  noModel: 'Connect a source and compose an operation to start.',
  leaveTitle: 'Keep your changes?',
  leaveDescription:
    'This operation has unapplied changes. Apply them to the model or discard them before leaving.',
  apply: 'Apply and continue',
  discard: 'Discard changes',
  stay: 'Keep editing',
  resources: 'Resources',
  showSources: 'Show sources',
  hideSources: 'Collapse sources',
  search: 'Search sources…',
  noMatches: 'No matching sources.',
  noCompatibleJoinFields: 'No compatible fields for this selection.',
  edit: 'Edit',
  editConditions: 'Edit conditions',
  expand: 'Details',
  collapse: 'Hide details',
  focus: 'Focus',
  exitFocus: 'Back to tree',
  conditions: 'conditions',
  columns: 'columns',
  pending: 'Sources available to add',
  queryInProgress: 'Preparing a preview of the applied version…',
  pendingPreview: 'Connected sources are still outside this model’s relational tree:',
  pendingPreviewHint:
    'Include them in a composition and apply it, or remove their Canvas connections if they are not needed.',
  missingPreview: 'The relational tree references disconnected sources:',
  missingPreviewHint: 'Reconnect these sources or update the composition before requesting data.',
  reviewInputs: 'Review inputs',
  operations: 'Operations',
  crossJoinWarning:
    'CROSS combines every row on L with every row on R. Cardinality remains unknown until preview.',
  removeCard: 'Remove from tree',
  removeDependents: 'Also remove dependent operations?',
  removeDependentsHint: 'These operations cannot remain valid after this removal:',
  closeEditor: 'Close semantic editor',
  workspaceTabs: 'Workspace navigation',
  removeKeepLeft: 'Remove JOIN · keep L',
  removeKeepRight: 'Remove JOIN · keep R',
  removalDependency:
    'Another operation depends on this card. Review its conditions, grouping or window before removing it.',
  removalUnavailable: 'This card cannot be removed from the current composition.',
  removalUnsupportedType:
    'The current single-source projection cannot preserve this input’s field types. The tree has not changed.',
  replaceOperation: 'Replace the current composition?',
  replaceProjectionHint:
    'The current profile cannot use a filtered projection as a JOIN or UNION input. Replacing it rebuilds the composition from the selected sources and removes its projection, filters and windows. Cancel keeps the current tree unchanged.',
  replaceOperationHint:
    'Changing the operation replaces this local composition. Cancel restores the applied version.',
  derivedOutput: {
    add: 'Add derived field',
    functionLabel: 'Function',
    operandsLabel: 'Ordered fields',
    addOperand: 'Add field',
    removeOperand: 'Remove field',
    aliasLabel: 'Output name',
    cancel: 'Cancel',
    save: 'Add field',
    failed: 'The derived field could not be added to this operation.',
  },
};
const es: typeof en = {
  back: 'Volver al Canvas',
  editor: 'Editor semántico',
  sql: 'SQL',
  data: 'Datos',
  expressionTree: 'Árbol',
  properties: 'Propiedades',
  output: 'Output',
  reorderOutput: 'Reordenar campo de salida',
  reorderOutputHint: 'Arrastra o pulsa Alt+Arriba/Abajo para reordenar los campos de salida.',
  inspectionOnly: 'Inspección de solo lectura.',
  operationData: 'Datos · operación',
  selectOperation: 'Abre una operación para previsualizar su salida.',
  viewData: 'Ver datos',
  execute: 'Ejecutar',
  openEditor: 'Haz doble clic para abrir el editor semántico',
  openEditorAction: 'Abrir editor semántico',
  model: 'Transformación relacional',
  applied: 'Versión aplicada',
  draft: 'Cambios sin aplicar',
  preview: 'Vista previa de datos',
  refresh: 'Actualizar vista previa',
  previewHint: 'Explora el modelo aplicado sin publicar un resultado.',
  previewEmpty: 'Ejecuta una vista previa para explorar las filas del modelo.',
  operationPreviewRecords: '{count}/{limit} registros',
  operationPreviewEmpty: 'Previsualiza la salida de esta operación.',
  operationPreviewUnapplied:
    'Guarda la condición y aplica la composición para previsualizar esta revisión.',
  operationPreviewFailed:
    'Vista previa no disponible para esta operación. Comprueba sus entradas y el perfil PostgreSQL admitido.',
  empty: 'La consulta no ha devuelto filas.',
  loading: 'Cargando vista previa…',
  unavailable: 'La vista previa de datos no está disponible en este espacio.',
  failed:
    'No se ha podido cargar la vista previa. Comprueba las entradas del modelo y vuelve a intentarlo.',
  saveFailed:
    'No se han podido guardar los cambios aplicados. No se ha consultado la vista previa.',
  applyRejected: 'El modelo ha rechazado estos cambios. Revisa la operación e inténtalo de nuevo.',
  applyNodeUnavailable: 'Este modelo ya no está disponible. Se han conservado tus cambios locales.',
  stale: 'Obsoleto',
  staleHint: 'El modelo ha cambiado. Actualiza para ver la versión aplicada.',
  revision: 'Revisión',
  rows: 'filas',
  sqlHint: 'SQL de solo lectura generado a partir del modelo aplicado.',
  sqlError:
    'El SQL no está disponible para esta composición. Comprueba sus entradas y operaciones admitidas.',
  noModel: 'Conecta una fuente y compón una operación para empezar.',
  leaveTitle: '¿Qué hacemos con tus cambios?',
  leaveDescription:
    'Esta operación tiene cambios sin aplicar. Aplícalos al modelo o descártalos antes de salir.',
  apply: 'Aplicar y continuar',
  discard: 'Descartar cambios',
  stay: 'Seguir editando',
  resources: 'Recursos',
  showSources: 'Mostrar fuentes',
  hideSources: 'Plegar fuentes',
  search: 'Buscar fuentes…',
  noMatches: 'No hay fuentes que coincidan.',
  noCompatibleJoinFields: 'No hay campos compatibles con esta selección.',
  edit: 'Editar',
  editConditions: 'Editar condiciones',
  expand: 'Detalles',
  collapse: 'Ocultar detalles',
  focus: 'Focus',
  exitFocus: 'Volver al árbol',
  conditions: 'condiciones',
  columns: 'columnas',
  pending: 'Fuentes disponibles para añadir',
  queryInProgress: 'Preparando la vista previa de la versión aplicada…',
  pendingPreview: 'Hay fuentes conectadas que aún no forman parte del árbol relacional:',
  pendingPreviewHint:
    'Inclúyelas en una composición y aplícala, o retira sus conexiones del Canvas si no las necesitas.',
  missingPreview: 'El árbol relacional hace referencia a fuentes desconectadas:',
  missingPreviewHint:
    'Reconecta estas fuentes o actualiza la composición antes de consultar datos.',
  reviewInputs: 'Revisar entradas',
  operations: 'Operaciones',
  crossJoinWarning:
    'CROSS combina cada fila de L con cada fila de R. La cardinalidad no se conoce hasta previsualizar.',
  removeCard: 'Retirar del árbol',
  removeDependents: '¿Retirar también las operaciones dependientes?',
  removeDependentsHint: 'Estas operaciones no pueden seguir siendo válidas tras la retirada:',
  closeEditor: 'Cerrar editor semántico',
  workspaceTabs: 'Navegación del espacio de trabajo',
  removeKeepLeft: 'Retirar JOIN · conservar L',
  removeKeepRight: 'Retirar JOIN · conservar R',
  removalDependency:
    'Otra operación depende de esta tarjeta. Revisa sus condiciones, agrupación o ventana antes de retirarla.',
  removalUnavailable: 'No se puede retirar esta tarjeta de la composición actual.',
  removalUnsupportedType:
    'La proyección actual de una sola fuente no puede conservar los tipos de esta entrada. El árbol no se ha modificado.',
  replaceOperation: '¿Reemplazar la composición actual?',
  replaceProjectionHint:
    'El perfil actual no admite una proyección filtrada como entrada de JOIN o UNION. Al sustituirla se reconstruye la composición con las fuentes seleccionadas y se retiran su proyección, filtros y ventanas. Cancelar mantiene el árbol actual intacto.',
  replaceOperationHint:
    'Cambiar la operación reemplaza esta composición local. Cancelar recupera la versión aplicada.',
  derivedOutput: {
    add: 'Añadir campo derivado',
    functionLabel: 'Función',
    operandsLabel: 'Campos ordenados',
    addOperand: 'Añadir campo',
    removeOperand: 'Retirar campo',
    aliasLabel: 'Nombre de salida',
    cancel: 'Cancelar',
    save: 'Añadir campo',
    failed: 'No se ha podido añadir el campo derivado a esta operación.',
  },
};
export type CanvasSemanticEditorCopy = typeof en;
export function resolveCanvasSemanticEditorCopy(language: string): CanvasSemanticEditorCopy {
  return language === 'es' ? es : en;
}
