/** Owned concern: provide concise localized copy for the Model editor, not semantic policy. */
const en = {
  back: 'Back to Canvas',
  editor: 'Semantic editor',
  sql: 'SQL',
  data: 'Data',
  viewData: 'View data',
  openEditor: 'Double-click to open the semantic editor',
  model: 'Relational transformation',
  applied: 'Applied version',
  draft: 'Unapplied changes',
  preview: 'Preview data',
  refresh: 'Refresh preview',
  previewHint: 'Explore the applied model without publishing a result.',
  previewEmpty: 'Run a preview to explore this model’s rows.',
  empty: 'The query returned no rows.',
  loading: 'Loading preview…',
  unavailable: 'Data preview is not available in this workspace.',
  failed: 'The preview could not be loaded. Check the model inputs and try again.',
  saveFailed: 'The applied changes could not be saved. Preview has not run.',
  stale: 'Out of date',
  staleHint: 'The model has changed. Refresh to see the applied version.',
  revision: 'Revision',
  rows: 'rows',
  sqlHint: 'Read-only SQL generated from the applied model.',
  sqlError: 'SQL is not available for this composition. Check its inputs and supported operations.',
  noModel: 'Connect a source and compose an operation to start.',
  leaveTitle: 'Keep your changes?',
  leaveDescription:
    'This operation has unapplied changes. Apply them to the model or discard them before leaving.',
  apply: 'Apply and continue',
  discard: 'Discard changes',
  stay: 'Keep editing',
  resources: 'Resources',
  showSources: 'Show sources',
  hideSources: 'Collapse sources',
  search: 'Search sources…',
  noMatches: 'No matching sources.',
  edit: 'Edit composition',
  editConditions: 'Edit conditions',
  expand: 'Details',
  collapse: 'Hide details',
  focus: 'Focus',
  exitFocus: 'Back to tree',
  conditions: 'conditions',
  columns: 'columns',
  pending: 'Sources available to add',
  queryInProgress: 'Preparing a preview of the applied version…',
  pendingPreview: 'Connected sources are still outside this model’s relational tree:',
  pendingPreviewHint:
    'Include them in a composition and apply it, or remove their Canvas connections if they are not needed.',
  missingPreview: 'The relational tree references disconnected sources:',
  missingPreviewHint: 'Reconnect these sources or update the composition before requesting data.',
  reviewInputs: 'Review inputs',
  operations: 'Operations',
  removeCard: 'Remove from tree',
  removeKeepLeft: 'Remove JOIN · keep L',
  removeKeepRight: 'Remove JOIN · keep R',
  removalDependency:
    'Another operation depends on this card. Review its conditions, grouping or window before removing it.',
  removalUnavailable: 'This card cannot be removed from the current composition.',
  removalUnsupportedType:
    'The current single-source projection cannot preserve this input’s field types. The tree has not changed.',
  replaceOperation: 'Replace the current composition?',
  replaceOperationHint:
    'Changing the operation replaces this local composition. Cancel restores the applied version.',
};
const es: typeof en = {
  back: 'Volver al Canvas',
  editor: 'Editor semántico',
  sql: 'SQL',
  data: 'Datos',
  viewData: 'Ver datos',
  openEditor: 'Haz doble clic para abrir el editor semántico',
  model: 'Transformación relacional',
  applied: 'Versión aplicada',
  draft: 'Cambios sin aplicar',
  preview: 'Vista previa de datos',
  refresh: 'Actualizar vista previa',
  previewHint: 'Explora el modelo aplicado sin publicar un resultado.',
  previewEmpty: 'Ejecuta una vista previa para explorar las filas del modelo.',
  empty: 'La consulta no ha devuelto filas.',
  loading: 'Cargando vista previa…',
  unavailable: 'La vista previa de datos no está disponible en este espacio.',
  failed:
    'No se ha podido cargar la vista previa. Comprueba las entradas del modelo y vuelve a intentarlo.',
  saveFailed:
    'No se han podido guardar los cambios aplicados. No se ha consultado la vista previa.',
  stale: 'Obsoleto',
  staleHint: 'El modelo ha cambiado. Actualiza para ver la versión aplicada.',
  revision: 'Revisión',
  rows: 'filas',
  sqlHint: 'SQL de solo lectura generado a partir del modelo aplicado.',
  sqlError:
    'El SQL no está disponible para esta composición. Comprueba sus entradas y operaciones admitidas.',
  noModel: 'Conecta una fuente y compón una operación para empezar.',
  leaveTitle: '¿Qué hacemos con tus cambios?',
  leaveDescription:
    'Esta operación tiene cambios sin aplicar. Aplícalos al modelo o descártalos antes de salir.',
  apply: 'Aplicar y continuar',
  discard: 'Descartar cambios',
  stay: 'Seguir editando',
  resources: 'Recursos',
  showSources: 'Mostrar fuentes',
  hideSources: 'Plegar fuentes',
  search: 'Buscar fuentes…',
  noMatches: 'No hay fuentes que coincidan.',
  edit: 'Editar composición',
  editConditions: 'Editar condiciones',
  expand: 'Detalles',
  collapse: 'Ocultar detalles',
  focus: 'Focus',
  exitFocus: 'Volver al árbol',
  conditions: 'condiciones',
  columns: 'columnas',
  pending: 'Fuentes disponibles para añadir',
  queryInProgress: 'Preparando la vista previa de la versión aplicada…',
  pendingPreview: 'Hay fuentes conectadas que aún no forman parte del árbol relacional:',
  pendingPreviewHint:
    'Inclúyelas en una composición y aplícala, o retira sus conexiones del Canvas si no las necesitas.',
  missingPreview: 'El árbol relacional hace referencia a fuentes desconectadas:',
  missingPreviewHint:
    'Reconecta estas fuentes o actualiza la composición antes de consultar datos.',
  reviewInputs: 'Revisar entradas',
  operations: 'Operaciones',
  removeCard: 'Retirar del árbol',
  removeKeepLeft: 'Retirar JOIN · conservar L',
  removeKeepRight: 'Retirar JOIN · conservar R',
  removalDependency:
    'Otra operación depende de esta tarjeta. Revisa sus condiciones, agrupación o ventana antes de retirarla.',
  removalUnavailable: 'No se puede retirar esta tarjeta de la composición actual.',
  removalUnsupportedType:
    'La proyección actual de una sola fuente no puede conservar los tipos de esta entrada. El árbol no se ha modificado.',
  replaceOperation: '¿Reemplazar la composición actual?',
  replaceOperationHint:
    'Cambiar la operación reemplaza esta composición local. Cancelar recupera la versión aplicada.',
};
export type CanvasSemanticEditorCopy = typeof en;
export function resolveCanvasSemanticEditorCopy(language: string): CanvasSemanticEditorCopy {
  return language === 'es' ? es : en;
}
