import type { CanvasViewCopy } from './canvasCopy.types';

export const canvasViewExecutionCopyEs = {
  planPermissionDeniedMessage: 'No tienes permisos para crear Execution Previews',
  planSqlArtifactRequiredMessage:
    'La provenance del preview debe resolver el artefacto SQL antes de crear un Execution Preview persistido.',
  planUnableToCreateMessage: 'No se ha podido crear el Execution Preview',
  planGraphModelSqlDivergenceMessageTemplate:
    'Código de proyecto contiene una edición más reciente en {path}. El Preview se ha detenido sin sobrescribirla. Continúa desde un proyecto DBT con autoridad de archivos o restaura la revisión generada por el Canvas.',
  planGraphAuthorityRefusedMessage:
    'La previsualización se detuvo porque este Canvas no tiene autoridad graph-draft exclusiva. Abre el proyecto con autoridad de ficheros o resuelve el conflicto de autoridad del Canvas.',
  planGraphDbtCompilationFailedMessage:
    'La previsualización se detuvo porque la compilación nativa de DBT no validó los modelos generados. Revisa el SQL del modelo y la configuración del destino.',
  previewProvenanceTransformPathRequiredMessage:
    'Execution Preview necesita contenido SQL. Selecciona un fichero SQL del workspace para el SQL transform o usa un transform creado en el canvas para que DVT lo cree.',
  previewProvenanceWorkspaceNotConfiguredMessage:
    'La provenance del preview no esta configurada para este workspace. Define el repo Git y la ruta del artefacto de grafo antes de planificar.',
  previewProvenanceExplicitGitRevisionRequiredMessage:
    'La provenance del preview requiere una rama y un commit Git explicitos antes de planificar.',
  previewProvenanceWorkspaceFilesUnavailableMessage:
    'No se ha podido resolver la provenance del preview a partir de los ficheros del workspace.',
  runPermissionDeniedMessage: 'No tienes permisos para arrancar runs',
  runNoPlanMessage: 'No hay un Execution Preview disponible: previsualiza la ejecucion antes.',
  runPreviewStaleMessage:
    'Execution Preview esta obsoleto. Previsualiza la ejecucion otra vez antes de arrancar.',
  runPlanRefUnavailableMessage:
    'La referencia del Execution Preview no esta disponible para este modo',
  runPersistedPreviewRequiredMessage:
    'El arranque del run requiere un Execution Preview persistido y vinculado a la referencia de Execution Preview actual. Previsualiza la ejecucion otra vez primero.',
  runFailedMessage: 'No se ha podido arrancar el run',
  canvasExecutionUnavailableMessage:
    'Execution Preview y el arranque de run no estan disponibles para este tipo de canvas.',
  dbtExplicitSelectionRequiresExecutableResourceMessage:
    'La seleccion contiene recursos no disponibles o no ejecutables. Resuelve la seleccion explicita en Operaciones antes del Preview.',
  planCreatedMessage: 'Vista previa de ejecución creada',
  planPreviewTitle: 'Vista previa de ejecución',
  planPreviewReadOnlyLabel: 'Solo lectura',
  planPreviewDescription: 'Revisa la vista previa inmutable antes de iniciar una ejecución.',
  planPreviewNotEstimatedValue: 'Sin estimar',
  planPreviewIdentityTitle: 'Identidad de la vista previa',
  planPreviewIdentityCaption: 'Identificadores inmutables de la vista previa persistida.',
  planPreviewIdLabel: 'ID de vista previa',
  planPreviewVersionLabel: 'Versión',
  planPreviewRefLabel: 'Referencia de vista previa',
  planPreviewGeneratedLabel: 'Generada',
  planPreviewEstimatedCostLabel: 'Coste estimado',
  planPreviewExecutionTargetTitle: 'Destino de ejecución',
  planPreviewExecutionTargetCaption: 'Configuración de ejecución que se usará al iniciar.',
  planPreviewExecutorLabel: 'Ejecutor',
  planPreviewNotReportedValue: 'Sin informar',
  planPreviewAdapterLabel: 'Adaptador',
  planPreviewUnknownValue: 'Desconocido',
  planPreviewTargetLabel: 'Destino',
  planPreviewConnectionLabel: 'Conexión',
  planPreviewResolutionSourceLabel: 'Resuelto por',
  planPreviewEnvironmentDefaultValue: 'Predeterminado del entorno',
  planPreviewCapabilitiesLabel: 'Capacidades',
  planPreviewSummaryTitle: 'Resumen de la vista previa persistida',
  planPreviewSummaryCaption:
    'Tamaño del grafo y alcance de tablas guardados en la vista previa de ejecución.',
  planPreviewNodesLabel: 'Nodos',
  planPreviewStepsLabel: 'Pasos',
  planPreviewSourceTablesLabel: 'Tablas de origen',
  planPreviewSinkTablesLabel: 'Tablas de destino',
  planPreviewUnavailableValue: 'No disponible',
  planPreviewPersistenceTitle: 'Evidencia de persistencia',
  planPreviewPersistenceCaption:
    'Prueba de que esta vista previa está respaldada por un registro canónico.',
  planPreviewRecordLabel: 'Registro de vista previa',
  planPreviewCanonicalShaLabel: 'SHA canónico de la vista previa',
  planPreviewSelectionTitle: 'Selección de ejecución',
  planPreviewSelectionCaption:
    'Raíces solicitadas y dependencias incluidas por la política de cierre gobernada.',
  planPreviewSelectionModeLabel: 'Modo de selección',
  planPreviewSelectionExplicitValue: 'Explícita',
  planPreviewSelectionWorkspaceDefaultValue: 'Predeterminada del espacio de trabajo',
  planPreviewRequestedResourcesLabel: 'Recursos solicitados',
  planPreviewIncludedDependenciesLabel: 'Dependencias incluidas',
  planPreviewNoneValue: 'Ninguna',
  planPreviewAuthorizedScopeLabel: 'Alcance de ejecución autorizado',
  planPreviewProvenanceTitle: 'Procedencia',
  planPreviewDbtProvenanceCaption:
    'Revisión autoritativa del proyecto dbt y destino de ejecución controlado por el servidor.',
  planPreviewRepositoryProvenanceCaption:
    'Artefactos del repositorio usados para generar la vista previa.',
  planPreviewCanvasLabel: 'Canvas',
  planPreviewProjectRootLabel: 'Raíz del proyecto',
  planPreviewDbtVersionLabel: 'Versión de dbt',
  planPreviewProjectRevisionLabel: 'Revisión del proyecto',
  planPreviewAnalysisRevisionLabel: 'Revisión del análisis',
  planPreviewSelectedResourcesLabel: 'Recursos seleccionados',
  planPreviewGraphArtifactLabel: 'Artefacto del grafo',
  planPreviewSqlArtifactLabel: 'Artefacto SQL',
  planPreviewExecutionStepsTitle: 'Pasos de ejecución',
  planPreviewExecutionStepsCaption:
    'Orden de los pasos y políticas que se enviarán al motor de ejecución.',
  planPreviewStepLabel: 'Paso',
  planPreviewNodeSuffix: 'nodo',
  planPreviewNodesSuffix: 'nodos',
  planPreviewTimeoutLabel: 'Tiempo límite',
  planPreviewRetriesLabel: 'Reintentos',
  planPreviewConcurrencyLabel: 'Concurrencia',
  planPreviewWarehouseLabel: 'Almacén',
  planPreviewExportJsonAction: 'Exportar JSON',
  planPreviewStartRunAction: 'Iniciar ejecución',
  planPreviewSelectionRejectedTitle: 'Vista previa de ejecución rechazada',
  planPreviewSelectionRejectedDescription: 'La selección de ejecución actual no ha sido admitida.',
  planPreviewPlanInvalidTitle: 'Vista previa de ejecución no ejecutable',
  planPreviewPlanInvalidDescription:
    'La vista previa persistida no ha superado la validación del motor de ejecución.',
  planPreviewUnknownCodeMessage:
    'La vista previa de ejecución ha sido rechazada. Revisa el código técnico.',
  planPreviewCodeLabel: 'Código técnico',
  planPreviewCauseLabel: 'Causa',
  planPreviewReasonLabel: 'Motivo',
  planPreviewCloseLabel: 'Cerrar',
  planPreviewDecisionsTitle: 'Decisiones de ejecución',
  planPreviewDecisionsCaption:
    'Decisiones del planificador persistidas con esta vista previa inmutable.',
  planPreviewDecisionSubjectLabel: 'Sujeto',
  planPreviewDecisionStatusLabel: 'Decisión',
  planPreviewDecisionReasonLabel: 'Motivo del planificador',
  planPreviewDecisionIncludedLabel: 'Alcance incluido',
  planPreviewDecisionExcludedLabel: 'Alcance excluido',
  planPreviewDecisionRunLabel: 'Ejecutar',
  planPreviewDecisionSkipLabel: 'Omitir',
  planPreviewDecisionPartialLabel: 'Parcial',
  planPreviewDecisionSelectedRootReason: 'Raíz de ejecución seleccionada explícitamente.',
  planPreviewDecisionSelectedClosureReason:
    'Dependencia incluida por el cierre de ejecución seleccionado.',
  planPreviewDecisionOutsideClosureReason: 'Fuera del cierre de ejecución seleccionado.',
  planPreviewDecisionBoundedSelectionReason:
    'El alcance de ejecución seleccionado incluye solo una parte del grafo.',
  runStartedMessage: 'Run arrancado',
  planStatusRunUnavailableMessage: 'El arranque de runs no esta disponible en este contexto.',
  planStatusPreviewRequiredMessage: 'Se requiere un preview antes de arrancar.',
  planStatusPreviewNotAlignedMessage:
    'Execution Preview no esta alineado con la referencia de Execution Preview activa. Previsualiza la ejecucion otra vez antes de arrancar.',
  planStatusPreviewNotPersistedMessage:
    'Execution Preview no esta persistido. Previsualiza la ejecucion para crear un preview persistido.',
  planStatusPreviewReadyMessage: 'La vista previa actual está lista para iniciar.',
  operationalDrawerTitle: 'Operaciones del Canvas',
  operationalDrawerLogTab: 'Registro',
  operationalDrawerProblemsTab: 'Problemas',
  operationalDrawerRunsTab: 'Ejecuciones',
  operationalDrawerPreviewTab: 'Vista previa',
  operationalDrawerDataTab: 'Datos',
  operationalDrawerProblemsAriaLabel: 'Problemas del Canvas',
  operationalDrawerNoProblemsMessage: 'No hay problemas actuales en el Canvas.',
  operationalDrawerRunsAriaLabel: 'Ejecuciones del Canvas',
  operationalDrawerRunReadyStatus: 'Ejecución lista',
  operationalDrawerRunBlockedStatus: 'Ejecución bloqueada',
  operationalDrawerRunActiveStatus: 'Ejecución activa',
  operationalDrawerActiveRunSummaryTemplate: 'La ejecución {runId} está activa.',
  operationalDrawerReadyRunSummary:
    'La ejecución está lista tras la vista previa de ejecución actual.',
  operationalDrawerPreviewAriaLabel: 'Vista previa de ejecución del Canvas',
  operationalDrawerPreviewAction: 'Crear Execution Preview',
  operationalDrawerPreviewReadyStatus: 'Vista previa lista',
  operationalDrawerPreviewBlockedStatus: 'Vista previa bloqueada',
  operationalDrawerDataAriaLabel: 'Muestra de datos del origen',
  operationalDrawerDataIdleMessage:
    'Haz doble clic en la zona de filas y tamaño de un origen importado para ver una muestra.',
  operationalDrawerDataLoadingTemplate: 'Cargando una muestra de datos de {nodeName}…',
  operationalDrawerDataEmptyTemplate: '{nodeName} no ha devuelto filas.',
  operationalDrawerDataConnectionNotFoundTemplate:
    'La conexión gobernada de {nodeName} ya no está disponible.',
  operationalDrawerDataSourceObjectNotFoundTemplate:
    'El objeto de origen de {nodeName} ya no está disponible.',
  operationalDrawerDataUnavailableTemplate: 'No se ha podido leer la muestra de {nodeName}.',
  operationalDrawerDataUnknownErrorTemplate: 'No se ha podido cargar la muestra de {nodeName}.',
  operationalDrawerDataTruncatedTemplate: 'Se muestran las primeras {limit} filas.',
  operationalDrawerDataCaptionTemplate: 'Muestra de datos de {nodeName}',
  operationalDrawerDataNullValue: 'NULO',
  sourceDataSampleInteractionLabel:
    'Haz doble clic en esta zona de métricas o pulsa Intro para abrir una muestra de datos.',
  operationalDrawerTabsAriaLabel: 'Cajón operativo del Canvas',
  operationalDrawerInfoSeverity: 'Información',
  operationalDrawerWarningSeverity: 'Advertencia',
  operationalDrawerErrorSeverity: 'Error',
  operationalDrawerPlanIntegrityBlocker: 'Integridad del Execution Preview',
  operationalDrawerBackpressureBlocker: 'Saturación temporal',
  operationalDrawerCapabilityMismatchBlocker: 'Capacidad incompatible',
  operationalDrawerAdapterDegradedBlocker: 'Adaptador degradado',
  operationalDrawerAuthorizationDeniedBlocker: 'Autorización denegada',
  planStatusBackpressureMessage:
    'La admisión del runtime está temporalmente saturada. Reinténtalo cuando se recupere la capacidad.',
  planStatusAdapterDegradedMessage:
    'El adaptador de ejecución está degradado. El arranque seguirá bloqueado hasta que se recupere el runtime.',
  selectionRecoveryTitle: 'Selección de ejecución',
  selectionRecoveryReadyStatus: 'lista',
  selectionRecoveryBlockedStatus: 'bloqueada',
  selectionRecoveryRequestedRootsLabel: 'Raíces solicitadas',
  selectionRecoveryUnavailableRootsLabel: 'Raíces no disponibles',
  selectionRecoveryNonExecutableRootsLabel: 'Raíces no ejecutables',
  selectionRecoveryDerivedDependenciesLabel: 'Dependencias derivadas',
  selectionRecoveryAdmittedScopeLabel: 'Alcance admitido',
  selectionRecoveryLastPreviewRevisionLabel: 'Última revisión del preview',
  selectionRecoveryEmptyValue: 'Ninguno',
  selectionRecoveryDiscardUnavailableAction: 'Descartar selección no disponible',
  selectionRecoveryUseWorkspaceScopeAction: 'Usar alcance del workspace',
  selectionRecoveryRefreshAnalysisAction: 'Mantener bloqueo y actualizar análisis',
  selectionRecoveryRefreshingAnalysisAction: 'Actualizando análisis autoritativo...',
  selectionRecoveryRefreshFailureMessage: 'No se pudo actualizar el análisis autoritativo.',
  selectionRecoveryProblemSummary: 'La selección de ejecución requiere recuperación.',
  selectionRecoveryProblemDetail:
    'Las raíces solicitadas no disponibles o no ejecutables deben resolverse antes del Preview.',
  selectionRecoveryBlockerLabel: 'Selección de ejecución',
  selectionRecoveryDiscardReceiptTemplate:
    'Raíces no disponibles descartadas: {affected}. Raíces explícitas conservadas: {retained}.',
  selectionRecoveryWorkspaceReceiptTemplate:
    'Raíces explícitas reemplazadas: {affected} por el alcance del workspace.',
  selectionRecoveryRefreshReceiptTemplate:
    'Raíces solicitadas conservadas: {retained}. Análisis autoritativo actualizado.',
} satisfies Partial<CanvasViewCopy>;
