/** Spanish copy for node property sections. */
export const nodePropertyCopyEs = {
  sectionLabels: {
    general: 'General',
    columns: 'Columnas',
    'inputs-outputs': 'Entradas y salidas',
    tests: 'Pruebas',
    keys: 'Claves',
    indexes: 'Índices',
    'foreign-keys': 'Claves externas',
    constraints: 'Restricciones',
    comments: 'Comentarios',
    sink: 'Salida',
    code: 'Código',
    summary: 'Resumen',
  },
  sectionEmptyStates: {
    columns: 'No hay columnas registradas para este nodo.',
    'inputs-outputs': 'No hay entradas ni salidas del grafo registradas para este nodo.',
    tests: 'No hay pruebas dbt ni de calidad de datos registradas para este nodo.',
    keys: 'No hay claves registradas para este nodo.',
    indexes: 'No hay índices registrados para este nodo.',
    'foreign-keys': 'No hay claves externas registradas para este nodo.',
    constraints: 'No hay restricciones de tabla registradas para este nodo.',
    comments: 'No hay comentarios registrados para este nodo.',
    sink: 'No hay destino de salida ni política de escritura registrados para este nodo.',
    fallback: 'No hay propiedades registradas para esta sección.',
  },
  rowLabels: {
    'last-run': 'Última ejecución',
    name: 'Nombre',
    'node-id': 'ID del nodo',
    kind: 'Tipo',
    role: 'Rol',
    status: 'Estado',
    plugin: 'Plugin',
    package: 'Paquete',
    materialization: 'Materialización',
    connection: 'Conexión',
    database: 'Base de datos',
    schema: 'Esquema',
    table: 'Tabla',
    source: 'Origen',
    path: 'Ruta',
    owner: 'Responsable',
    duration: 'Duración',
    cost: 'Coste',
    destination: 'Destino',
    'write-mode': 'Modo de escritura',
    'partition-strategy': 'Estrategia de partición',
    description: 'Descripción',
    comment: 'Comentario',
    'upstream-nodes': 'Nodos anteriores',
    'downstream-nodes': 'Nodos posteriores',
    tags: 'Etiquetas',
  },
  columnLabels: {
    name: 'Nombre',
    type: 'Tipo',
    nullable: 'Admite nulos',
    key: 'Clave',
    default: 'Predeterminado',
    comment: 'Comentario',
    source: 'Origen',
    reference: 'Referencia',
    selection: 'Selección',
    columns: 'Columnas',
    unique: 'Único',
    localColumns: 'Columnas locales',
    referencedTable: 'Tabla referenciada',
    referencedColumns: 'Columnas referenciadas',
    expression: 'Expresión',
    direction: 'Dirección',
    node: 'Nodo',
    kind: 'Tipo',
    severity: 'Severidad',
    status: 'Estado',
    nodeId: 'ID del nodo',
    relation: 'Relación',
    connection: 'Conexión',
    target: 'Objetivo',
    test: 'Prueba',
    package: 'Paquete',
  },
  valueLabels: {
    'not calculated': 'No calculado',
    yes: 'Sí',
    no: 'No',
    primary: 'Primaria',
    unique: 'Única',
    'not null': 'No nulo',
    nullable: 'Admite nulos',
    selected: 'Seleccionada',
    available: 'Disponible',
    incoming: 'Entrada',
    outgoing: 'Salida',
    input: 'Entrada',
    transform: 'Transformación',
    check: 'Validación',
    output: 'Salida',
    pending: 'Pendiente',
    idle: 'Inactivo',
    running: 'En ejecución',
    success: 'Correcto',
    failed: 'Fallido',
    skipped: 'Omitido',
    warn: 'Advertencia',
    cancelled: 'Cancelado',
    blocked: 'Bloqueado',
    draft: 'Borrador',
    ready: 'Listo',
    lineage: 'Linaje',
    validation: 'Validación',
    dependency: 'Dependencia',
    authored: 'Escrito',
    generated: 'Generado',
    canonical: 'Canónico',
    file: 'Archivo',
  },
} as const;
