/** English copy for node property sections. */
export const nodePropertyCopyEn = {
  sectionLabels: {
    general: 'General',
    columns: 'Columns',
    'inputs-outputs': 'Inputs / Outputs',
    tests: 'Tests',
    keys: 'Keys',
    indexes: 'Indexes',
    'foreign-keys': 'Foreign keys',
    constraints: 'Constraints',
    comments: 'Comments',
    sink: 'Sink',
    code: 'Code',
    summary: 'Summary',
  },
  sectionEmptyStates: {
    columns: 'No columns are recorded for this node.',
    'inputs-outputs': 'No graph inputs or outputs are recorded for this node.',
    tests: 'No dbt or data-quality tests are recorded for this node.',
    keys: 'No keys are recorded for this node.',
    indexes: 'No indexes are recorded for this node.',
    'foreign-keys': 'No foreign keys are recorded for this node.',
    constraints: 'No table constraints are recorded for this node.',
    comments: 'No comments are recorded for this node.',
    sink: 'No sink target or write policy is recorded for this node.',
    fallback: 'No properties are recorded for this section.',
  },
  rowLabels: { 'last-run': 'Last run' },
  columnLabels: {
    connection: 'Connection',
  },
  valueLabels: {
    'not calculated': 'Not calculated',
    yes: 'Yes',
    no: 'No',
    pending: 'Pending',
    idle: 'Inactive',
    running: 'Running',
    success: 'Completed',
    failed: 'Failed',
    skipped: 'Skipped',
    warn: 'Warning',
    cancelled: 'Cancelled',
    blocked: 'Blocked',
    draft: 'Draft',
    ready: 'Ready',
    input: 'Input',
    authored: 'Authored',
    generated: 'Generated',
    canonical: 'Canonical',
    file: 'File',
  },
} as const;
