/** Owned concern: adapt route-localized Canvas copy into the node-presentation DTO. */
import type { CanvasNodePresentationCopy } from '../../components/canvas/canvasNodePresentationCopy.contract';
import type { CanvasViewCopy } from './canvasCopy.types';

const NODE_PROPERTY_PRESENTATION_COPY = {
  en: {
    sectionLabels: {
      general: 'General',
      columns: 'Columns',
      'inputs-outputs': 'Inputs / Outputs',
      tests: 'Tests',
      keys: 'Keys',
      indexes: 'Indexes',
      'foreign-keys': 'Foreign keys',
      constraints: 'Constraints',
      comments: 'Comments',
      sink: 'Sink',
      code: 'Code',
      summary: 'Summary',
    },
    sectionEmptyStates: {
      columns: 'No columns are recorded for this node.',
      'inputs-outputs': 'No graph inputs or outputs are recorded for this node.',
      tests: 'No dbt or data-quality tests are recorded for this node.',
      keys: 'No keys are recorded for this node.',
      indexes: 'No indexes are recorded for this node.',
      'foreign-keys': 'No foreign keys are recorded for this node.',
      constraints: 'No table constraints are recorded for this node.',
      comments: 'No comments are recorded for this node.',
      sink: 'No sink target or write policy is recorded for this node.',
      fallback: 'No properties are recorded for this section.',
    },
    rowLabels: {},
    columnLabels: {
      connection: 'Connection',
    },
    valueLabels: {
      yes: 'Yes',
      no: 'No',
      pending: 'Pending',
      idle: 'Inactive',
      running: 'Running',
      success: 'Completed',
      failed: 'Failed',
      skipped: 'Skipped',
      warn: 'Warning',
      cancelled: 'Cancelled',
      blocked: 'Blocked',
      draft: 'Draft',
      ready: 'Ready',
      input: 'Input',
      authored: 'Authored',
      generated: 'Generated',
      canonical: 'Canonical',
      file: 'File',
    },
  },
  es: {
    sectionLabels: {
      general: 'General',
      columns: 'Columnas',
      'inputs-outputs': 'Entradas y salidas',
      tests: 'Pruebas',
      keys: 'Claves',
      indexes: 'Índices',
      'foreign-keys': 'Claves externas',
      constraints: 'Restricciones',
      comments: 'Comentarios',
      sink: 'Salida',
      code: 'Código',
      summary: 'Resumen',
    },
    sectionEmptyStates: {
      columns: 'No hay columnas registradas para este nodo.',
      'inputs-outputs': 'No hay entradas ni salidas del grafo registradas para este nodo.',
      tests: 'No hay pruebas dbt ni de calidad de datos registradas para este nodo.',
      keys: 'No hay claves registradas para este nodo.',
      indexes: 'No hay índices registrados para este nodo.',
      'foreign-keys': 'No hay claves externas registradas para este nodo.',
      constraints: 'No hay restricciones de tabla registradas para este nodo.',
      comments: 'No hay comentarios registrados para este nodo.',
      sink: 'No hay destino de salida ni política de escritura registrados para este nodo.',
      fallback: 'No hay propiedades registradas para esta sección.',
    },
    rowLabels: {
      name: 'Nombre',
      'node-id': 'ID del nodo',
      kind: 'Tipo',
      role: 'Rol',
      status: 'Estado',
      plugin: 'Plugin',
      package: 'Paquete',
      materialization: 'Materialización',
      connection: 'Conexión',
      database: 'Base de datos',
      schema: 'Esquema',
      table: 'Tabla',
      source: 'Origen',
      path: 'Ruta',
      owner: 'Responsable',
      rows: 'Filas',
      size: 'Tamaño',
      duration: 'Duración',
      cost: 'Coste',
      destination: 'Destino',
      'write-mode': 'Modo de escritura',
      'partition-strategy': 'Estrategia de partición',
      description: 'Descripción',
      comment: 'Comentario',
      'upstream-nodes': 'Nodos anteriores',
      'downstream-nodes': 'Nodos posteriores',
      tags: 'Etiquetas',
    },
    columnLabels: {
      name: 'Nombre',
      type: 'Tipo',
      nullable: 'Admite nulos',
      key: 'Clave',
      default: 'Predeterminado',
      comment: 'Comentario',
      source: 'Origen',
      reference: 'Referencia',
      selection: 'Selección',
      columns: 'Columnas',
      unique: 'Único',
      localColumns: 'Columnas locales',
      referencedTable: 'Tabla referenciada',
      referencedColumns: 'Columnas referenciadas',
      expression: 'Expresión',
      direction: 'Dirección',
      node: 'Nodo',
      kind: 'Tipo',
      severity: 'Severidad',
      status: 'Estado',
      nodeId: 'ID del nodo',
      relation: 'Relación',
      connection: 'Conexión',
      target: 'Objetivo',
      test: 'Prueba',
      package: 'Paquete',
    },
    valueLabels: {
      yes: 'Sí',
      no: 'No',
      primary: 'Primaria',
      unique: 'Única',
      'not null': 'No nulo',
      nullable: 'Admite nulos',
      selected: 'Seleccionada',
      available: 'Disponible',
      incoming: 'Entrada',
      outgoing: 'Salida',
      input: 'Entrada',
      transform: 'Transformación',
      check: 'Validación',
      output: 'Salida',
      pending: 'Pendiente',
      idle: 'Inactivo',
      running: 'En ejecución',
      success: 'Correcto',
      failed: 'Fallido',
      skipped: 'Omitido',
      warn: 'Advertencia',
      cancelled: 'Cancelado',
      blocked: 'Bloqueado',
      draft: 'Borrador',
      ready: 'Listo',
      lineage: 'Linaje',
      validation: 'Validación',
      dependency: 'Dependencia',
      authored: 'Escrito',
      generated: 'Generado',
      canonical: 'Canónico',
      file: 'Archivo',
    },
  },
} as const;

export function buildCanvasNodePresentationCopy(
  copy: CanvasViewCopy,
  locale = 'en'
): CanvasNodePresentationCopy {
  const normalizedLocale = locale.trim().toLowerCase();
  const nodePropertyCopy = normalizedLocale.startsWith('es')
    ? NODE_PROPERTY_PRESENTATION_COPY.es
    : NODE_PROPERTY_PRESENTATION_COPY.en;

  return {
    columnsLabel: copy.nodePresentationColumnsLabel,
    declaredColumnsDetailTemplate: copy.nodePresentationDeclaredColumnsDetailTemplate,
    inheritedColumnsDetailTemplate: copy.nodePresentationInheritedColumnsDetailTemplate,
    mixedColumnsDetailTemplate: copy.nodePresentationMixedColumnsDetailTemplate,
    noColumnsDetail: copy.nodePresentationNoColumnsDetail,
    codeLabel: copy.nodePresentationCodeLabel,
    workspaceCodeDetailTemplate: copy.nodePresentationWorkspaceCodeDetailTemplate,
    generatedCodeDetailTemplate: copy.nodePresentationGeneratedCodeDetailTemplate,
    canonicalSubstraitCodeDetailTemplate: copy.nodePresentationCanonicalSubstraitCodeDetailTemplate,
    invalidCanonicalSubstraitCodeMessage: copy.nodePresentationInvalidCanonicalSubstraitCodeMessage,
    codeUnavailableMessage: copy.nodePresentationCodeUnavailableMessage,
    readyStatusLabel: copy.nodePresentationReadyStatusLabel,
    draftStatusLabel: copy.nodePresentationDraftStatusLabel,
    authoringTagLabel: copy.nodePresentationAuthoringTagLabel,
    locale,
    sectionLabels: nodePropertyCopy.sectionLabels,
    sectionEmptyStates: nodePropertyCopy.sectionEmptyStates,
    rowLabels: nodePropertyCopy.rowLabels,
    columnLabels: nodePropertyCopy.columnLabels,
    valueLabels: nodePropertyCopy.valueLabels,
    kindLabels: {
      'dbt:source': copy.nodePresentationSourceKindLabel,
      'dvt:source': copy.nodePresentationSourceKindLabel,
      'dbt:model': copy.nodePresentationModelKindLabel,
      'dbt:test': copy.nodePresentationTestKindLabel,
    },
  };
}
