export const sourceImportWizardCopy = {
  title: 'Add source',
  description:
    'Explore governed connections, inspect source objects, and attach supported origins to the canvas.',
  footer: {
    doneAction: 'Done',
    cancelAction: 'Cancel',
    attachingAction: 'Attaching...',
    attachAction: 'Attach sources to canvas',
  },
  selectConnectionError: 'Please select a connection',
  selectAtLeastOneObjectError: 'Select at least one importable source object.',
  loadConnectionsError: 'Failed to load warehouse connections.',
  loadSourceObjectsError: 'Failed to load source objects.',
  importSuccess: 'Sources attached successfully',
  importError: 'Failed to register data objects.',
  connection: {
    title: 'Choose database connection',
    description:
      'Choose which database connection should be used to discover candidate data objects',
    loading: 'Loading connections...',
    searchLabel: 'Search governed connections',
    catalogSource: 'Catalog: .dvt/warehouse-connections.json',
    empty: 'No governed database connections found.',
    emptyHint: 'Add database connections to the workspace catalog before importing sources.',
    noMatches: 'No governed connections match the current search.',
    createAction: 'New connection',
    createTitle: 'Register database connection',
    createDescription:
      'Create a governed catalog entry from a server-resolved credential reference.',
    createNameLabel: 'Connection name',
    createTypeLabel: 'Connection type',
    createDatabaseLabel: 'Database',
    createCredentialRefLabel: 'Credential reference',
    createSubmitAction: 'Create connection',
    creatingAction: 'Creating...',
    createCancelAction: 'Cancel',
    createValidationError: 'Name, database, and credential reference are required.',
    createSuccess: 'Warehouse connection created',
    createError: 'Failed to create warehouse connection.',
    testAction: 'Test connection',
    testingAction: 'Testing...',
    testPassed: 'Connection passed',
    testFailed: 'Connection failed',
    testError: 'Failed to test warehouse connection.',
    reachableObjects: 'objects reachable',
  },
  selection: {
    title: 'Browse source objects',
    descriptionPrefix: 'Choose supported objects to attach as source nodes. Selected:',
    destinationPosture:
      'Output target is selected on a DVT Sink node after sources are attached. Choose database, schema, table, and write mode there before preview or run.',
    loading: 'Loading source objects...',
    empty: 'No source objects are available for this connection.',
    searchLabel: 'Search source catalog',
    searchPlaceholder: 'Search name, locator, column, or type',
  },
  metadata: {
    title: 'Source metadata',
    description: 'Inspect the active source object before registering it into the canvas graph.',
    noObjectSelected: 'No source object selected',
    rowsUnknown: 'Rows unknown',
    sizeUnknown: 'Size unknown',
    noColumns: '0 columns',
    columnsUnavailable: 'Column metadata is not recorded for the active source object.',
    optionsUnavailable:
      'Import options are unavailable because this source object cannot yet be attached by the relational importer.',
  },
  grouping: {
    title: 'Grouping Strategy',
    description: 'Choose how relational source objects should be grouped in the dbt registry',
    options: {
      schema: {
        id: 'schema',
        label: 'Group by Schema (Recommended)',
        description: 'Creates one source per schema. Example: RAW.ERP.ORDERS -> source(erp)',
        badge: 'Enterprise-friendly',
      },
      database: {
        id: 'database',
        label: 'Group by Database',
        description: 'Creates one source per database. Best for small projects.',
      },
    },
  },
  options: {
    title: 'Metadata Options',
    description: 'Configure what metadata to include when registering data objects',
  },
  review: {
    title: 'Selected sources',
    description: 'Review the selected source objects before attaching them to the canvas.',
    previewTitle: 'Canvas attachment preview',
    connectionLabel: 'Connection:',
    sourceObjectsSelectedLabel: 'Source objects selected:',
    dataObjectGroupsLabel: 'Data object groups:',
    groupingStrategyLabel: 'Grouping strategy:',
    enabledLabel: 'Yes',
    disabledLabel: 'No',
    registryFileLabel: 'Registry file',
    destinationPosture:
      'Destination is configured on a DVT Sink node after origin registration; verify the output target before previewing or running the graph.',
    dataObjectGroupPrefix: 'data-object-group',
    moreSourceObjectsPrefix: '... and',
    moreSourceObjectsSuffix: 'more objects',
  },
  selectionBasket: {
    title: 'Selected sources',
    empty: 'No source objects selected yet.',
    selected: 'selected',
    remove: 'Remove',
    noColumns: 'Column metadata is not recorded for this selected source.',
    moreColumnsPrefix: 'and',
    moreColumnsSuffix: 'more columns',
  },
  catalog: {
    selectSourceObject: 'Select source object',
    selectSourceDatabase: 'Select source database',
    selectSourceSchema: 'Select source schema',
    inSourceDatabase: 'In source database',
    inspectSourceObjectMetadata: 'Inspect source object',
    metadata: 'metadata',
    rowSingular: 'row',
    rowPlural: 'rows',
    estimatedSizePrefix: 'Estimated',
    columnSingular: 'column',
    columnPlural: 'columns',
    objectSingular: 'object',
    objectPlural: 'objects',
    schemaSingular: 'schema',
    schemaPlural: 'schemas',
    allSelected: 'All selected',
    nullable: 'Nullable',
    required: 'Required',
    primaryKey: 'Primary key',
    unique: 'Unique',
    available: 'available',
    showing: 'Showing',
    of: 'of',
    filterAll: 'All',
    filterSelected: 'Selected',
    filterWithColumns: 'With columns',
    filterImportable: 'Importable',
    filterListLabel: 'Source catalog filters',
    filterAccessibilityPrefix: 'Filter source catalog by',
    locatorKindLabels: {
      relation: 'Relations',
      file: 'Files',
      endpoint: 'Endpoints',
      stream: 'Streams',
    },
    unsupportedImport:
      'Visible for inspection. This importer currently attaches relational source objects only.',
  },
  result: {
    title: 'Sources imported',
    description:
      'The selected source objects were written through the active Canvas authoring authority.',
    filesTitle: 'Source files updated',
    graphDraftWarning:
      'Canvas queued the imported source ids and will focus them when the governed draft authority refreshes.',
    dbtProjectFilesWarning:
      'The dbt project files were updated and the file-backed graph projection will refresh from project authority.',
  },
} as const;

export const sourceImportCatalogNumberFormatter = new Intl.NumberFormat('en-US');
