export const sourceImportWizardCopy = {
  title: 'Add source',
  description:
    'Explore governed connections, choose source tables, inspect metadata, and attach selected origins to the canvas.',
  footer: {
    doneAction: 'Done',
    cancelAction: 'Cancel',
    attachingAction: 'Attaching...',
    attachAction: 'Attach sources to canvas',
  },
  selectConnectionError: 'Please select a connection',
  selectAtLeastOneTableError: 'Please select at least one table',
  loadConnectionsError: 'Failed to load warehouse connections.',
  loadTablesError: 'Failed to load warehouse tables.',
  importSuccess: 'Sources attached successfully',
  importNoop: 'Selected data objects are already present in the workspace graph',
  importError: 'Failed to register data objects.',
  connection: {
    title: 'Choose database connection',
    description:
      'Choose which database connection should be used to discover candidate data objects',
    loading: 'Loading connections...',
    searchLabel: 'Search governed connections',
    catalogSource: 'Catalog: .dvt/warehouse-connections.json',
    empty: 'No governed database connections found.',
    emptyHint: 'Add database connections to the workspace catalog before importing sources.',
    noMatches: 'No governed connections match the current search.',
    createAction: 'New connection',
    createTitle: 'Register database connection',
    createDescription:
      'Create a governed catalog entry from a server-resolved credential reference.',
    createNameLabel: 'Connection name',
    createTypeLabel: 'Connection type',
    createDatabaseLabel: 'Database',
    createCredentialRefLabel: 'Credential reference',
    createSubmitAction: 'Create connection',
    creatingAction: 'Creating...',
    createCancelAction: 'Cancel',
    createValidationError: 'Name, database, and credential reference are required.',
    createSuccess: 'Warehouse connection created',
    createError: 'Failed to create warehouse connection.',
    testAction: 'Test connection',
    testingAction: 'Testing...',
    testPassed: 'Connection passed',
    testFailed: 'Connection failed',
    testError: 'Failed to test warehouse connection.',
    reachableTables: 'tables reachable',
  },
  selection: {
    title: 'Browse source tables',
    descriptionPrefix: 'Choose tables to attach as source nodes. Selected:',
    destinationPosture:
      'Output target is selected on a DVT Sink node after sources are attached. Choose database, schema, table, and write mode there before preview or run.',
    loading: 'Loading tables...',
    empty: 'No tables available for this connection.',
    searchLabel: 'Search source catalog',
    searchPlaceholder: 'Search schema, table, column, or type',
    rowsSuffix: 'rows',
  },
  metadata: {
    title: 'Source metadata',
    description: 'Inspect the active source object before registering it into the canvas graph.',
    noTableSelected: 'No source table selected',
    rowsUnknown: 'Rows unknown',
    sizeUnknown: 'Size unknown',
    noColumns: '0 columns',
    warehouseSource: 'Warehouse source',
    columnsUnavailable: 'Column metadata is not recorded for the active source object.',
  },
  grouping: {
    title: 'Grouping Strategy',
    description: 'Choose how discovered tables should be grouped into registered data objects',
  },
  options: {
    title: 'Metadata Options',
    description: 'Configure what metadata to include when registering data objects',
  },
  review: {
    title: 'Selected sources',
    description: 'Review the selected source objects before attaching them to the canvas.',
    previewTitle: 'Canvas attachment preview',
    connectionLabel: 'Connection:',
    tablesSelectedLabel: 'Tables selected:',
    dataObjectGroupsLabel: 'Data object groups:',
    groupingStrategyLabel: 'Grouping strategy:',
    enabledLabel: 'Yes',
    disabledLabel: 'No',
    destinationPosture:
      'Destination is configured on a DVT Sink node after origin registration; verify the output target before previewing or running the graph.',
    dataObjectGroupPrefix: 'data-object-group',
    moreTablesPrefix: '... and',
    moreTablesSuffix: 'more',
  },
  selectionBasket: {
    title: 'Selected sources',
    empty: 'No source tables selected yet.',
    selected: 'selected',
    remove: 'Remove',
  },
  catalog: {
    selectSourceTable: 'Select source table',
    selectSourceDatabase: 'Select source database',
    inspectSourceTableMetadata: 'Inspect source table',
    metadata: 'metadata',
    rowsUnknown: 'Rows unknown',
    rowSingular: 'row',
    rowPlural: 'rows',
    columnSingular: 'column',
    columnPlural: 'columns',
    tableSingular: 'table',
    tablePlural: 'tables',
    schemaSingular: 'schema',
    schemaPlural: 'schemas',
    allSelected: 'All selected',
    nullable: 'Nullable',
    required: 'Required',
    primaryKey: 'Primary key',
    unique: 'Unique',
    available: 'available',
    showing: 'Showing',
    of: 'of',
  },
  result: {
    title: 'Sources attached',
    description: 'Your selected tables have been attached to the workspace graph.',
    noopTitle: 'No new data objects were added',
    noopDescription:
      'The selected tables are already registered, so Canvas did not need to materialize new source nodes.',
    filesTitle: 'Registry files created',
    warning:
      'Canvas queued the imported source ids and will focus them when the governed draft authority refreshes.',
    noopWarning:
      'Canvas stayed unchanged because the selected registry entries already existed in the workspace graph.',
  },
} as const;

export const sourceImportCatalogNumberFormatter = new Intl.NumberFormat('en-US');
