export const lineageViewCopy = {
  title: 'Lineage Analysis',
  loading: 'Loading...',
  nodesSuffix: 'nodes',
  searchPlaceholder: 'Search by model name...',
  pinToCanvas: 'Pin to Canvas',
  pathLabel: 'Path:',
  fullGraphTitle: 'Full graph',
  impactSummary: 'Impact Summary',
  upstreamDependencies: 'Upstream Dependencies',
  downstreamConsumers: 'Downstream Consumers',
  exposuresAffected: 'Exposures Affected',
  routeLoadingTitle: 'Loading lineage',
  routeLoadingMessage: 'Fetching workspace graph context for lineage analysis.',
  routeEmptyTitle: 'No lineage focus available',
  routeEmptyMessage: 'Search for a model or load workspace graph data to inspect lineage.',
  routeErrorTitle: 'Lineage graph unavailable',
  routeErrorFallbackMessage: 'The workspace graph could not be loaded for lineage analysis.',
} as const;
